In [ ]:
import torch
import torch.nn as nn
from transformers import AutoModel
from torch.utils.data import Dataset

def collate_fn(batch):
    input_ids = torch.stack([item['input_ids'] for item in batch])
    attention_mask = torch.stack([item['attention_mask'] for item in batch])
    targets = torch.stack([item['target'] for item in batch])
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "target": targets
    }

class TitleDataset(Dataset):
    def __init__(self, df, tokenizer, target_col="target", max_length=32):
        self.targets = df[target_col].to_list()
        self.encodings = tokenizer(
            df["video_title"].to_list(),
            padding="max_length",
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        )

    def __len__(self):
        return len(self.targets)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["target"] = torch.tensor(self.targets[idx]).float()
        return item

class TitleRegressor(nn.Module):
    def __init__(self, model_name, dropout_rate=0.2, freeze_n_layers=None):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.encoder = AutoModel.from_pretrained(model_name)

        print(self.encoder.config)

        if freeze_n_layers is not None:
            self._freeze_layers(freeze_n_layers)
        
        hidden_dim = self.encoder.config.hidden_size
        self.regressor = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(128, 1)  # Output layer for regression
        )

    def _freeze_layers(self, n):
        # Freeze embeddings if present
        if hasattr(self.encoder, 'embeddings'):
            for param in self.encoder.embeddings.parameters():
                param.requires_grad = False

        # Try locating layer stack via known patterns
        candidate_paths = [
            ("encoder.layer", getattr(self.encoder, "encoder", None)),
            ("transformer.layer", getattr(self.encoder, "transformer", None)),
            ("distilbert.transformer.layer", getattr(getattr(self.encoder, "distilbert", None), "transformer", None)),
            ("layers", self.encoder),  # ModernBERT: layers at top-level
        ]

        for name, module in candidate_paths:
            if module and hasattr(module, "layer"):
                layers = getattr(module, "layer")
                if isinstance(layers, nn.ModuleList):
                    break
            elif isinstance(module, nn.Module) and hasattr(module, "layers"):
                layers = getattr(module, "layers")
                if isinstance(layers, nn.ModuleList):
                    break
        else:
            # Fallback: search recursively for first ModuleList with enough layers
            layers = next(
                (m for m in self.encoder.modules() if isinstance(m, nn.ModuleList) and len(m) >= n),
                None
            )
            if layers is None:
                raise ValueError("Cannot locate transformer layers in the model")

        # Cap n at available number of layers
        n = min(n, len(layers))
        print(f"Freezing first {n} of {len(layers)} layers.")

        for layer in layers[:n]:
            for param in layer.parameters():
                param.requires_grad = False


    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # CLS token
        return self.regressor(cls_embedding)

    def summary(self):
        print(f"TitleRegressor with {self.encoder.config.hidden_size} hidden size and {len(self.regressor)} layers.")
        total, trainable = 0, 0
        for name, param in self.named_parameters():  # fixed from `model.named_parameters()`
            total += param.numel()
            if param.requires_grad:
                trainable += param.numel()
                print(f"Trainable: {name} - {param.numel()} params")
        print()
        print(f"Total parameters: {total:,}")
        print(f"Trainable parameters: {trainable:,}")
        print(f"Percentage of trainable parameters: {trainable / total:.2%}")
        
        effective_parameters = int(total * (1 - self.dropout_rate) // 1)
        print(f"Effective parameters after dropout: {effective_parameters:,}")

        effective_trainable = int(trainable * (1 - self.dropout_rate) // 1)
        print(f"Effective trainable parameters after dropout: {effective_trainable:,}")

from sklearn.model_selection import train_test_split

from enum import Enum
# Model configuration
class ModelType(Enum):
    BERT_TINY = "prajjwal1/bert-tiny"
    DISTILBERT_BASE = "distilbert/distilbert-base-uncased"
    BERT_BASE_UNCASED = "google-bert/bert-base-uncased"
    MODERN_BERT_BASE = "answerdotai/ModernBERT-base"
    MPNET_BASE = "microsoft/mpnet-base"
    CONTRIEVER = "facebook/contriever"
    ALL_MINILM_L6_V2 = "sentence-transformers/all-MiniLM-L6-v2"
    E5_BASE_V2 = "intfloat/e5-base-v2"
    YOUTUBE_BERT = "flboehm/youtube-bert"
    YOUTUBE_BERT_10 = "flboehm/youtube-bert_10"
    T5_SMALL_YOUTUBE = "marianna13/t5-small-finetuned-youtube"
    DEBERTA_V3_XSMALL = "microsoft/deberta-v3-xsmall"
    YOUTUBE_XLM_ROBERTA_BASE = "AmaanP314/youtube-xlm-roberta-base-sentiment-multilingual"

model_selection = ModelType.BERT_TINY
model_name = model_selection.value
test_frac = 0.1
batch_size = 8192

# Channel-level split
channel_ids = norm_df["channel_id"].unique().to_list()
train_ch, test_ch = train_test_split(channel_ids, test_size=test_frac, random_state=42)

train_df = norm_df.filter(pl.col("channel_id").is_in(train_ch))
test_df = norm_df.filter(pl.col("channel_id").is_in(test_ch))

from transformers import AutoTokenizer
text_tokenizer = AutoTokenizer.from_pretrained(model_name)

train_dataset = TitleDataset(train_df, tokenizer=text_tokenizer)
test_dataset = TitleDataset(test_df, tokenizer=text_tokenizer)

from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn)

model = TitleRegressor(
    model_name=model_name,
    freeze_n_layers=22,
    dropout_rate=0.5
)
    
model.to(device)
model.summary()

NameError: name 'norm_df' is not defined

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
loss_fn = torch.nn.HuberLoss()
epochs = 256

from torch.utils.tensorboard import SummaryWriter
from datetime import datetime

log_dir = f"runs/title_regression_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
writer = SummaryWriter(log_dir=log_dir)

from sklearn.metrics import mean_squared_error, r2_score
from tqdm.notebook import trange

from torch.amp import autocast, GradScaler

scaler = GradScaler()

for epoch in trange(epochs, desc="Training Epochs"):
    model.train()
    total_loss = 0

    for batch in train_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        targets = batch["target"].unsqueeze(1).to(device)

        optimizer.zero_grad()

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)
            loss = loss_fn(preds, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

    # Log training loss
    writer.add_scalar("Loss/Train", total_loss / len(train_loader), epoch)

    if (epoch + 1) % 4 == 0:
        model.eval()
        val_preds = []
        val_targets = []
        val_loss = 0

        with torch.no_grad():
            for batch in test_loader:
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                targets = batch["target"].unsqueeze(1).to(device)

                with autocast(device_type='cuda'):
                    preds = model(input_ids, attention_mask)
                    loss = loss_fn(preds, targets)

                val_preds.extend(preds.squeeze().cpu().tolist())
                val_targets.extend(targets.squeeze().cpu().tolist())
                val_loss += loss.item()

        val_mse = mean_squared_error(val_targets, val_preds)
        val_r2 = r2_score(val_targets, val_preds)

        # Log validation metrics
        writer.add_scalar("Loss/Val", val_loss / len(test_loader), epoch)
        writer.add_scalar("Metrics/Val_MSE", val_mse, epoch)
        writer.add_scalar("Metrics/Val_R2", val_r2, epoch)

        print(f"Epoch {epoch+1}/{epochs} - "
              f"Train Loss: {total_loss / len(train_loader):.4f} | "
              f"Val Loss: {val_loss / len(test_loader):.4f} | "
              f"Val MSE: {val_mse:.4f} | Val R2: {val_r2:.4f}")

:

In [ ]:
import os

print(os.getcwd())

from pathlib import Path
import av
import numpy as np
import torch
import polars as pl

# Config
data_path = "../data/video_data.parquet"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load metadata
df = pl.read_parquet(data_path)

df = df.filter(
    pl.col('media_type') == 'video',
    pl.col("view_count").is_not_null(),
    )

# Get unique channel list
channels = df.select("channel_id").unique().to_series()

# List to collect per-channel normalized DataFrames
normalized_chunks = []

# Loop through channels and normalize
for ch in channels:
    
    channel_df = df.filter(pl.col("channel_id") == ch)
    # log scale view_count
    channel_df = channel_df.with_columns(
        pl.col("view_count").log().alias("log_view_count")
    )

    # set target to log view_count
    channel_df = channel_df.with_columns(
        pl.col("log_view_count").alias("target")
    )
    
    # Normalize view count by Z-score
    mean_vc = channel_df.select(pl.col("log_view_count").mean()).item()
    std_vc = channel_df.select(pl.col("log_view_count").std()).item()
    channel_df = channel_df.with_columns(
        ((pl.col("log_view_count") - mean_vc) / std_vc).alias("target")
    )

    # Add mean, std for debug
    channel_df = channel_df.with_columns(
        pl.lit(mean_vc).alias("mean_log_view_count"),
        pl.lit(std_vc).alias("std_log_view_count")
    )

    normalized_chunks.append(channel_df)

# Concatenate all normalized chunks
norm_df = pl.concat(normalized_chunks)
norm_df = norm_df.drop_nulls(subset=["target", "video_title"])


print(norm_df.shape)

f:\Project\YTIntroModel\notebooks
(7713, 28)

In [ ]:
import torch
import torch.nn as nn
from transformers import AutoModel
from torch.utils.data import Dataset

def collate_fn(batch):
    input_ids = torch.stack([item['input_ids'] for item in batch])
    attention_mask = torch.stack([item['attention_mask'] for item in batch])
    targets = torch.stack([item['target'] for item in batch])
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "target": targets
    }

class TitleDataset(Dataset):
    def __init__(self, df, tokenizer, target_col="target", max_length=32):
        self.targets = df[target_col].to_list()
        self.encodings = tokenizer(
            df["video_title"].to_list(),
            padding="max_length",
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        )

    def __len__(self):
        return len(self.targets)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["target"] = torch.tensor(self.targets[idx]).float()
        return item

class TitleRegressor(nn.Module):
    def __init__(self, model_name, dropout_rate=0.2, freeze_n_layers=None):
        super().__init__()
        self.dropout_rate = dropout_rate
        self.encoder = AutoModel.from_pretrained(model_name)

        print(self.encoder.config)

        if freeze_n_layers is not None:
            self._freeze_layers(freeze_n_layers)
        
        hidden_dim = self.encoder.config.hidden_size
        self.regressor = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(128, 1)  # Output layer for regression
        )

    def _freeze_layers(self, n):
        # Freeze embeddings if present
        if hasattr(self.encoder, 'embeddings'):
            for param in self.encoder.embeddings.parameters():
                param.requires_grad = False

        # Try locating layer stack via known patterns
        candidate_paths = [
            ("encoder.layer", getattr(self.encoder, "encoder", None)),
            ("transformer.layer", getattr(self.encoder, "transformer", None)),
            ("distilbert.transformer.layer", getattr(getattr(self.encoder, "distilbert", None), "transformer", None)),
            ("layers", self.encoder),  # ModernBERT: layers at top-level
        ]

        for name, module in candidate_paths:
            if module and hasattr(module, "layer"):
                layers = getattr(module, "layer")
                if isinstance(layers, nn.ModuleList):
                    break
            elif isinstance(module, nn.Module) and hasattr(module, "layers"):
                layers = getattr(module, "layers")
                if isinstance(layers, nn.ModuleList):
                    break
        else:
            # Fallback: search recursively for first ModuleList with enough layers
            layers = next(
                (m for m in self.encoder.modules() if isinstance(m, nn.ModuleList) and len(m) >= n),
                None
            )
            if layers is None:
                raise ValueError("Cannot locate transformer layers in the model")

        # Cap n at available number of layers
        n = min(n, len(layers))
        print(f"Freezing first {n} of {len(layers)} layers.")

        for layer in layers[:n]:
            for param in layer.parameters():
                param.requires_grad = False


    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # CLS token
        return self.regressor(cls_embedding)

    def summary(self):
        print(f"TitleRegressor with {self.encoder.config.hidden_size} hidden size and {len(self.regressor)} layers.")
        total, trainable = 0, 0
        for name, param in self.named_parameters():  # fixed from `model.named_parameters()`
            total += param.numel()
            if param.requires_grad:
                trainable += param.numel()
                print(f"Trainable: {name} - {param.numel()} params")
        print()
        print(f"Total parameters: {total:,}")
        print(f"Trainable parameters: {trainable:,}")
        print(f"Percentage of trainable parameters: {trainable / total:.2%}")
        
        effective_parameters = int(total * (1 - self.dropout_rate) // 1)
        print(f"Effective parameters after dropout: {effective_parameters:,}")

        effective_trainable = int(trainable * (1 - self.dropout_rate) // 1)
        print(f"Effective trainable parameters after dropout: {effective_trainable:,}")

from sklearn.model_selection import train_test_split

from enum import Enum
# Model configuration
class ModelType(Enum):
    BERT_TINY = "prajjwal1/bert-tiny"
    DISTILBERT_BASE = "distilbert/distilbert-base-uncased"
    BERT_BASE_UNCASED = "google-bert/bert-base-uncased"
    MODERN_BERT_BASE = "answerdotai/ModernBERT-base"
    MPNET_BASE = "microsoft/mpnet-base"
    CONTRIEVER = "facebook/contriever"
    ALL_MINILM_L6_V2 = "sentence-transformers/all-MiniLM-L6-v2"
    E5_BASE_V2 = "intfloat/e5-base-v2"
    YOUTUBE_BERT = "flboehm/youtube-bert"
    YOUTUBE_BERT_10 = "flboehm/youtube-bert_10"
    T5_SMALL_YOUTUBE = "marianna13/t5-small-finetuned-youtube"
    DEBERTA_V3_XSMALL = "microsoft/deberta-v3-xsmall"
    YOUTUBE_XLM_ROBERTA_BASE = "AmaanP314/youtube-xlm-roberta-base-sentiment-multilingual"

model_selection = ModelType.BERT_TINY
model_name = model_selection.value
test_frac = 0.1
batch_size = 8192

# Channel-level split
channel_ids = norm_df["channel_id"].unique().to_list()
train_ch, test_ch = train_test_split(channel_ids, test_size=test_frac, random_state=42)

train_df = norm_df.filter(pl.col("channel_id").is_in(train_ch))
test_df = norm_df.filter(pl.col("channel_id").is_in(test_ch))

from transformers import AutoTokenizer
text_tokenizer = AutoTokenizer.from_pretrained(model_name)

train_dataset = TitleDataset(train_df, tokenizer=text_tokenizer)
test_dataset = TitleDataset(test_df, tokenizer=text_tokenizer)

from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn)

model = TitleRegressor(
    model_name=model_name,
    freeze_n_layers=22,
    dropout_rate=0.5
)
    
model.to(device)
model.summary()

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 128,
  "initializer_range": 0.02,
  "intermediate_size": 512,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 2,
  "num_hidden_layers": 2,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.0.dev0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Freezing first 2 of 2 layers.
TitleRegressor with 128 hidden size and 4 layers.
Trainable: encoder.pooler.dense.weight - 16384 params
Trainable: encoder.pooler.dense.bias - 128 params
Trainable: regressor.0.weight - 16384 params
Trainable: regressor.0.bias - 128 params
Trainable: regressor.3.weight - 128 params
Trainable: regressor.3.bias - 1 params

Total parameters: 4,402,561
Trainable parameters: 33,153
Percentage of trainable parameters: 0.75%
Effective parameters after dropout: 2,201,280
Effective trainable parameters after dropout: 16,576

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
loss_fn = torch.nn.HuberLoss()
epochs = 256

from torch.utils.tensorboard import SummaryWriter
from datetime import datetime

log_dir = f"runs/title_regression_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
writer = SummaryWriter(log_dir=log_dir)

from sklearn.metrics import mean_squared_error, r2_score
from tqdm.notebook import trange

from torch.amp import autocast, GradScaler

scaler = GradScaler()

for epoch in trange(epochs, desc="Training Epochs"):
    model.train()
    total_loss = 0

    for batch in train_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        targets = batch["target"].unsqueeze(1).to(device)

        optimizer.zero_grad()

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)
            loss = loss_fn(preds, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

    # Log training loss
    writer.add_scalar("Loss/Train", total_loss / len(train_loader), epoch)

    if (epoch + 1) % 4 == 0:
        model.eval()
        val_preds = []
        val_targets = []
        val_loss = 0

        with torch.no_grad():
            for batch in test_loader:
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                targets = batch["target"].unsqueeze(1).to(device)

                with autocast(device_type='cuda'):
                    preds = model(input_ids, attention_mask)
                    loss = loss_fn(preds, targets)

                val_preds.extend(preds.squeeze().cpu().tolist())
                val_targets.extend(targets.squeeze().cpu().tolist())
                val_loss += loss.item()

        val_mse = mean_squared_error(val_targets, val_preds)
        val_r2 = r2_score(val_targets, val_preds)

        # Log validation metrics
        writer.add_scalar("Loss/Val", val_loss / len(test_loader), epoch)
        writer.add_scalar("Metrics/Val_MSE", val_mse, epoch)
        writer.add_scalar("Metrics/Val_R2", val_r2, epoch)

        print(f"Epoch {epoch+1}/{epochs} - "
              f"Train Loss: {total_loss / len(train_loader):.4f} | "
              f"Val Loss: {val_loss / len(test_loader):.4f} | "
              f"Val MSE: {val_mse:.4f} | Val R2: {val_r2:.4f}")

Training Epochs:   0%|          | 0/256 [00:00<?, ?it/s]

Epoch 4/256 - Train Loss: 0.4265 | Val Loss: 0.4135 | Val MSE: 0.9903 | Val R2: 0.0020
Epoch 8/256 - Train Loss: 0.4007 | Val Loss: 0.4139 | Val MSE: 0.9836 | Val R2: 0.0086
Epoch 12/256 - Train Loss: 0.3923 | Val Loss: 0.4188 | Val MSE: 0.9878 | Val R2: 0.0045
Epoch 16/256 - Train Loss: 0.3770 | Val Loss: 0.4237 | Val MSE: 0.9965 | Val R2: -0.0044
Epoch 20/256 - Train Loss: 0.3752 | Val Loss: 0.4298 | Val MSE: 1.0089 | Val R2: -0.0168
Epoch 24/256 - Train Loss: 0.3686 | Val Loss: 0.4273 | Val MSE: 1.0052 | Val R2: -0.0131
Epoch 28/256 - Train Loss: 0.3624 | Val Loss: 0.4276 | Val MSE: 1.0083 | Val R2: -0.0162
Epoch 32/256 - Train Loss: 0.3599 | Val Loss: 0.4289 | Val MSE: 1.0134 | Val R2: -0.0213
Epoch 36/256 - Train Loss: 0.3557 | Val Loss: 0.4298 | Val MSE: 1.0170 | Val R2: -0.0249
Epoch 40/256 - Train Loss: 0.3545 | Val Loss: 0.4312 | Val MSE: 1.0198 | Val R2: -0.0278
Epoch 44/256 - Train Loss: 0.3543 | Val Loss: 0.4310 | Val MSE: 1.0194 | Val R2: -0.0274
Epoch 48/256 - Train Loss: 0.3484 | Val Loss: 0.4305 | Val MSE: 1.0187 | Val R2: -0.0267
Epoch 52/256 - Train Loss: 0.3466 | Val Loss: 0.4297 | Val MSE: 1.0177 | Val R2: -0.0257
Epoch 56/256 - Train Loss: 0.3421 | Val Loss: 0.4284 | Val MSE: 1.0147 | Val R2: -0.0227
Epoch 60/256 - Train Loss: 0.3430 | Val Loss: 0.4283 | Val MSE: 1.0140 | Val R2: -0.0219
Epoch 64/256 - Train Loss: 0.3366 | Val Loss: 0.4270 | Val MSE: 1.0112 | Val R2: -0.0191
Epoch 68/256 - Train Loss: 0.3431 | Val Loss: 0.4279 | Val MSE: 1.0138 | Val R2: -0.0217
Epoch 72/256 - Train Loss: 0.3351 | Val Loss: 0.4282 | Val MSE: 1.0155 | Val R2: -0.0235
Epoch 76/256 - Train Loss: 0.3369 | Val Loss: 0.4277 | Val MSE: 1.0152 | Val R2: -0.0232
Epoch 80/256 - Train Loss: 0.3336 | Val Loss: 0.4272 | Val MSE: 1.0142 | Val R2: -0.0221
Epoch 84/256 - Train Loss: 0.3314 | Val Loss: 0.4252 | Val MSE: 1.0093 | Val R2: -0.0172
Epoch 88/256 - Train Loss: 0.3347 | Val Loss: 0.4261 | Val MSE: 1.0116 | Val R2: -0.0195
Epoch 92/256 - Train Loss: 0.3278 | Val Loss: 0.4248 | Val MSE: 1.0090 | Val R2: -0.0170
Epoch 96/256 - Train Loss: 0.3285 | Val Loss: 0.4270 | Val MSE: 1.0139 | Val R2: -0.0219
Epoch 100/256 - Train Loss: 0.3279 | Val Loss: 0.4261 | Val MSE: 1.0113 | Val R2: -0.0192
Epoch 104/256 - Train Loss: 0.3236 | Val Loss: 0.4275 | Val MSE: 1.0140 | Val R2: -0.0219
Epoch 108/256 - Train Loss: 0.3240 | Val Loss: 0.4273 | Val MSE: 1.0134 | Val R2: -0.0214
Epoch 112/256 - Train Loss: 0.3248 | Val Loss: 0.4254 | Val MSE: 1.0100 | Val R2: -0.0179
Epoch 116/256 - Train Loss: 0.3232 | Val Loss: 0.4266 | Val MSE: 1.0123 | Val R2: -0.0203
Epoch 120/256 - Train Loss: 0.3240 | Val Loss: 0.4255 | Val MSE: 1.0097 | Val R2: -0.0177
Epoch 124/256 - Train Loss: 0.3218 | Val Loss: 0.4282 | Val MSE: 1.0159 | Val R2: -0.0239
Epoch 128/256 - Train Loss: 0.3190 | Val Loss: 0.4274 | Val MSE: 1.0147 | Val R2: -0.0226
Epoch 132/256 - Train Loss: 0.3196 | Val Loss: 0.4285 | Val MSE: 1.0181 | Val R2: -0.0261
Epoch 136/256 - Train Loss: 0.3206 | Val Loss: 0.4267 | Val MSE: 1.0135 | Val R2: -0.0215
Epoch 140/256 - Train Loss: 0.3152 | Val Loss: 0.4280 | Val MSE: 1.0165 | Val R2: -0.0244
Epoch 144/256 - Train Loss: 0.3177 | Val Loss: 0.4300 | Val MSE: 1.0220 | Val R2: -0.0301
Epoch 148/256 - Train Loss: 0.3199 | Val Loss: 0.4282 | Val MSE: 1.0184 | Val R2: -0.0264
Epoch 152/256 - Train Loss: 0.3170 | Val Loss: 0.4289 | Val MSE: 1.0201 | Val R2: -0.0281
Epoch 156/256 - Train Loss: 0.3174 | Val Loss: 0.4271 | Val MSE: 1.0152 | Val R2: -0.0231
Epoch 160/256 - Train Loss: 0.3175 | Val Loss: 0.4291 | Val MSE: 1.0187 | Val R2: -0.0267
Epoch 164/256 - Train Loss: 0.3172 | Val Loss: 0.4268 | Val MSE: 1.0133 | Val R2: -0.0212
Epoch 168/256 - Train Loss: 0.3130 | Val Loss: 0.4304 | Val MSE: 1.0224 | Val R2: -0.0304
Epoch 172/256 - Train Loss: 0.3149 | Val Loss: 0.4305 | Val MSE: 1.0235 | Val R2: -0.0315
Epoch 176/256 - Train Loss: 0.3107 | Val Loss: 0.4300 | Val MSE: 1.0230 | Val R2: -0.0311
Epoch 180/256 - Train Loss: 0.3121 | Val Loss: 0.4303 | Val MSE: 1.0238 | Val R2: -0.0319
Epoch 184/256 - Train Loss: 0.3136 | Val Loss: 0.4317 | Val MSE: 1.0273 | Val R2: -0.0354
Epoch 188/256 - Train Loss: 0.3140 | Val Loss: 0.4310 | Val MSE: 1.0255 | Val R2: -0.0335
Epoch 192/256 - Train Loss: 0.3125 | Val Loss: 0.4295 | Val MSE: 1.0214 | Val R2: -0.0294
Epoch 196/256 - Train Loss: 0.3090 | Val Loss: 0.4318 | Val MSE: 1.0269 | Val R2: -0.0350
Epoch 200/256 - Train Loss: 0.3054 | Val Loss: 0.4327 | Val MSE: 1.0294 | Val R2: -0.0375
Epoch 204/256 - Train Loss: 0.3093 | Val Loss: 0.4331 | Val MSE: 1.0302 | Val R2: -0.0383
Epoch 208/256 - Train Loss: 0.3126 | Val Loss: 0.4318 | Val MSE: 1.0266 | Val R2: -0.0347
Epoch 212/256 - Train Loss: 0.3091 | Val Loss: 0.4329 | Val MSE: 1.0299 | Val R2: -0.0380
Epoch 216/256 - Train Loss: 0.3081 | Val Loss: 0.4324 | Val MSE: 1.0294 | Val R2: -0.0375
Epoch 220/256 - Train Loss: 0.3070 | Val Loss: 0.4331 | Val MSE: 1.0316 | Val R2: -0.0397
Epoch 224/256 - Train Loss: 0.3127 | Val Loss: 0.4339 | Val MSE: 1.0338 | Val R2: -0.0419
Epoch 228/256 - Train Loss: 0.3071 | Val Loss: 0.4326 | Val MSE: 1.0288 | Val R2: -0.0368
Epoch 232/256 - Train Loss: 0.3058 | Val Loss: 0.4306 | Val MSE: 1.0230 | Val R2: -0.0310
Epoch 236/256 - Train Loss: 0.3088 | Val Loss: 0.4329 | Val MSE: 1.0283 | Val R2: -0.0364
Epoch 240/256 - Train Loss: 0.3062 | Val Loss: 0.4335 | Val MSE: 1.0302 | Val R2: -0.0383
Epoch 244/256 - Train Loss: 0.3044 | Val Loss: 0.4354 | Val MSE: 1.0366 | Val R2: -0.0447
Epoch 248/256 - Train Loss: 0.3017 | Val Loss: 0.4348 | Val MSE: 1.0358 | Val R2: -0.0439
Epoch 252/256 - Train Loss: 0.3069 | Val Loss: 0.4373 | Val MSE: 1.0409 | Val R2: -0.0491
Epoch 256/256 - Train Loss: 0.3059 | Val Loss: 0.4364 | Val MSE: 1.0381 | Val R2: -0.0463

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
loss_fn = torch.nn.HuberLoss()
epochs = 256

from torch.utils.tensorboard import SummaryWriter
from datetime import datetime

log_dir = f"runs/title_regression_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
writer = SummaryWriter(log_dir=log_dir)

from sklearn.metrics import mean_squared_error, r2_score
from tqdm.notebook import trange

from torch.amp import autocast, GradScaler

scaler = GradScaler()

for epoch in trange(epochs, desc="Training Epochs"):
    model.train()
    total_loss = 0

    for batch in train_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        targets = batch["target"].unsqueeze(1).to(device)

        optimizer.zero_grad()

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)
            loss = loss_fn(preds, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

    # Log training loss
    writer.add_scalar("Loss/Train", total_loss / len(train_loader), epoch)

    if (epoch + 1) % 4 == 0:
        model.eval()
        val_preds = []
        val_targets = []
        val_loss = 0

        with torch.no_grad():
            for batch in test_loader:
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                targets = batch["target"].unsqueeze(1).to(device)

                with autocast(device_type='cuda'):
                    preds = model(input_ids, attention_mask)
                    loss = loss_fn(preds, targets)

                val_preds.extend(preds.squeeze().cpu().tolist())
                val_targets.extend(targets.squeeze().cpu().tolist())
                val_loss += loss.item()

        val_mse = mean_squared_error(val_targets, val_preds)
        val_r2 = r2_score(val_targets, val_preds)

        # Log validation metrics
        writer.add_scalar("Loss/Val", val_loss / len(test_loader), epoch)
        writer.add_scalar("Metrics/Val_MSE", val_mse, epoch)
        writer.add_scalar("Metrics/Val_R2", val_r2, epoch)

        print(f"Epoch {epoch+1}/{epochs} - "
              f"Train Loss: {total_loss / len(train_loader):.4f} | "
              f"Val Loss: {val_loss / len(test_loader):.4f} | "
              f"Val MSE: {val_mse:.4f} | Val R2: {val_r2:.4f}")

Training Epochs:   0%|          | 0/256 [00:00<?, ?it/s]

Epoch 4/256 - Train Loss: 0.3066 | Val Loss: 0.4361 | Val MSE: 1.0393 | Val R2: -0.0474
Epoch 8/256 - Train Loss: 0.3044 | Val Loss: 0.4336 | Val MSE: 1.0329 | Val R2: -0.0410
Epoch 12/256 - Train Loss: 0.3027 | Val Loss: 0.4346 | Val MSE: 1.0345 | Val R2: -0.0426
Epoch 16/256 - Train Loss: 0.3026 | Val Loss: 0.4361 | Val MSE: 1.0389 | Val R2: -0.0471
Epoch 20/256 - Train Loss: 0.3085 | Val Loss: 0.4370 | Val MSE: 1.0407 | Val R2: -0.0489
Epoch 24/256 - Train Loss: 0.3057 | Val Loss: 0.4330 | Val MSE: 1.0300 | Val R2: -0.0381
Epoch 28/256 - Train Loss: 0.3023 | Val Loss: 0.4327 | Val MSE: 1.0295 | Val R2: -0.0376
Epoch 32/256 - Train Loss: 0.3045 | Val Loss: 0.4337 | Val MSE: 1.0322 | Val R2: -0.0403
Epoch 36/256 - Train Loss: 0.3011 | Val Loss: 0.4334 | Val MSE: 1.0313 | Val R2: -0.0394
Epoch 40/256 - Train Loss: 0.3030 | Val Loss: 0.4329 | Val MSE: 1.0297 | Val R2: -0.0378
Epoch 44/256 - Train Loss: 0.3025 | Val Loss: 0.4346 | Val MSE: 1.0341 | Val R2: -0.0422
Epoch 48/256 - Train Loss: 0.3034 | Val Loss: 0.4367 | Val MSE: 1.0408 | Val R2: -0.0490
Epoch 52/256 - Train Loss: 0.3014 | Val Loss: 0.4390 | Val MSE: 1.0474 | Val R2: -0.0556
Epoch 56/256 - Train Loss: 0.2996 | Val Loss: 0.4352 | Val MSE: 1.0352 | Val R2: -0.0433
Epoch 60/256 - Train Loss: 0.2986 | Val Loss: 0.4343 | Val MSE: 1.0311 | Val R2: -0.0392
Epoch 64/256 - Train Loss: 0.2949 | Val Loss: 0.4309 | Val MSE: 1.0241 | Val R2: -0.0321
Epoch 68/256 - Train Loss: 0.2977 | Val Loss: 0.4337 | Val MSE: 1.0303 | Val R2: -0.0384
Epoch 72/256 - Train Loss: 0.3008 | Val Loss: 0.4344 | Val MSE: 1.0312 | Val R2: -0.0393
Epoch 76/256 - Train Loss: 0.3007 | Val Loss: 0.4319 | Val MSE: 1.0251 | Val R2: -0.0332
Epoch 80/256 - Train Loss: 0.2972 | Val Loss: 0.4301 | Val MSE: 1.0196 | Val R2: -0.0276
Epoch 84/256 - Train Loss: 0.2993 | Val Loss: 0.4320 | Val MSE: 1.0232 | Val R2: -0.0312
Epoch 88/256 - Train Loss: 0.2955 | Val Loss: 0.4317 | Val MSE: 1.0240 | Val R2: -0.0320
Epoch 92/256 - Train Loss: 0.2948 | Val Loss: 0.4311 | Val MSE: 1.0221 | Val R2: -0.0301
Epoch 96/256 - Train Loss: 0.3004 | Val Loss: 0.4298 | Val MSE: 1.0172 | Val R2: -0.0252
Epoch 100/256 - Train Loss: 0.2979 | Val Loss: 0.4283 | Val MSE: 1.0141 | Val R2: -0.0221
Epoch 104/256 - Train Loss: 0.2959 | Val Loss: 0.4301 | Val MSE: 1.0200 | Val R2: -0.0280
Epoch 108/256 - Train Loss: 0.2980 | Val Loss: 0.4307 | Val MSE: 1.0198 | Val R2: -0.0278
Epoch 112/256 - Train Loss: 0.2938 | Val Loss: 0.4311 | Val MSE: 1.0183 | Val R2: -0.0263
Epoch 116/256 - Train Loss: 0.2903 | Val Loss: 0.4305 | Val MSE: 1.0159 | Val R2: -0.0239
Epoch 120/256 - Train Loss: 0.2978 | Val Loss: 0.4307 | Val MSE: 1.0184 | Val R2: -0.0264
Epoch 124/256 - Train Loss: 0.2943 | Val Loss: 0.4325 | Val MSE: 1.0235 | Val R2: -0.0315
Epoch 128/256 - Train Loss: 0.2937 | Val Loss: 0.4320 | Val MSE: 1.0216 | Val R2: -0.0296
Epoch 132/256 - Train Loss: 0.2956 | Val Loss: 0.4293 | Val MSE: 1.0149 | Val R2: -0.0228
Epoch 136/256 - Train Loss: 0.2985 | Val Loss: 0.4294 | Val MSE: 1.0167 | Val R2: -0.0247
Epoch 140/256 - Train Loss: 0.2972 | Val Loss: 0.4304 | Val MSE: 1.0201 | Val R2: -0.0281
Epoch 144/256 - Train Loss: 0.2965 | Val Loss: 0.4291 | Val MSE: 1.0173 | Val R2: -0.0253
Epoch 148/256 - Train Loss: 0.2971 | Val Loss: 0.4299 | Val MSE: 1.0180 | Val R2: -0.0260
Epoch 152/256 - Train Loss: 0.2954 | Val Loss: 0.4301 | Val MSE: 1.0168 | Val R2: -0.0248
Epoch 156/256 - Train Loss: 0.2955 | Val Loss: 0.4306 | Val MSE: 1.0167 | Val R2: -0.0247
Epoch 160/256 - Train Loss: 0.2946 | Val Loss: 0.4273 | Val MSE: 1.0104 | Val R2: -0.0183
Epoch 164/256 - Train Loss: 0.2963 | Val Loss: 0.4291 | Val MSE: 1.0152 | Val R2: -0.0232
Epoch 168/256 - Train Loss: 0.2936 | Val Loss: 0.4307 | Val MSE: 1.0173 | Val R2: -0.0253
Epoch 172/256 - Train Loss: 0.2913 | Val Loss: 0.4278 | Val MSE: 1.0090 | Val R2: -0.0169
Epoch 176/256 - Train Loss: 0.2926 | Val Loss: 0.4284 | Val MSE: 1.0106 | Val R2: -0.0185
Epoch 180/256 - Train Loss: 0.2919 | Val Loss: 0.4278 | Val MSE: 1.0084 | Val R2: -0.0163
Epoch 184/256 - Train Loss: 0.2921 | Val Loss: 0.4300 | Val MSE: 1.0130 | Val R2: -0.0210
Epoch 188/256 - Train Loss: 0.2923 | Val Loss: 0.4249 | Val MSE: 1.0017 | Val R2: -0.0096
Epoch 192/256 - Train Loss: 0.2893 | Val Loss: 0.4273 | Val MSE: 1.0085 | Val R2: -0.0164
Epoch 196/256 - Train Loss: 0.2942 | Val Loss: 0.4273 | Val MSE: 1.0111 | Val R2: -0.0190
Epoch 200/256 - Train Loss: 0.2943 | Val Loss: 0.4278 | Val MSE: 1.0096 | Val R2: -0.0175
Epoch 204/256 - Train Loss: 0.2922 | Val Loss: 0.4266 | Val MSE: 1.0062 | Val R2: -0.0141
Epoch 208/256 - Train Loss: 0.2908 | Val Loss: 0.4287 | Val MSE: 1.0119 | Val R2: -0.0198
Epoch 212/256 - Train Loss: 0.2950 | Val Loss: 0.4272 | Val MSE: 1.0082 | Val R2: -0.0161
Epoch 216/256 - Train Loss: 0.2903 | Val Loss: 0.4268 | Val MSE: 1.0060 | Val R2: -0.0139
Epoch 220/256 - Train Loss: 0.2875 | Val Loss: 0.4291 | Val MSE: 1.0111 | Val R2: -0.0190
Epoch 224/256 - Train Loss: 0.2881 | Val Loss: 0.4300 | Val MSE: 1.0128 | Val R2: -0.0207
Epoch 228/256 - Train Loss: 0.2922 | Val Loss: 0.4269 | Val MSE: 1.0061 | Val R2: -0.0140
Epoch 232/256 - Train Loss: 0.2914 | Val Loss: 0.4309 | Val MSE: 1.0159 | Val R2: -0.0239
Epoch 236/256 - Train Loss: 0.2841 | Val Loss: 0.4300 | Val MSE: 1.0140 | Val R2: -0.0220
Epoch 240/256 - Train Loss: 0.2928 | Val Loss: 0.4301 | Val MSE: 1.0123 | Val R2: -0.0203
Epoch 244/256 - Train Loss: 0.2964 | Val Loss: 0.4276 | Val MSE: 1.0055 | Val R2: -0.0134
Epoch 248/256 - Train Loss: 0.2897 | Val Loss: 0.4303 | Val MSE: 1.0131 | Val R2: -0.0211
Epoch 252/256 - Train Loss: 0.2896 | Val Loss: 0.4298 | Val MSE: 1.0124 | Val R2: -0.0203
Epoch 256/256 - Train Loss: 0.2923 | Val Loss: 0.4278 | Val MSE: 1.0070 | Val R2: -0.0149

In [ ]:
# load the model
model_path = "models/title_regressor_bert_tiny.pt"
if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path, map_location=device))
    print(f"Model loaded from {model_path}")

Model loaded from models/title_regressor_bert_tiny.pt

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

inf_df

shape: (385, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ video_des ┆ media_typ ┆ … ┆ target    ┆ mean_log_ ┆ std_log_v ┆ predicte │
│ ---       ┆ le        ┆ cription  ┆ e         ┆   ┆ ---       ┆ view_coun ┆ iew_count ┆ d_target │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ t         ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆ ---       ┆ f64       ┆ f32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -hMr1TeEn ┆ Lost      ┆ Start     ┆ video     ┆ … ┆ -0.129147 ┆ 14.252996 ┆ 0.853826  ┆ -0.22009 │
│ NA        ┆ Media     ┆ speaking  ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆ From Nick ┆ a new     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ elodeon   ┆ language  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20…       ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ -HuEtZH6W ┆ Top 40    ┆ As of     ┆ video     ┆ … ┆ 2.251116  ┆ 14.252996 ┆ 0.853826  ┆ 0.172607 │
│ Dw        ┆ Lost or   ┆ 2/28/15:  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Banned    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Episodes… ┆  1) LOST  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆  2) h…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ -JQdbaHJZ ┆ 7         ┆ Spanish   ┆ video     ┆ … ┆ 1.905423  ┆ 14.252996 ┆ 0.853826  ┆ 0.513184 │
│ Yc        ┆ Insanely  ┆ Version:  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shitty    ┆ https://w ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Superhero ┆ ww.y…     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Ri…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -QDNJcMWJ ┆ Top 13    ┆ Today on  ┆ video     ┆ … ┆ -0.973468 ┆ 14.252996 ┆ 0.853826  ┆ 0.185669 │
│ iM        ┆ Lost      ┆ blameiton ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Horror    ┆ jorge,    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Films |   ┆ we're…    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ bla…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -WVzB_2bg ┆ 10        ┆ Today on  ┆ video     ┆ … ┆ 1.274986  ┆ 14.252996 ┆ 0.853826  ┆ 0.039307 │
│ Ks        ┆ Episodes  ┆ blameiton ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ of Kids   ┆ jorge, we ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shows     ┆ ta…       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ That…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ YFJN2bqE- ┆ 5 More    ┆ Tonight   ┆ video     ┆ … ┆ -0.970177 ┆ 14.42901  ┆ 1.195854  ┆ -0.51855 │
│ sA        ┆ Strange   ┆ we are    ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ and       ┆ checking  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Unnerving ┆ out fi…   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Y…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Z03BX5IEo ┆ Disturbin ┆ The       ┆ video     ┆ … ┆ 1.121428  ┆ 14.42901  ┆ 1.195854  ┆ 0.654785 │
│ ZI        ┆ g Things  ┆ Internet  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ from      ┆ is full   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Around …  ┆ of        ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ creepy…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ZjFBi3otr ┆ The "Real ┆ 🌏 Get    ┆ video     ┆ … ┆ -0.139099 ┆ 14.42901  ┆ 1.195854  ┆ 0.159424 │
│ U8        ┆ Blair     ┆ exclusive ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Witch"    ┆ NordVPN   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Inciden…  ┆ deal h…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ zLd9Q6687 ┆ Exploring ┆ On        ┆ video     ┆ … ┆ -0.361229 ┆ 14.42901  ┆ 1.195854  ┆ -0.30078 │
│ Cg        ┆ the "Stra ┆ Twitter,  ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ yedAway"  ┆ a user    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Vo…       ┆ named Ty  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ (a…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ zr64hUY6q ┆ The       ┆ In late   ┆ video     ┆ … ┆ 0.997894  ┆ 14.42901  ┆ 1.195854  ┆ -0.27099 │
│ lg        ┆ Search    ┆ 2015, a   ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ Term that ┆ 4Channer  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Made a    ┆ share…    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Yo…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'duration', 'fps', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df

shape: (385, 10)
┌────────────┬────────────┬──────────┬──────┬───┬───────────┬────────────┬────────────┬────────────┐
│ video_id   ┆ video_titl ┆ duration ┆ fps  ┆ … ┆ target    ┆ mean_log_v ┆ std_log_vi ┆ predicted_ │
│ ---        ┆ e          ┆ ---      ┆ ---  ┆   ┆ ---       ┆ iew_count  ┆ ew_count   ┆ target     │
│ str        ┆ ---        ┆ i64      ┆ f64  ┆   ┆ f64       ┆ ---        ┆ ---        ┆ ---        │
│            ┆ str        ┆          ┆      ┆   ┆           ┆ f64        ┆ f64        ┆ f32        │
╞════════════╪════════════╪══════════╪══════╪═══╪═══════════╪════════════╪════════════╪════════════╡
│ -hMr1TeEnN ┆ Lost Media ┆ 1301     ┆ 60.0 ┆ … ┆ -0.129147 ┆ 14.252996  ┆ 0.853826   ┆ -0.220093  │
│ A          ┆ From Nicke ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ lodeon 20… ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ -HuEtZH6WD ┆ Top 40     ┆ 2201     ┆ 30.0 ┆ … ┆ 2.251116  ┆ 14.252996  ┆ 0.853826   ┆ 0.172607   │
│ w          ┆ Lost or    ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Banned     ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Episodes…  ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ -JQdbaHJZY ┆ 7 Insanely ┆ 631      ┆ 60.0 ┆ … ┆ 1.905423  ┆ 14.252996  ┆ 0.853826   ┆ 0.513184   │
│ c          ┆ Shitty     ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Superhero  ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Ri…        ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ -QDNJcMWJi ┆ Top 13     ┆ 1322     ┆ 60.0 ┆ … ┆ -0.973468 ┆ 14.252996  ┆ 0.853826   ┆ 0.185669   │
│ M          ┆ Lost       ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Horror     ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Films |    ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ bla…       ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ -WVzB_2bgK ┆ 10         ┆ 1487     ┆ 60.0 ┆ … ┆ 1.274986  ┆ 14.252996  ┆ 0.853826   ┆ 0.039307   │
│ s          ┆ Episodes   ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ of Kids    ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Shows      ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ That…      ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …         ┆ …          ┆ …          ┆ …          │
│ YFJN2bqE-s ┆ 5 More     ┆ 525      ┆ 30.0 ┆ … ┆ -0.970177 ┆ 14.42901   ┆ 1.195854   ┆ -0.518555  │
│ A          ┆ Strange    ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ and        ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Unnerving  ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Y…         ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ Z03BX5IEoZ ┆ Disturbing ┆ 803      ┆ 30.0 ┆ … ┆ 1.121428  ┆ 14.42901   ┆ 1.195854   ┆ 0.654785   │
│ I          ┆ Things     ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ from       ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Around …   ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ ZjFBi3otrU ┆ The "Real  ┆ 1899     ┆ 30.0 ┆ … ┆ -0.139099 ┆ 14.42901   ┆ 1.195854   ┆ 0.159424   │
│ 8          ┆ Blair      ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Witch"     ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Inciden…   ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ zLd9Q6687C ┆ Exploring  ┆ 355      ┆ 30.0 ┆ … ┆ -0.361229 ┆ 14.42901   ┆ 1.195854   ┆ -0.300781  │
│ g          ┆ the "Stray ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ edAway"    ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Vo…        ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│ zr64hUY6ql ┆ The Search ┆ 2224     ┆ 60.0 ┆ … ┆ 0.997894  ┆ 14.42901   ┆ 1.195854   ┆ -0.270996  │
│ g          ┆ Term that  ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
│            ┆ Made a Yo… ┆          ┆      ┆   ┆           ┆            ┆            ┆            │
└────────────┴────────────┴──────────┴──────┴───┴───────────┴────────────┴────────────┴────────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'duration', 'fps', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target', 'duration', 'fps']

inf_df = inf_df.select(select_cols)

inf_df

DuplicateError: the name 'duration' is duplicate

It's possible that multiple expressions are returning the same default column name. If this is the case, try renaming the columns with `.alias("new_name")` to avoid duplicate column names.

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df

shape: (385, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ video_id   ┆ video_titl ┆ view_count ┆ channel_h ┆ target    ┆ mean_log_ ┆ std_log_v ┆ predicted │
│ ---        ┆ e          ┆ ---        ┆ andle     ┆ ---       ┆ view_coun ┆ iew_count ┆ _target   │
│ str        ┆ ---        ┆ i64        ┆ ---       ┆ f64       ┆ t         ┆ ---       ┆ ---       │
│            ┆ str        ┆            ┆ str       ┆           ┆ ---       ┆ f64       ┆ f32       │
│            ┆            ┆            ┆           ┆           ┆ f64       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -hMr1TeEnN ┆ Lost Media ┆ 1387101    ┆ @blameito ┆ -0.129147 ┆ 14.252996 ┆ 0.853826  ┆ -0.220093 │
│ A          ┆ From Nicke ┆            ┆ njorge    ┆           ┆           ┆           ┆           │
│            ┆ lodeon 20… ┆            ┆           ┆           ┆           ┆           ┆           │
│ -HuEtZH6WD ┆ Top 40     ┆ 10586159   ┆ @blameito ┆ 2.251116  ┆ 14.252996 ┆ 0.853826  ┆ 0.172607  │
│ w          ┆ Lost or    ┆            ┆ njorge    ┆           ┆           ┆           ┆           │
│            ┆ Banned     ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Episodes…  ┆            ┆           ┆           ┆           ┆           ┆           │
│ -JQdbaHJZY ┆ 7 Insanely ┆ 7880456    ┆ @blameito ┆ 1.905423  ┆ 14.252996 ┆ 0.853826  ┆ 0.513184  │
│ c          ┆ Shitty     ┆            ┆ njorge    ┆           ┆           ┆           ┆           │
│            ┆ Superhero  ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Ri…        ┆            ┆           ┆           ┆           ┆           ┆           │
│ -QDNJcMWJi ┆ Top 13     ┆ 674565     ┆ @blameito ┆ -0.973468 ┆ 14.252996 ┆ 0.853826  ┆ 0.185669  │
│ M          ┆ Lost       ┆            ┆ njorge    ┆           ┆           ┆           ┆           │
│            ┆ Horror     ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Films |    ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ bla…       ┆            ┆           ┆           ┆           ┆           ┆           │
│ -WVzB_2bgK ┆ 10         ┆ 4600211    ┆ @blameito ┆ 1.274986  ┆ 14.252996 ┆ 0.853826  ┆ 0.039307  │
│ s          ┆ Episodes   ┆            ┆ njorge    ┆           ┆           ┆           ┆           │
│            ┆ of Kids    ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Shows      ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ That…      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ YFJN2bqE-s ┆ 5 More     ┆ 578863     ┆ @Nexpo    ┆ -0.970177 ┆ 14.42901  ┆ 1.195854  ┆ -0.518555 │
│ A          ┆ Strange    ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ and        ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Unnerving  ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Y…         ┆            ┆           ┆           ┆           ┆           ┆           │
│ Z03BX5IEoZ ┆ Disturbing ┆ 7060841    ┆ @Nexpo    ┆ 1.121428  ┆ 14.42901  ┆ 1.195854  ┆ 0.654785  │
│ I          ┆ Things     ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ from       ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Around …   ┆            ┆           ┆           ┆           ┆           ┆           │
│ ZjFBi3otrU ┆ The "Real  ┆ 1563861    ┆ @Nexpo    ┆ -0.139099 ┆ 14.42901  ┆ 1.195854  ┆ 0.159424  │
│ 8          ┆ Blair      ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Witch"     ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Inciden…   ┆            ┆           ┆           ┆           ┆           ┆           │
│ zLd9Q6687C ┆ Exploring  ┆ 1199042    ┆ @Nexpo    ┆ -0.361229 ┆ 14.42901  ┆ 1.195854  ┆ -0.300781 │
│ g          ┆ the "Stray ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ edAway"    ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Vo…        ┆            ┆           ┆           ┆           ┆           ┆           │
│ zr64hUY6ql ┆ The Search ┆ 6091136    ┆ @Nexpo    ┆ 0.997894  ┆ 14.42901  ┆ 1.195854  ┆ -0.270996 │
│ g          ┆ Term that  ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ Made a Yo… ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df = inf_df.with_columns(
    # error
    (pl.col("predicted_target") - pl.col("target")).alias("error"),
).sort("error")


inf_df

shape: (385, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ view_coun ┆ channel_h ┆ … ┆ mean_log_ ┆ std_log_v ┆ predicted ┆ error    │
│ ---       ┆ le        ┆ t         ┆ andle     ┆   ┆ view_coun ┆ iew_count ┆ _target   ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ f64      │
│           ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ f64       ┆ f32       ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ iHzzSao6y ┆ The       ┆ 42141929  ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ -0.012161 ┆ -2.23631 │
│ pE        ┆ Simple    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ Solution  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ to        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Traffic   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ tdOKTV0kP ┆ Top 20    ┆ 16429197  ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ 0.539551  ┆ -2.22632 │
│ M0        ┆ Saddest   ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆ Moments   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ In Kid …  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -HuEtZH6W ┆ Top 40    ┆ 10586159  ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ 0.172607  ┆ -2.07850 │
│ Dw        ┆ Lost or   ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ Banned    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Episodes… ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ vIADc1oMi ┆ Top 30    ┆ 7727912   ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ -0.138184 ┆ -2.02071 │
│ BE        ┆ Disturbin ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆ g Moments ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ in K…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3Ztj_4fFJ ┆ Dan Schne ┆ 7863656   ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ -0.059784 ┆ -1.96270 │
│ ck        ┆ ider: A   ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ Scandal   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ at Ni…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ u7TlWQ9qd ┆ The Lost  ┆ 284776    ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ 0.236572  ┆ 2.220041 │
│ ik        ┆ "Uncle    ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆          │
│           ┆ Walt"     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Short Wa… ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ufsYK3Eec ┆ Behind    ┆ 571687    ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ -0.024277 ┆ 2.225337 │
│ w4        ┆ the       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Scenes of ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ TEKOI     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TftIoyO7Z ┆ The Myste ┆ 136464    ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ 0.271973  ┆ 2.450495 │
│ qE        ┆ rious     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Death of  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Elisa …   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ lk4lBV5wg ┆ NEW: More ┆ 341702    ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ -0.308105 ┆ 2.476933 │
│ GM        ┆ Designs   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ for Your  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Sid…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FhqNGaA3f ┆ 15,000:   ┆ 20111     ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ -0.418213 ┆ 3.361504 │
│ vY        ┆ Thank     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ you.      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df = inf_df.with_columns(
    # error
    (pl.col("predicted_target") - pl.col("target")).abs().alias("error"),
).sort("error")


inf_df

shape: (385, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ view_coun ┆ channel_h ┆ … ┆ mean_log_ ┆ std_log_v ┆ predicted ┆ error    │
│ ---       ┆ le        ┆ t         ┆ andle     ┆   ┆ view_coun ┆ iew_count ┆ _target   ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ f64      │
│           ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ f64       ┆ f32       ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ xUyVEax17 ┆ The       ┆ 1723275   ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ 0.124146  ┆ 0.00087  │
│ iA        ┆ "Where    ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆          │
│           ┆ Did This  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Image     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Come…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TCyuiJeyG ┆ Tea Time  ┆ 1201150   ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ -0.352539 ┆ 0.007221 │
│ 2c        ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Que2myhwr ┆ Investiga ┆ 1867036   ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ 0.001497  ┆ 0.007578 │
│ 48        ┆ ting the  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ "Magic    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ World…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ wAUGFiLrp ┆ "My       ┆ 1519661   ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ -0.153931 ┆ 0.009143 │
│ lg        ┆ Sister"   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ bhyYgnhhK ┆ The True  ┆ 6731369   ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ 0.304443  ┆ 0.011415 │
│ Fw        ┆ Cost of   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ the Royal ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Fam…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ tdOKTV0kP ┆ Top 20    ┆ 16429197  ┆ @blameito ┆ … ┆ 14.252996 ┆ 0.853826  ┆ 0.539551  ┆ 2.226322 │
│ M0        ┆ Saddest   ┆           ┆ njorge    ┆   ┆           ┆           ┆           ┆          │
│           ┆ Moments   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ In Kid …  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ iHzzSao6y ┆ The       ┆ 42141929  ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ -0.012161 ┆ 2.236318 │
│ pE        ┆ Simple    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Solution  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ to        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Traffic   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TftIoyO7Z ┆ The Myste ┆ 136464    ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ 0.271973  ┆ 2.450495 │
│ qE        ┆ rious     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Death of  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Elisa …   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ lk4lBV5wg ┆ NEW: More ┆ 341702    ┆ @CGPGrey  ┆ … ┆ 15.418685 ┆ 0.961204  ┆ -0.308105 ┆ 2.476933 │
│ GM        ┆ Designs   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ for Your  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Sid…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FhqNGaA3f ┆ 15,000:   ┆ 20111     ┆ @Nexpo    ┆ … ┆ 14.42901  ┆ 1.195854  ┆ -0.418213 ┆ 3.361504 │
│ vY        ┆ Thank     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ you.      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df = inf_df.with_columns(
    # error
    (pl.col("predicted_target") - pl.col("target")).abs().alias("error"),
).sort("error")

inf_df = inf_df.with_columns(
    # predicted view count
    (pl.col("predicted_target").exp() * pl.col("std_log_view_count") + pl.col("mean_log_view_count")).alias("predicted_view_count"),
)

inf_df

shape: (385, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ video_id  ┆ video_tit ┆ view_coun ┆ channel_h ┆ … ┆ std_log_v ┆ predicted ┆ error    ┆ predicted │
│ ---       ┆ le        ┆ t         ┆ andle     ┆   ┆ iew_count ┆ _target   ┆ ---      ┆ _view_cou │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ nt        │
│           ┆ str       ┆ i64       ┆ str       ┆   ┆ f64       ┆ f32       ┆          ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ xUyVEax17 ┆ The       ┆ 1723275   ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.124146  ┆ 0.00087  ┆ 15.219682 │
│ iA        ┆ "Where    ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Did This  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Image     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Come…     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TCyuiJeyG ┆ Tea Time  ┆ 1201150   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.352539 ┆ 0.007221 ┆ 15.269577 │
│ 2c        ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ Que2myhwr ┆ Investiga ┆ 1867036   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.001497  ┆ 0.007578 ┆ 15.626656 │
│ 48        ┆ ting the  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ "Magic    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ World…    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ wAUGFiLrp ┆ "My       ┆ 1519661   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.153931 ┆ 0.009143 ┆ 15.454253 │
│ lg        ┆ Sister"   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ bhyYgnhhK ┆ The True  ┆ 6731369   ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ 0.304443  ┆ 0.011415 ┆ 16.721953 │
│ Fw        ┆ Cost of   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ the Royal ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Fam…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ tdOKTV0kP ┆ Top 20    ┆ 16429197  ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.539551  ┆ 2.226322 ┆ 15.71751  │
│ M0        ┆ Saddest   ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Moments   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ In Kid …  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ iHzzSao6y ┆ The       ┆ 42141929  ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.012161 ┆ 2.236318 ┆ 16.368271 │
│ pE        ┆ Simple    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Solution  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ to        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Traffic   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TftIoyO7Z ┆ The Myste ┆ 136464    ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.271973  ┆ 2.450495 ┆ 15.998629 │
│ qE        ┆ rious     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Death of  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Elisa …   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ lk4lBV5wg ┆ NEW: More ┆ 341702    ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.308105 ┆ 2.476933 ┆ 16.125014 │
│ GM        ┆ Designs   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ for Your  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Sid…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ FhqNGaA3f ┆ 15,000:   ┆ 20111     ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.418213 ┆ 3.361504 ┆ 15.216148 │
│ vY        ┆ Thank     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ you.      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df = inf_df.with_columns(
    # error
    (pl.col("predicted_target") - pl.col("target")).abs().alias("error"),
).sort("error")

inf_df = inf_df.with_columns(
    # predicted view count
    (pl.col("predicted_target") * pl.col("std_log_view_count") + pl.col("mean_log_view_count")).alias("predicted_view_count"),
)

inf_df

shape: (385, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ video_id  ┆ video_tit ┆ view_coun ┆ channel_h ┆ … ┆ std_log_v ┆ predicted ┆ error    ┆ predicted │
│ ---       ┆ le        ┆ t         ┆ andle     ┆   ┆ iew_count ┆ _target   ┆ ---      ┆ _view_cou │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ nt        │
│           ┆ str       ┆ i64       ┆ str       ┆   ┆ f64       ┆ f32       ┆          ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ xUyVEax17 ┆ The       ┆ 1723275   ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.124146  ┆ 0.00087  ┆ 14.358995 │
│ iA        ┆ "Where    ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Did This  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Image     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Come…     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TCyuiJeyG ┆ Tea Time  ┆ 1201150   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.352539 ┆ 0.007221 ┆ 14.007425 │
│ 2c        ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ Que2myhwr ┆ Investiga ┆ 1867036   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.001497  ┆ 0.007578 ┆ 14.430801 │
│ 48        ┆ ting the  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ "Magic    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ World…    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ wAUGFiLrp ┆ "My       ┆ 1519661   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.153931 ┆ 0.009143 ┆ 14.244932 │
│ lg        ┆ Sister"   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ bhyYgnhhK ┆ The True  ┆ 6731369   ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ 0.304443  ┆ 0.011415 ┆ 15.711317 │
│ Fw        ┆ Cost of   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ the Royal ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Fam…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ tdOKTV0kP ┆ Top 20    ┆ 16429197  ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.539551  ┆ 2.226322 ┆ 14.713679 │
│ M0        ┆ Saddest   ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Moments   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ In Kid …  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ iHzzSao6y ┆ The       ┆ 42141929  ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.012161 ┆ 2.236318 ┆ 15.406995 │
│ pE        ┆ Simple    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Solution  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ to        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Traffic   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TftIoyO7Z ┆ The Myste ┆ 136464    ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.271973  ┆ 2.450495 ┆ 14.75425  │
│ qE        ┆ rious     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Death of  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Elisa …   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ lk4lBV5wg ┆ NEW: More ┆ 341702    ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.308105 ┆ 2.476933 ┆ 15.122533 │
│ GM        ┆ Designs   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ for Your  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Sid…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ FhqNGaA3f ┆ 15,000:   ┆ 20111     ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.418213 ┆ 3.361504 ┆ 13.928889 │
│ vY        ┆ Thank     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ you.      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [ ]:
inf_df = test_df.clone()
# create prediction column
inf_df = inf_df.with_columns(
    pl.lit(np.nan).alias("predicted_target")
)

# Inference
model.eval()
predictions = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        with autocast(device_type='cuda'):
            preds = model(input_ids, attention_mask)

        predictions.extend(preds.squeeze().cpu().tolist())
        
# Update the DataFrame with predictions
inf_df = inf_df.with_columns(
    pl.Series(predictions, dtype=pl.Float32).alias("predicted_target")
)

select_cols = ['video_id', 'video_title', 'view_count',
               'channel_handle', 'target', 'mean_log_view_count',
               'std_log_view_count', 'predicted_target']

inf_df = inf_df.select(select_cols)

inf_df = inf_df.with_columns(
    # error
    (pl.col("predicted_target") - pl.col("target")).abs().alias("error"),
).sort("error")

inf_df = inf_df.with_columns(
    # predicted view count
    ((pl.col("predicted_target") * pl.col("std_log_view_count") + pl.col("mean_log_view_count"))).exp().alias("predicted_view_count"),
)

inf_df

shape: (385, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ video_id  ┆ video_tit ┆ view_coun ┆ channel_h ┆ … ┆ std_log_v ┆ predicted ┆ error    ┆ predicted │
│ ---       ┆ le        ┆ t         ┆ andle     ┆   ┆ iew_count ┆ _target   ┆ ---      ┆ _view_cou │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ nt        │
│           ┆ str       ┆ i64       ┆ str       ┆   ┆ f64       ┆ f32       ┆          ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ xUyVEax17 ┆ The       ┆ 1723275   ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.124146  ┆ 0.00087  ┆ 1.7220e6  │
│ iA        ┆ "Where    ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Did This  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Image     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Come…     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TCyuiJeyG ┆ Tea Time  ┆ 1201150   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.352539 ┆ 0.007221 ┆ 1.2116e6  │
│ 2c        ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ Que2myhwr ┆ Investiga ┆ 1867036   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.001497  ┆ 0.007578 ┆ 1.8502e6  │
│ 48        ┆ ting the  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ "Magic    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ World…    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ wAUGFiLrp ┆ "My       ┆ 1519661   ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.153931 ┆ 0.009143 ┆ 1.5364e6  │
│ lg        ┆ Sister"   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Analysis  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ bhyYgnhhK ┆ The True  ┆ 6731369   ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ 0.304443  ┆ 0.011415 ┆ 6.6579e6  │
│ Fw        ┆ Cost of   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ the Royal ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Fam…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ tdOKTV0kP ┆ Top 20    ┆ 16429197  ┆ @blameito ┆ … ┆ 0.853826  ┆ 0.539551  ┆ 2.226322 ┆ 2.4551e6  │
│ M0        ┆ Saddest   ┆           ┆ njorge    ┆   ┆           ┆           ┆          ┆           │
│           ┆ Moments   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ In Kid …  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ iHzzSao6y ┆ The       ┆ 42141929  ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.012161 ┆ 2.236318 ┆ 4.9110e6  │
│ pE        ┆ Simple    ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Solution  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ to        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Traffic   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ TftIoyO7Z ┆ The Myste ┆ 136464    ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ 0.271973  ┆ 2.450495 ┆ 2.5568e6  │
│ qE        ┆ rious     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Death of  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Elisa …   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ lk4lBV5wg ┆ NEW: More ┆ 341702    ┆ @CGPGrey  ┆ … ┆ 0.961204  ┆ -0.308105 ┆ 2.476933 ┆ 3.6952e6  │
│ GM        ┆ Designs   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ for Your  ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ Sid…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ FhqNGaA3f ┆ 15,000:   ┆ 20111     ┆ @Nexpo    ┆ … ┆ 1.195854  ┆ -0.418213 ┆ 3.361504 ┆ 1.1201e6  │
│ vY        ┆ Thank     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ you.      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [ ]:
import torch
import polars as pl
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import r2_score
from torch.nn.functional import cosine_similarity

# Ensure model exposes embedding extraction
def get_cls_embeddings(model, test_loader, device="cuda"):
    model.eval()
    cls_embeddings = []
    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            outputs = model.encoder(input_ids=input_ids, attention_mask=attention_mask)
            cls = outputs.last_hidden_state[:, 0, :]
            cls_embeddings.append(cls.cpu())
    return torch.cat(cls_embeddings, dim=0).numpy()

In [ ]:
inf_df = inf_df.with_columns(
    ((pl.col("predicted_target") * pl.col("std_log_view_count") + pl.col("mean_log_view_count"))).exp().alias("predicted_view_count"),
)

In [ ]:
# Step 1: Extract CLS Embeddings
print("[CLS] Extracting CLS token embeddings from test set...")
cls_embeddings = get_cls_embeddings(model, test_loader, device)
print(f"[CLS] Shape: {cls_embeddings.shape}")

[CLS] Extracting CLS token embeddings from test set...
[CLS] Shape: (385, 128)

In [ ]:
# Step 2: Run KMeans Clustering
n_clusters = 20  # change if needed
print(f"[KMeans] Clustering into {n_clusters} clusters...")
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
cluster_ids = kmeans.fit_predict(cls_embeddings)

inf_df = inf_df.with_columns(
    pl.Series(cluster_ids).alias("cluster_id")
)

[KMeans] Clustering into 20 clusters...

In [ ]:
# Step 3: Per-Cluster Metrics
print("\n=== Per-Cluster Performance ===")
for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    if len(cluster) < 2:
        print(f"Cluster {cid:>2}: Too few samples ({len(cluster)})")
        continue
    y_true = cluster["target"].to_numpy()
    y_pred = cluster["predicted_target"].to_numpy()
    mean_err = cluster["error"].mean()
    r2 = r2_score(y_true, y_pred)
    print(f"Cluster {cid:>2}: R² = {r2:.4f} | Mean Error = {mean_err:.3f} | N = {len(cluster)}")

=== Per-Cluster Performance ===
Cluster  0: R² = -0.9347 | Mean Error = 0.502 | N = 3
Cluster  1: R² = 0.3052 | Mean Error = 0.704 | N = 28
Cluster  2: R² = 0.4503 | Mean Error = 0.238 | N = 31
Cluster  3: R² = 0.2451 | Mean Error = 0.606 | N = 26
Cluster  4: R² = 0.8048 | Mean Error = 0.146 | N = 33
Cluster  5: R² = 0.0998 | Mean Error = 0.563 | N = 13
Cluster  6: R² = 0.1728 | Mean Error = 0.736 | N = 33
Cluster  7: R² = -0.1259 | Mean Error = 0.637 | N = 13
Cluster  8: R² = 0.4607 | Mean Error = 0.300 | N = 10
Cluster  9: R² = -0.1294 | Mean Error = 1.558 | N = 2
Cluster 10: R² = 0.1766 | Mean Error = 0.852 | N = 25
Cluster 11: R² = -0.0311 | Mean Error = 0.788 | N = 12
Cluster 12: R² = 0.1447 | Mean Error = 0.556 | N = 20
Cluster 13: R² = 0.1373 | Mean Error = 1.229 | N = 17
Cluster 14: R² = -0.0012 | Mean Error = 1.063 | N = 9
Cluster 15: R² = 0.2946 | Mean Error = 0.616 | N = 25
Cluster 16: R² = 0.0636 | Mean Error = 1.501 | N = 16
Cluster 17: R² = -0.0801 | Mean Error = 0.436 | N = 18
Cluster 18: R² = 0.0857 | Mean Error = 1.099 | N = 31
Cluster 19: R² = 0.0849 | Mean Error = 1.181 | N = 20

In [ ]:
# Step 4: Intra-Cluster Neighbor Inspection
print("\n=== Intra-Cluster Nearest Neighbor Error Inspection ===")
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
emb_tensor = torch.tensor(cls_embeddings).float()

for i in range(min(3, len(emb_tensor))):  # adjust range as needed
    cid = clusters[i]
    indices_in_cluster = [j for j, c in enumerate(clusters) if c == cid and j != i]
    if not indices_in_cluster:
        continue

    query = emb_tensor[i].unsqueeze(0)
    cluster_embs = emb_tensor[indices_in_cluster]
    sims = cosine_similarity(query, cluster_embs).cpu().numpy().flatten()
    topk_idx = sims.argsort()[-3:][::-1]
    real_indices = [indices_in_cluster[j] for j in topk_idx]

    print(f"\n▶ {titles[i]} (err = {errors[i]:.3f}) [Cluster {cid}]")
    for j in real_indices:
        print(f"  → {titles[j]} (err = {errors[j]:.3f})")

=== Intra-Cluster Nearest Neighbor Error Inspection ===

▶ The "Where Did This Image Come From?" Iceberg (err = 0.001) [Cluster 17]
  → Death & Dynasties (err = 0.128)
  → Explaining Ratafak Plachta | blameitonjorge (err = 0.156)
  → Should all locks have keys? Phones, Castles, Encryption, and You. (err = 0.176)

▶ Tea Time Analysis (err = 0.007) [Cluster 4]
  → Ten Years Later (err = 0.294)
  → The True Cost of the Royal Family Explained (err = 0.011)
  → Where is Scandinavia? (err = 0.223)

▶ Investigating the "Magic World of Ania” (err = 0.008) [Cluster 4]
  → YouTube vs Grey: A Ballad of Accidental Suspension (err = 0.064)
  → The Lost Media Gameshow Iceberg | blameitonjorge (err = 0.123)
  → What is "This Room Does Not Exist"? (err = 0.146)

In [ ]:
# Step 4: Intra-Cluster Neighbor Inspection
print("\n=== Intra-Cluster Nearest Neighbor Error Inspection ===")
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
emb_tensor = torch.tensor(cls_embeddings).float()

for i in range(min(10, len(emb_tensor))):  # adjust range as needed
    cid = clusters[i]
    indices_in_cluster = [j for j, c in enumerate(clusters) if c == cid and j != i]
    if not indices_in_cluster:
        continue

    query = emb_tensor[i].unsqueeze(0)
    cluster_embs = emb_tensor[indices_in_cluster]
    sims = cosine_similarity(query, cluster_embs).cpu().numpy().flatten()
    topk_idx = sims.argsort()[-3:][::-1]
    real_indices = [indices_in_cluster[j] for j in topk_idx]

    print(f"\n▶ {titles[i]} (err = {errors[i]:.3f}) [Cluster {cid}]")
    for j in real_indices:
        print(f"  → {titles[j]} (err = {errors[j]:.3f})")

=== Intra-Cluster Nearest Neighbor Error Inspection ===

▶ The "Where Did This Image Come From?" Iceberg (err = 0.001) [Cluster 17]
  → Death & Dynasties (err = 0.128)
  → Explaining Ratafak Plachta | blameitonjorge (err = 0.156)
  → Should all locks have keys? Phones, Castles, Encryption, and You. (err = 0.176)

▶ Tea Time Analysis (err = 0.007) [Cluster 4]
  → Ten Years Later (err = 0.294)
  → The True Cost of the Royal Family Explained (err = 0.011)
  → Where is Scandinavia? (err = 0.223)

▶ Investigating the "Magic World of Ania” (err = 0.008) [Cluster 4]
  → YouTube vs Grey: A Ballad of Accidental Suspension (err = 0.064)
  → The Lost Media Gameshow Iceberg | blameitonjorge (err = 0.123)
  → What is "This Room Does Not Exist"? (err = 0.146)

▶ "My Sister" Analysis (err = 0.009) [Cluster 4]
  → 2020 Vision: The YouTube Channel Predicting Death (err = 0.079)
  → What is "This Room Does Not Exist"? (err = 0.146)
  → What is a Leap Year? (err = 0.057)

▶ The True Cost of the Royal Family Explained (err = 0.011) [Cluster 4]
  → Where is Scandinavia? (err = 0.223)
  → Groundhog Day Explained (err = 0.208)
  → Ten Years Later (err = 0.294)

▶ Re: The Trouble With The Electoral College – Cities, Metro Areas, Elections and The United States (err = 0.015) [Cluster 4]
  → Tea Time Analysis (err = 0.007)
  → Ten Years Later (err = 0.294)
  → Where is Scandinavia? (err = 0.223)

▶ Patrice Wilson Live Stream: Explained (err = 0.016) [Cluster 2]
  → What If the Electoral College is Tied? (err = 0.195)
  → 11 Insane Knockoffs of Popular Children's' Shows From Around The World (err = 0.249)
  → The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)

▶ No Flag Northern Ireland (err = 0.023) [Cluster 3]
  → The Debt Limit Explained (err = 0.270)
  → Lost Media Found in 2021 | blameitonjorge (err = 0.247)
  → My Experience with a Stalker (err = 0.157)

▶ 15 Lost Disney Cartoons, Episodes, & Shorts That We May Never See Again | blameitonjorge (err = 0.023) [Cluster 2]
  → What If the Electoral College is Tied? (err = 0.195)
  → John Kricfalusi: An Open Secret | blameitonjorge (err = 0.198)
  → The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)

▶ Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027) [Cluster 1]
  → 40 MORE Lost or Banned Episodes of Kids Shows (err = 0.305)
  → Vatican City Explained (err = 0.983)
  → 12 Lost Pieces of Cartoon Network Media | blameitonjorge (err = 0.866)

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")


# Optional: print titles closest to the cluster centroid
def top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5):
    indices = [i for i, c in enumerate(cluster_ids) if c == cid]
    cluster_embs = emb_tensor[indices]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_k = sims.argsort()[-k:][::-1]
    return [inf_df["video_title"][indices[i]] for i in top_k]

print("\n=== Cluster Summaries (Representative Titles) ===")
for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    if len(cluster) < 2:
        continue
    print(f"\n📦 Cluster {cid} — {len(cluster)} samples")
    reps = top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5)
    for title in reps:
        print(f"  - {title}")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

=== Cluster Summaries (Representative Titles) ===

📦 Cluster 0 — 3 samples
  - Las Vegas isn't Las Vegas
  - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge
  - The Battle of SHARKS!

📦 Cluster 1 — 28 samples
  - Vatican City Explained
  - Top 10 Best Episodes of Goosebumps | blameitonjorge
  - 12 Lost Pieces of Cartoon Network Media | blameitonjorge
  - Gemini and the End of the World
  - The European Union Explained*

📦 Cluster 2 — 31 samples
  - Hi I'm Mary Mary: Explained
  - What If the Electoral College is Tied?
  - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge
  - Unnerving YouTube Channels #2
  - What's Going On with "Dad"?

📦 Cluster 3 — 26 samples
  - The Debt Limit Explained
  - No Flag Northern Ireland
  - Into the Abyss of Haunted PS1
  - The Simple Secret of Runway Numbers
  - A Redditor's Dive Into Turmoil

📦 Cluster 4 — 33 samples
  - What is "This Room Does Not Exist"?
  - Ten Years Later
  - Tea Time Analysis
  - Groundhog Day Explained
  - The True Cost of the Royal Family Explained

📦 Cluster 5 — 13 samples
  - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown)
  - Is Pluto a planet?
  - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge
  - Disturbing Lost Media From Television
  - Disturbing Things from Around the Internet [Vol. 7]

📦 Cluster 6 — 33 samples
  - Why Resident Evil 6 Failed
  - Exploring the Horrors of SOMA
  - Lost Media Found in the Strangest Ways 2
  - 15 Hilariously Awful Wii Games | blameitonjorge
  - History of the Union Jack

📦 Cluster 7 — 13 samples
  - Abstractions: Explained
  - The Race to Win Staten Island
  - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge
  - 🚛 🚗 The Interstate's Forgotten Code 🚗 🚛
  - Daylight Saving Time Explained

📦 Cluster 8 — 10 samples
  - Google Translate’s Strange Responses
  - Gas Stations and Sonic Sound Effects - Why?
  - The Lost Media of Creepypastas
  - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge
  - Lost Media From Nickelodeon 2022

📦 Cluster 9 — 2 samples
  - Inside Colorado's Weed Research Lab
  - Top 20 Unintentionally Disturbing Kids' Characters From Around The World

📦 Cluster 10 — 25 samples
  - Magibon's Online Stalker
  - How Drug Trafficking Destroyed This Popular Video Game
  - How AIs, like ChatGPT, Learn
  - An Empty City is Eerie Magic
  - 8 Animal Misconceptions Rundown

📦 Cluster 11 — 12 samples
  - The Hidden Pattern in Post Codes
  - This Journal Keeps Me Productive (& Maybe You Too)
  - What is Local58?
  - An Experiment With YouTube Comments…
  - Strange Reviews for "Pie" that Doesn't Exist

📦 Cluster 12 — 20 samples
  - Top 20 Disturbing Moments in Kid Films | blameitonjorge
  - How to be a Pirate Captain! 🌈  ☠️ 🌈
  - What Really Happened with u/YAYVIDEOGAMES?
  - The Dark Side of Reddit [3]
  - The Curse of Evil Otto

📦 Cluster 13 — 17 samples
  - Top 5 Biggest Lost Media Finds of 2024 (so far)
  - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge
  - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge
  - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge
  - Looking for Lisa Holst (Re: 10 Misconceptions Rundown)

📦 Cluster 14 — 9 samples
  - 20 Creepypastas Inspired By Real Events
  - u/darylprat, the Reddit Stalker
  - 3 Reddit Posts with Disturbing & Strange Backstories
  - The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge
  - Can Texas Secede from the Union?

📦 Cluster 15 — 25 samples
  - Disturbing Things from Around the Internet [Vol. 1]
  - Majora's Mask and the Art of Dark Symbolism
  - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag
  - Gerrymandering Explained
  - Death to Nickels

📦 Cluster 16 — 16 samples
  - Who Is This Man? | Creepy Videos on the Internet
  - Your New Sidekick (Notepad!)
  - Brief History of the Royal Family
  - The Simple Solution to Traffic
  - The Most Terrifying Sound Heard Around The World | blameitonjorge

📦 Cluster 17 — 18 samples
  - Should all locks have keys? Phones, Castles, Encryption, and You.
  - The Harrowing Disappearance of Kris Kremers & Lisanne Froon
  - The "Where Did This Image Come From?" Iceberg
  - When 43 Students Go Missing...
  - I, Phone

📦 Cluster 18 — 31 samples
  - American Empire
  - Behind the Scenes of TEKOI
  - More Mysterious & Spooky Lost Commercials
  - Disturbing Lost Recordings of Real Events
  - The Mysterious & Lost Locations Iceberg

📦 Cluster 19 — 20 samples
  - Lost Media Bounties
  - Lost Media From Nintendo
  - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge
  - The Fall of Flight 123
  - The Rules for Rulers

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")


# Optional: print titles closest to the cluster centroid
def top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5):
    indices = [i for i, c in enumerate(cluster_ids) if c == cid]
    cluster_embs = emb_tensor[indices]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_k = sims.argsort()[-k:][::-1]
    return [inf_df["video_title"][indices[i]] for i in top_k]

print("\n=== Cluster Summaries (Representative Titles) ===")
for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    if len(cluster) < 2:
        continue
    print(f"\n📦 Cluster {cid} — {len(cluster)} samples")
    reps = top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5)
    for title in reps:
        print(f"  - {title}")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

=== Cluster Summaries (Representative Titles) ===

📦 Cluster 0 — 3 samples
  - Las Vegas isn't Las Vegas
  - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge
  - The Battle of SHARKS!

📦 Cluster 1 — 28 samples
  - Vatican City Explained
  - Top 10 Best Episodes of Goosebumps | blameitonjorge
  - 12 Lost Pieces of Cartoon Network Media | blameitonjorge
  - Gemini and the End of the World
  - The European Union Explained*

📦 Cluster 2 — 31 samples
  - Hi I'm Mary Mary: Explained
  - What If the Electoral College is Tied?
  - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge
  - Unnerving YouTube Channels #2
  - What's Going On with "Dad"?

📦 Cluster 3 — 26 samples
  - The Debt Limit Explained
  - No Flag Northern Ireland
  - Into the Abyss of Haunted PS1
  - The Simple Secret of Runway Numbers
  - A Redditor's Dive Into Turmoil

📦 Cluster 4 — 33 samples
  - What is "This Room Does Not Exist"?
  - Ten Years Later
  - Tea Time Analysis
  - Groundhog Day Explained
  - The True Cost of the Royal Family Explained

📦 Cluster 5 — 13 samples
  - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown)
  - Is Pluto a planet?
  - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge
  - Disturbing Lost Media From Television
  - Disturbing Things from Around the Internet [Vol. 7]

📦 Cluster 6 — 33 samples
  - Why Resident Evil 6 Failed
  - Exploring the Horrors of SOMA
  - Lost Media Found in the Strangest Ways 2
  - 15 Hilariously Awful Wii Games | blameitonjorge
  - History of the Union Jack

📦 Cluster 7 — 13 samples
  - Abstractions: Explained
  - The Race to Win Staten Island
  - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge
  - 🚛 🚗 The Interstate's Forgotten Code 🚗 🚛
  - Daylight Saving Time Explained

📦 Cluster 8 — 10 samples
  - Google Translate’s Strange Responses
  - Gas Stations and Sonic Sound Effects - Why?
  - The Lost Media of Creepypastas
  - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge
  - Lost Media From Nickelodeon 2022

📦 Cluster 9 — 2 samples
  - Inside Colorado's Weed Research Lab
  - Top 20 Unintentionally Disturbing Kids' Characters From Around The World

📦 Cluster 10 — 25 samples
  - Magibon's Online Stalker
  - How Drug Trafficking Destroyed This Popular Video Game
  - How AIs, like ChatGPT, Learn
  - An Empty City is Eerie Magic
  - 8 Animal Misconceptions Rundown

📦 Cluster 11 — 12 samples
  - The Hidden Pattern in Post Codes
  - This Journal Keeps Me Productive (& Maybe You Too)
  - What is Local58?
  - An Experiment With YouTube Comments…
  - Strange Reviews for "Pie" that Doesn't Exist

📦 Cluster 12 — 20 samples
  - Top 20 Disturbing Moments in Kid Films | blameitonjorge
  - How to be a Pirate Captain! 🌈  ☠️ 🌈
  - What Really Happened with u/YAYVIDEOGAMES?
  - The Dark Side of Reddit [3]
  - The Curse of Evil Otto

📦 Cluster 13 — 17 samples
  - Top 5 Biggest Lost Media Finds of 2024 (so far)
  - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge
  - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge
  - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge
  - Looking for Lisa Holst (Re: 10 Misconceptions Rundown)

📦 Cluster 14 — 9 samples
  - 20 Creepypastas Inspired By Real Events
  - u/darylprat, the Reddit Stalker
  - 3 Reddit Posts with Disturbing & Strange Backstories
  - The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge
  - Can Texas Secede from the Union?

📦 Cluster 15 — 25 samples
  - Disturbing Things from Around the Internet [Vol. 1]
  - Majora's Mask and the Art of Dark Symbolism
  - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag
  - Gerrymandering Explained
  - Death to Nickels

📦 Cluster 16 — 16 samples
  - Who Is This Man? | Creepy Videos on the Internet
  - Your New Sidekick (Notepad!)
  - Brief History of the Royal Family
  - The Simple Solution to Traffic
  - The Most Terrifying Sound Heard Around The World | blameitonjorge

📦 Cluster 17 — 18 samples
  - Should all locks have keys? Phones, Castles, Encryption, and You.
  - The Harrowing Disappearance of Kris Kremers & Lisanne Froon
  - The "Where Did This Image Come From?" Iceberg
  - When 43 Students Go Missing...
  - I, Phone

📦 Cluster 18 — 31 samples
  - American Empire
  - Behind the Scenes of TEKOI
  - More Mysterious & Spooky Lost Commercials
  - Disturbing Lost Recordings of Real Events
  - The Mysterious & Lost Locations Iceberg

📦 Cluster 19 — 20 samples
  - Lost Media Bounties
  - Lost Media From Nintendo
  - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge
  - The Fall of Flight 123
  - The Rules for Rulers

In [ ]:
,

''

In [ ]:
print("\n=== Cluster Content Summaries ===")

num_examples_per_cluster = 5  # adjust if needed
sort_by_error = True  # set False to sample randomly

for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    n = len(cluster)
    if n < 2:
        print(f"\nCluster {cid:>2}: Too small ({n} samples)")
        continue

    mean_err = cluster["error"].mean()
    std_err = cluster["error"].std()
    print(f"\n📦 Cluster {cid} — {n} samples")
    print(f"   Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    if sort_by_error:
        rows = cluster.sort("error", descending=True).head(num_examples_per_cluster)
        label = "Top Error Titles"
    else:
        rows = cluster.sample(n=min(num_examples_per_cluster, n))
        label = "Random Titles"

    print(f"   {label}:")
    for r in rows.iter_rows(named=True):
        print(f"     - \"{r['video_title']}\" (err={r['error']:.3f})")


# Optional: print titles closest to the cluster centroid
def top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5):
    indices = [i for i, c in enumerate(cluster_ids) if c == cid]
    cluster_embs = emb_tensor[indices]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_k = sims.argsort()[-k:][::-1]
    return [inf_df["video_title"][indices[i]] for i in top_k]

print("\n=== Cluster Summaries (Representative Titles) ===")
for cid in sorted(set(cluster_ids)):
    cluster = inf_df.filter(pl.col("cluster_id") == cid)
    if len(cluster) < 2:
        continue
    print(f"\n📦 Cluster {cid} — {len(cluster)} samples")
    reps = top_titles_by_centroid(cls_embeddings, cluster_ids, emb_tensor, inf_df, cid, k=5)
    for title in reps:
        print(f"  - {title}")
from torch.nn.functional import cosine_similarity

print("\n=== Cluster Insights ===")

emb_tensor = torch.tensor(cls_embeddings).float()
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
targets = inf_df["target"].to_list()
preds = inf_df["predicted_target"].to_list()

for cid in sorted(set(clusters)):
    cluster_idx = [i for i, c in enumerate(clusters) if c == cid]
    if len(cluster_idx) < 2:
        print(f"\nCluster {cid:>2}: Too few samples ({len(cluster_idx)})")
        continue

    y_true = [targets[i] for i in cluster_idx]
    y_pred = [preds[i] for i in cluster_idx]
    r2 = r2_score(y_true, y_pred)
    mean_err = np.mean([errors[i] for i in cluster_idx])
    std_err = np.std([errors[i] for i in cluster_idx])

    print(f"\n📦 Cluster {cid} — {len(cluster_idx)} samples")
    print(f"   R² = {r2:.4f} | Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")

    # Top-3 most erroneous
    top_err = sorted(cluster_idx, key=lambda i: -errors[i])[:3]
    print("   ❌ Worst Predictions:")
    for i in top_err:
        print(f"     - {titles[i]} (err = {errors[i]:.3f})")

    # Top-3 most accurate
    low_err = sorted(cluster_idx, key=lambda i: errors[i])[:3]
    print("   ✅ Most Accurate Predictions:")
    for i in low_err:
        print(f"     - {titles[i]} (err = {errors[i]:.3f})")

    # Top-3 most representative (closest to cluster centroid)
    cluster_embs = emb_tensor[cluster_idx]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_centroid = np.argsort(sims)[-3:][::-1]
    print("   🎯 Most Representative Titles:")
    for i in top_centroid:
        real_idx = cluster_idx[i]
        print(f"     - {titles[real_idx]} (err = {errors[real_idx]:.3f})")

=== Cluster Content Summaries ===

📦 Cluster 0 — 3 samples
   Mean Abs Error = 0.502 ± 0.165
   Top Error Titles:
     - "10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge" (err=0.692)
     - "Las Vegas isn't Las Vegas" (err=0.410)
     - "The Battle of SHARKS!" (err=0.403)

📦 Cluster 1 — 28 samples
   Mean Abs Error = 0.704 ± 0.409
   Top Error Titles:
     - "9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge" (err=1.825)
     - "Gemini and the End of the World" (err=1.381)
     - "One Year & 100,000 Subscribers Later (Thank You!)" (err=1.352)
     - "7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge" (err=1.219)
     - "Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge" (err=1.068)

📦 Cluster 2 — 31 samples
   Mean Abs Error = 0.238 ± 0.183
   Top Error Titles:
     - "The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge" (err=0.813)
     - "10 Japanese Rituals That Might Scare You To Death" (err=0.560)
     - "A New Theory on KrainaGrzybowTV" (err=0.555)
     - "✈️ The Maddening Mess of Airport Codes! ✈️" (err=0.454)
     - "The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge" (err=0.446)

📦 Cluster 3 — 26 samples
   Mean Abs Error = 0.606 ± 0.593
   Top Error Titles:
     - "Top 20 Saddest Moments In Kid Shows | blameitonjorge" (err=2.226)
     - "Canada & The United States's Bizarre Border" (err=1.771)
     - "20 Creepy YouTube Horror Channels" (err=1.391)
     - "The Simple Secret of Runway Numbers" (err=1.267)
     - "Time Management for Teachers" (err=1.215)

📦 Cluster 4 — 33 samples
   Mean Abs Error = 0.146 ± 0.100
   Top Error Titles:
     - "9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge" (err=0.315)
     - "History Lesson for the History Channel" (err=0.298)
     - "Ten Years Later" (err=0.294)
     - "'Indian' or 'Native American'?  [Reservations, Part 0]" (err=0.281)
     - "Top 10 Best Songs From Kids Shows | blameitonjorge" (err=0.279)

📦 Cluster 5 — 13 samples
   Mean Abs Error = 0.563 ± 0.300
   Top Error Titles:
     - "The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide)" (err=1.269)
     - "Who Owns The Statue of Liberty?" (err=0.934)
     - "Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…)" (err=0.726)
     - "TimmyThick's Strange Disappearance: Solved in Three Minutes or Less" (err=0.656)
     - "Strange Flyers Around Portland, Oregon" (err=0.651)

📦 Cluster 6 — 33 samples
   Mean Abs Error = 0.736 ± 0.395
   Top Error Titles:
     - "Getting Vaccinated at the Coolest Place 😎" (err=1.993)
     - "The Difference between the UK, Great Britain & England Explained" (err=1.499)
     - "Humans Need Not Apply" (err=1.320)
     - "🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags!" (err=1.314)
     - "2.5 Hours of Lost Media Stories" (err=1.150)

📦 Cluster 7 — 13 samples
   Mean Abs Error = 0.637 ± 0.222
   Top Error Titles:
     - "The Race to Win Staten Island" (err=0.985)
     - "The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge" (err=0.843)
     - "Lost Media That Never Existed | blameitonjorge" (err=0.775)
     - "Death to Pennies" (err=0.769)
     - "Exploring the "Ryan" Thread" (err=0.759)

📦 Cluster 8 — 10 samples
   Mean Abs Error = 0.300 ± 0.368
   Top Error Titles:
     - "Summer of Grey: Parts 1 & 3" (err=1.260)
     - "Not The Confederate Flag?" (err=0.533)
     - "Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge" (err=0.300)
     - "10 Worst Character Redesigns In Kids’ Shows | blameitonjorge" (err=0.228)
     - "Google Translate’s Strange Responses" (err=0.210)

📦 Cluster 9 — 2 samples
   Mean Abs Error = 1.558 ± 0.510
   Top Error Titles:
     - "Top 20 Unintentionally Disturbing Kids' Characters From Around The World" (err=1.919)
     - "Inside Colorado's Weed Research Lab" (err=1.197)

📦 Cluster 10 — 25 samples
   Mean Abs Error = 0.852 ± 0.520
   Top Error Titles:
     - "The Theme System Journal" (err=1.989)
     - "An Empty City is Eerie Magic" (err=1.816)
     - "🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️" (err=1.464)
     - "The Lost Media Iceberg | blameitonjorge" (err=1.420)
     - "Why Some Animals Can't be Domesticated" (err=1.378)

📦 Cluster 11 — 12 samples
   Mean Abs Error = 0.788 ± 0.481
   Top Error Titles:
     - "Lost Media Found in 2025 Vol. 1" (err=2.148)
     - "Lost Media Found in 2024" (err=0.976)
     - "7 Ways to Maximize Misery 😞" (err=0.952)
     - "This Journal Keeps Me Productive (& Maybe You Too)" (err=0.909)
     - "7 Eerily Disturbing Old Cartoons & Animations | blameitonjorge" (err=0.812)

📦 Cluster 12 — 20 samples
   Mean Abs Error = 0.556 ± 0.163
   Top Error Titles:
     - "What Really Happened with u/YAYVIDEOGAMES?" (err=0.851)
     - "This Video Will Hurt" (err=0.814)
     - "7 Forgotten & Underrated Halloween Specials | blameitonjorge" (err=0.780)
     - "How Many Countries Are There?" (err=0.714)
     - "8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge" (err=0.701)

📦 Cluster 13 — 17 samples
   Mean Abs Error = 1.229 ± 0.586
   Top Error Titles:
     - "The Dyatlov Pass Incident | PSX Documentaries" (err=2.151)
     - "Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge" (err=2.079)
     - "Dan Schneider: A Scandal at Nickelodeon | blameitonjorge" (err=1.963)
     - "7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge" (err=1.836)
     - "Top 5 Biggest Lost Media Finds of 2024 (so far)" (err=1.661)

📦 Cluster 14 — 9 samples
   Mean Abs Error = 1.063 ± 0.612
   Top Error Titles:
     - "20 Creepypastas Inspired By Real Events" (err=2.159)
     - "The Mandela Effect Analysis" (err=1.812)
     - "The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge" (err=1.374)
     - "u/darylprat, the Reddit Stalker" (err=1.211)
     - "Can Texas Secede from the Union?" (err=0.728)

📦 Cluster 15 — 25 samples
   Mean Abs Error = 0.616 ± 0.345
   Top Error Titles:
     - "2h32 Analysis" (err=1.559)
     - "The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge" (err=1.252)
     - "Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less" (err=1.128)
     - "Death to Nickels" (err=0.949)
     - "What Happened to u/throwaway181718?" (err=0.920)

📦 Cluster 16 — 16 samples
   Mean Abs Error = 1.501 ± 0.444
   Top Error Titles:
     - "The Simple Solution to Traffic" (err=2.236)
     - "The Lost "Uncle Walt" Short Was Almost Found" (err=2.220)
     - "Haunted Morgue Analysis" (err=2.091)
     - "Your World Analysis" (err=1.989)
     - "Kurat 963 Analysis" (err=1.846)

📦 Cluster 17 — 18 samples
   Mean Abs Error = 0.436 ± 0.567
   Top Error Titles:
     - "People Pronouncing Uranus" (err=1.908)
     - "Weekend Wednesday" (err=1.785)
     - "Strange Sounds from 96.7FM" (err=1.030)
     - "11 Episodes of Children's’ Shows Affected by 9/11" (err=0.573)
     - "Someone Dead Ruined My Life… Again." (err=0.511)

📦 Cluster 18 — 31 samples
   Mean Abs Error = 1.099 ± 0.785
   Top Error Titles:
     - "15,000: Thank you." (err=3.362)
     - "NEW: More Designs for Your Sidekick Notepad!" (err=2.477)
     - "The Mysterious Death of Elisa Lam" (err=2.450)
     - "Behind the Scenes of TEKOI" (err=2.225)
     - "How to Become Pope" (err=1.789)

📦 Cluster 19 — 20 samples
   Mean Abs Error = 1.181 ± 0.451
   Top Error Titles:
     - "Top 30 Disturbing Moments in Kids Shows (2018) | blameitonjorge" (err=2.021)
     - "The Better Boarding Method Airlines Won't Use" (err=1.836)
     - "Burden Analysis" (err=1.752)
     - "❄️🇬🇧 London Snow Day 🇬🇧❄️" (err=1.729)
     - "The Cult in a Boarding School" (err=1.542)

=== Cluster Summaries (Representative Titles) ===

📦 Cluster 0 — 3 samples
  - Las Vegas isn't Las Vegas
  - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge
  - The Battle of SHARKS!

📦 Cluster 1 — 28 samples
  - Vatican City Explained
  - Top 10 Best Episodes of Goosebumps | blameitonjorge
  - 12 Lost Pieces of Cartoon Network Media | blameitonjorge
  - Gemini and the End of the World
  - The European Union Explained*

📦 Cluster 2 — 31 samples
  - Hi I'm Mary Mary: Explained
  - What If the Electoral College is Tied?
  - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge
  - Unnerving YouTube Channels #2
  - What's Going On with "Dad"?

📦 Cluster 3 — 26 samples
  - The Debt Limit Explained
  - No Flag Northern Ireland
  - Into the Abyss of Haunted PS1
  - The Simple Secret of Runway Numbers
  - A Redditor's Dive Into Turmoil

📦 Cluster 4 — 33 samples
  - What is "This Room Does Not Exist"?
  - Ten Years Later
  - Tea Time Analysis
  - Groundhog Day Explained
  - The True Cost of the Royal Family Explained

📦 Cluster 5 — 13 samples
  - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown)
  - Is Pluto a planet?
  - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge
  - Disturbing Lost Media From Television
  - Disturbing Things from Around the Internet [Vol. 7]

📦 Cluster 6 — 33 samples
  - Why Resident Evil 6 Failed
  - Exploring the Horrors of SOMA
  - Lost Media Found in the Strangest Ways 2
  - 15 Hilariously Awful Wii Games | blameitonjorge
  - History of the Union Jack

📦 Cluster 7 — 13 samples
  - Abstractions: Explained
  - The Race to Win Staten Island
  - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge
  - 🚛 🚗 The Interstate's Forgotten Code 🚗 🚛
  - Daylight Saving Time Explained

📦 Cluster 8 — 10 samples
  - Google Translate’s Strange Responses
  - Gas Stations and Sonic Sound Effects - Why?
  - The Lost Media of Creepypastas
  - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge
  - Lost Media From Nickelodeon 2022

📦 Cluster 9 — 2 samples
  - Inside Colorado's Weed Research Lab
  - Top 20 Unintentionally Disturbing Kids' Characters From Around The World

📦 Cluster 10 — 25 samples
  - Magibon's Online Stalker
  - How Drug Trafficking Destroyed This Popular Video Game
  - How AIs, like ChatGPT, Learn
  - An Empty City is Eerie Magic
  - 8 Animal Misconceptions Rundown

📦 Cluster 11 — 12 samples
  - The Hidden Pattern in Post Codes
  - This Journal Keeps Me Productive (& Maybe You Too)
  - What is Local58?
  - An Experiment With YouTube Comments…
  - Strange Reviews for "Pie" that Doesn't Exist

📦 Cluster 12 — 20 samples
  - Top 20 Disturbing Moments in Kid Films | blameitonjorge
  - How to be a Pirate Captain! 🌈  ☠️ 🌈
  - What Really Happened with u/YAYVIDEOGAMES?
  - The Dark Side of Reddit [3]
  - The Curse of Evil Otto

📦 Cluster 13 — 17 samples
  - Top 5 Biggest Lost Media Finds of 2024 (so far)
  - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge
  - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge
  - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge
  - Looking for Lisa Holst (Re: 10 Misconceptions Rundown)

📦 Cluster 14 — 9 samples
  - 20 Creepypastas Inspired By Real Events
  - u/darylprat, the Reddit Stalker
  - 3 Reddit Posts with Disturbing & Strange Backstories
  - The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge
  - Can Texas Secede from the Union?

📦 Cluster 15 — 25 samples
  - Disturbing Things from Around the Internet [Vol. 1]
  - Majora's Mask and the Art of Dark Symbolism
  - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag
  - Gerrymandering Explained
  - Death to Nickels

📦 Cluster 16 — 16 samples
  - Who Is This Man? | Creepy Videos on the Internet
  - Your New Sidekick (Notepad!)
  - Brief History of the Royal Family
  - The Simple Solution to Traffic
  - The Most Terrifying Sound Heard Around The World | blameitonjorge

📦 Cluster 17 — 18 samples
  - Should all locks have keys? Phones, Castles, Encryption, and You.
  - The Harrowing Disappearance of Kris Kremers & Lisanne Froon
  - The "Where Did This Image Come From?" Iceberg
  - When 43 Students Go Missing...
  - I, Phone

📦 Cluster 18 — 31 samples
  - American Empire
  - Behind the Scenes of TEKOI
  - More Mysterious & Spooky Lost Commercials
  - Disturbing Lost Recordings of Real Events
  - The Mysterious & Lost Locations Iceberg

📦 Cluster 19 — 20 samples
  - Lost Media Bounties
  - Lost Media From Nintendo
  - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge
  - The Fall of Flight 123
  - The Rules for Rulers

=== Cluster Insights ===

📦 Cluster 0 — 3 samples
   R² = -0.9347 | Mean Abs Error = 0.502 ± 0.134
   ❌ Worst Predictions:
     - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge (err = 0.692)
     - Las Vegas isn't Las Vegas (err = 0.410)
     - The Battle of SHARKS! (err = 0.403)
   ✅ Most Accurate Predictions:
     - The Battle of SHARKS! (err = 0.403)
     - Las Vegas isn't Las Vegas (err = 0.410)
     - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge (err = 0.692)
   🎯 Most Representative Titles:
     - Las Vegas isn't Las Vegas (err = 0.410)
     - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge (err = 0.692)
     - The Battle of SHARKS! (err = 0.403)

📦 Cluster 1 — 28 samples
   R² = 0.3052 | Mean Abs Error = 0.704 ± 0.401
   ❌ Worst Predictions:
     - 9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge (err = 1.825)
     - Gemini and the End of the World (err = 1.381)
     - One Year & 100,000 Subscribers Later (Thank You!) (err = 1.352)
   ✅ Most Accurate Predictions:
     - Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027)
     - The Darkest Lost Media [Vol. 3] (err = 0.099)
     - 40 MORE Lost or Banned Episodes of Kids Shows (err = 0.305)
   🎯 Most Representative Titles:
     - Vatican City Explained (err = 0.983)
     - Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027)
     - 12 Lost Pieces of Cartoon Network Media | blameitonjorge (err = 0.866)

📦 Cluster 2 — 31 samples
   R² = 0.4503 | Mean Abs Error = 0.238 ± 0.180
   ❌ Worst Predictions:
     - The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge (err = 0.813)
     - 10 Japanese Rituals That Might Scare You To Death (err = 0.560)
     - A New Theory on KrainaGrzybowTV (err = 0.555)
   ✅ Most Accurate Predictions:
     - Patrice Wilson Live Stream: Explained (err = 0.016)
     - 15 Lost Disney Cartoons, Episodes, & Shorts That We May Never See Again | blameitonjorge (err = 0.023)
     - What's Going On with "Dad"? (err = 0.040)
   🎯 Most Representative Titles:
     - Hi I'm Mary Mary: Explained (err = 0.239)
     - What If the Electoral College is Tied? (err = 0.195)
     - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)

📦 Cluster 3 — 26 samples
   R² = 0.2451 | Mean Abs Error = 0.606 ± 0.581
   ❌ Worst Predictions:
     - Top 20 Saddest Moments In Kid Shows | blameitonjorge (err = 2.226)
     - Canada & The United States's Bizarre Border (err = 1.771)
     - 20 Creepy YouTube Horror Channels (err = 1.391)
   ✅ Most Accurate Predictions:
     - No Flag Northern Ireland (err = 0.023)
     - 💖 The History of The Tiffany 💖 (err = 0.032)
     - Road Trip After Eight Years Without Driving (err = 0.043)
   🎯 Most Representative Titles:
     - The Debt Limit Explained (err = 0.270)
     - No Flag Northern Ireland (err = 0.023)
     - Into the Abyss of Haunted PS1 (err = 0.274)

📦 Cluster 4 — 33 samples
   R² = 0.8048 | Mean Abs Error = 0.146 ± 0.099
   ❌ Worst Predictions:
     - 9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge (err = 0.315)
     - History Lesson for the History Channel (err = 0.298)
     - Ten Years Later (err = 0.294)
   ✅ Most Accurate Predictions:
     - Tea Time Analysis (err = 0.007)
     - Investigating the "Magic World of Ania” (err = 0.008)
     - "My Sister" Analysis (err = 0.009)
   🎯 Most Representative Titles:
     - What is "This Room Does Not Exist"? (err = 0.146)
     - Ten Years Later (err = 0.294)
     - Tea Time Analysis (err = 0.007)

📦 Cluster 5 — 13 samples
   R² = 0.0998 | Mean Abs Error = 0.563 ± 0.288
   ❌ Worst Predictions:
     - The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide) (err = 1.269)
     - Who Owns The Statue of Liberty? (err = 0.934)
     - Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…) (err = 0.726)
   ✅ Most Accurate Predictions:
     - Is Pluto a planet? (err = 0.152)
     - Lost Media Found in the Strangest Ways | blameitonjorge (err = 0.310)
     - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown) (err = 0.332)
   🎯 Most Representative Titles:
     - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown) (err = 0.332)
     - Is Pluto a planet? (err = 0.152)
     - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge (err = 0.338)

📦 Cluster 6 — 33 samples
   R² = 0.1728 | Mean Abs Error = 0.736 ± 0.389
   ❌ Worst Predictions:
     - Getting Vaccinated at the Coolest Place 😎 (err = 1.993)
     - The Difference between the UK, Great Britain & England Explained (err = 1.499)
     - Humans Need Not Apply (err = 1.320)
   ✅ Most Accurate Predictions:
     - How the Electoral College Works (err = 0.176)
     - Who Owns Antarctica? (err = 0.228)
     - Exploring the Horrors of SOMA (err = 0.339)
   🎯 Most Representative Titles:
     - Why Resident Evil 6 Failed (err = 0.456)
     - Exploring the Horrors of SOMA (err = 0.339)
     - Lost Media Found in the Strangest Ways 2 (err = 0.803)

📦 Cluster 7 — 13 samples
   R² = -0.1259 | Mean Abs Error = 0.637 ± 0.213
   ❌ Worst Predictions:
     - The Race to Win Staten Island (err = 0.985)
     - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge (err = 0.843)
     - Lost Media That Never Existed | blameitonjorge (err = 0.775)
   ✅ Most Accurate Predictions:
     - The Legacy of Spongebob Squarepants ... And How Nickelodeon Is Squeezing It Dry | blameitonjorge (err = 0.177)
     - Disturbing Things from Around the Internet [Vol. 14] (err = 0.341)
     - Investigating Mysterious Encounters from Randonautica (err = 0.420)
   🎯 Most Representative Titles:
     - Abstractions: Explained (err = 0.608)
     - The Race to Win Staten Island (err = 0.985)
     - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge (err = 0.843)

📦 Cluster 8 — 10 samples
   R² = 0.4607 | Mean Abs Error = 0.300 ± 0.349
   ❌ Worst Predictions:
     - Summer of Grey: Parts 1 & 3 (err = 1.260)
     - Not The Confederate Flag? (err = 0.533)
     - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge (err = 0.300)
   ✅ Most Accurate Predictions:
     - How Sesame Street's Banned 847 Episode Was Found | The Lost Wicked Witch Segment (err = 0.039)
     - Gas Stations and Sonic Sound Effects - Why? (err = 0.059)
     - A Bizarre Lost Kids Show - The Search For Pink Morning Cartoon | blameitonjorge (err = 0.072)
   🎯 Most Representative Titles:
     - Google Translate’s Strange Responses (err = 0.210)
     - Gas Stations and Sonic Sound Effects - Why? (err = 0.059)
     - The Lost Media of Creepypastas (err = 0.204)

📦 Cluster 9 — 2 samples
   R² = -0.1294 | Mean Abs Error = 1.558 ± 0.361
   ❌ Worst Predictions:
     - Top 20 Unintentionally Disturbing Kids' Characters From Around The World (err = 1.919)
     - Inside Colorado's Weed Research Lab (err = 1.197)
   ✅ Most Accurate Predictions:
     - Inside Colorado's Weed Research Lab (err = 1.197)
     - Top 20 Unintentionally Disturbing Kids' Characters From Around The World (err = 1.919)
   🎯 Most Representative Titles:
     - Inside Colorado's Weed Research Lab (err = 1.197)
     - Top 20 Unintentionally Disturbing Kids' Characters From Around The World (err = 1.919)

📦 Cluster 10 — 25 samples
   R² = 0.1766 | Mean Abs Error = 0.852 ± 0.510
   ❌ Worst Predictions:
     - The Theme System Journal (err = 1.989)
     - An Empty City is Eerie Magic (err = 1.816)

In [ ]:
from torch.nn.functional import cosine_similarity
from sklearn.metrics import r2_score

print("\n=== Cluster Summary by Centroid ===")

emb_tensor = torch.tensor(cls_embeddings).float()
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
targets = inf_df["target"].to_list()
preds = inf_df["predicted_target"].to_list()

num_titles = 5  # number of representative titles to show

for cid in sorted(set(clusters)):
    cluster_idx = [i for i, c in enumerate(clusters) if c == cid]
    if len(cluster_idx) < 2:
        print(f"\nCluster {cid:>2}: Too few samples ({len(cluster_idx)})")
        continue

    # Compute R² and mean error
    y_true = [targets[i] for i in cluster_idx]
    y_pred = [preds[i] for i in cluster_idx]
    try:
        r2 = r2_score(y_true, y_pred)
    except Exception:
        r2 = float("nan")
    mean_err = np.mean([errors[i] for i in cluster_idx])
    std_err = np.std([errors[i] for i in cluster_idx])

    # Compute centroid-based similarity
    cluster_embs = emb_tensor[cluster_idx]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_idxs = np.argsort(sims)[-num_titles:][::-1]

    print(f"\n📦 Cluster {cid} — {len(cluster_idx)} samples")
    print(f"   R² = {r2:.4f} | Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")
    print(f"   🎯 Most Representative Titles:")
    for i in top_idxs:
        real_idx = cluster_idx[i]
        print(f"     - {titles[real_idx]} (err = {errors[real_idx]:.3f})")

=== Cluster Summary by Centroid ===

📦 Cluster 0 — 3 samples
   R² = -0.9347 | Mean Abs Error = 0.502 ± 0.134
   🎯 Most Representative Titles:
     - Las Vegas isn't Las Vegas (err = 0.410)
     - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge (err = 0.692)
     - The Battle of SHARKS! (err = 0.403)

📦 Cluster 1 — 28 samples
   R² = 0.3052 | Mean Abs Error = 0.704 ± 0.401
   🎯 Most Representative Titles:
     - Vatican City Explained (err = 0.983)
     - Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027)
     - 12 Lost Pieces of Cartoon Network Media | blameitonjorge (err = 0.866)
     - Gemini and the End of the World (err = 1.381)
     - The European Union Explained* (err = 1.023)

📦 Cluster 2 — 31 samples
   R² = 0.4503 | Mean Abs Error = 0.238 ± 0.180
   🎯 Most Representative Titles:
     - Hi I'm Mary Mary: Explained (err = 0.239)
     - What If the Electoral College is Tied? (err = 0.195)
     - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)
     - Unnerving YouTube Channels #2 (err = 0.189)
     - What's Going On with "Dad"? (err = 0.040)

📦 Cluster 3 — 26 samples
   R² = 0.2451 | Mean Abs Error = 0.606 ± 0.581
   🎯 Most Representative Titles:
     - The Debt Limit Explained (err = 0.270)
     - No Flag Northern Ireland (err = 0.023)
     - Into the Abyss of Haunted PS1 (err = 0.274)
     - The Simple Secret of Runway Numbers (err = 1.267)
     - A Redditor's Dive Into Turmoil (err = 0.289)

📦 Cluster 4 — 33 samples
   R² = 0.8048 | Mean Abs Error = 0.146 ± 0.099
   🎯 Most Representative Titles:
     - What is "This Room Does Not Exist"? (err = 0.146)
     - Ten Years Later (err = 0.294)
     - Tea Time Analysis (err = 0.007)
     - Groundhog Day Explained (err = 0.208)
     - The True Cost of the Royal Family Explained (err = 0.011)

📦 Cluster 5 — 13 samples
   R² = 0.0998 | Mean Abs Error = 0.563 ± 0.288
   🎯 Most Representative Titles:
     - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown) (err = 0.332)
     - Is Pluto a planet? (err = 0.152)
     - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge (err = 0.338)
     - Disturbing Lost Media From Television (err = 0.640)
     - Disturbing Things from Around the Internet [Vol. 7] (err = 0.383)

📦 Cluster 6 — 33 samples
   R² = 0.1728 | Mean Abs Error = 0.736 ± 0.389
   🎯 Most Representative Titles:
     - Why Resident Evil 6 Failed (err = 0.456)
     - Exploring the Horrors of SOMA (err = 0.339)
     - Lost Media Found in the Strangest Ways 2 (err = 0.803)
     - 15 Hilariously Awful Wii Games | blameitonjorge (err = 0.757)
     - History of the Union Jack (err = 0.596)

📦 Cluster 7 — 13 samples
   R² = -0.1259 | Mean Abs Error = 0.637 ± 0.213
   🎯 Most Representative Titles:
     - Abstractions: Explained (err = 0.608)
     - The Race to Win Staten Island (err = 0.985)
     - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge (err = 0.843)
     - 🚛 🚗 The Interstate's Forgotten Code 🚗 🚛 (err = 0.532)
     - Daylight Saving Time Explained (err = 0.626)

📦 Cluster 8 — 10 samples
   R² = 0.4607 | Mean Abs Error = 0.300 ± 0.349
   🎯 Most Representative Titles:
     - Google Translate’s Strange Responses (err = 0.210)
     - Gas Stations and Sonic Sound Effects - Why? (err = 0.059)
     - The Lost Media of Creepypastas (err = 0.204)
     - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge (err = 0.300)
     - Lost Media From Nickelodeon 2022 (err = 0.091)

📦 Cluster 9 — 2 samples
   R² = -0.1294 | Mean Abs Error = 1.558 ± 0.361
   🎯 Most Representative Titles:
     - Inside Colorado's Weed Research Lab (err = 1.197)
     - Top 20 Unintentionally Disturbing Kids' Characters From Around The World (err = 1.919)

📦 Cluster 10 — 25 samples
   R² = 0.1766 | Mean Abs Error = 0.852 ± 0.510
   🎯 Most Representative Titles:
     - Magibon's Online Stalker (err = 0.070)
     - How Drug Trafficking Destroyed This Popular Video Game (err = 0.796)
     - How AIs, like ChatGPT, Learn (err = 0.967)
     - An Empty City is Eerie Magic (err = 1.816)
     - 8 Animal Misconceptions Rundown (err = 0.401)

📦 Cluster 11 — 12 samples
   R² = -0.0311 | Mean Abs Error = 0.788 ± 0.461
   🎯 Most Representative Titles:
     - The Hidden Pattern in Post Codes (err = 0.762)
     - This Journal Keeps Me Productive (& Maybe You Too) (err = 0.909)
     - What is Local58? (err = 0.539)
     - An Experiment With YouTube Comments… (err = 0.353)
     - Strange Reviews for "Pie" that Doesn't Exist (err = 0.341)

📦 Cluster 12 — 20 samples
   R² = 0.1447 | Mean Abs Error = 0.556 ± 0.159
   🎯 Most Representative Titles:
     - Top 20 Disturbing Moments in Kid Films | blameitonjorge (err = 0.640)
     - How to be a Pirate Captain! 🌈  ☠️ 🌈 (err = 0.522)
     - What Really Happened with u/YAYVIDEOGAMES? (err = 0.851)
     - The Dark Side of Reddit [3] (err = 0.578)
     - The Curse of Evil Otto (err = 0.334)

📦 Cluster 13 — 17 samples
   R² = 0.1373 | Mean Abs Error = 1.229 ± 0.569
   🎯 Most Representative Titles:
     - Top 5 Biggest Lost Media Finds of 2024 (so far) (err = 1.661)
     - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge (err = 1.392)
     - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge (err = 1.836)
     - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge (err = 2.079)
     - Looking for Lisa Holst (Re: 10 Misconceptions Rundown) (err = 1.051)

📦 Cluster 14 — 9 samples
   R² = -0.0012 | Mean Abs Error = 1.063 ± 0.577
   🎯 Most Representative Titles:
     - 20 Creepypastas Inspired By Real Events (err = 2.159)
     - u/darylprat, the Reddit Stalker (err = 1.211)
     - 3 Reddit Posts with Disturbing & Strange Backstories (err = 0.506)
     - The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge (err = 1.374)
     - Can Texas Secede from the Union? (err = 0.728)

📦 Cluster 15 — 25 samples
   R² = 0.2946 | Mean Abs Error = 0.616 ± 0.338
   🎯 Most Representative Titles:
     - Disturbing Things from Around the Internet [Vol. 1] (err = 0.467)
     - Majora's Mask and the Art of Dark Symbolism (err = 0.548)
     - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag (err = 0.220)
     - Gerrymandering Explained (err = 0.052)
     - Death to Nickels (err = 0.949)

📦 Cluster 16 — 16 samples
   R² = 0.0636 | Mean Abs Error = 1.501 ± 0.430
   🎯 Most Representative Titles:
     - Who Is This Man? | Creepy Videos on the Internet (err = 0.906)
     - Your New Sidekick (Notepad!) (err = 1.205)
     - Brief History of the Royal Family (err = 1.431)
     - The Simple Solution to Traffic (err = 2.236)
     - The Most Terrifying Sound Heard Around The World | blameitonjorge (err = 1.161)

📦 Cluster 17 — 18 samples
   R² = -0.0801 | Mean Abs Error = 0.436 ± 0.551
   🎯 Most Representative Titles:
     - Should all locks have keys? Phones, Castles, Encryption, and You. (err = 0.176)
     - The Harrowing Disappearance of Kris Kremers & Lisanne Froon (err = 0.211)
     - The "Where Did This Image Come From?" Iceberg (err = 0.001)
     - When 43 Students Go Missing... (err = 0.125)
     - I, Phone (err = 0.214)

📦 Cluster 18 — 31 samples
   R² = 0.0857 | Mean Abs Error = 1.099 ± 0.772
   🎯 Most Representative Titles:
     - American Empire (err = 1.022)
     - Behind the Scenes of TEKOI (err = 2.225)
     - More Mysterious & Spooky Lost Commercials (err = 1.640)
     - Disturbing Lost Recordings of Real Events (err = 0.140)
     - The Mysterious & Lost Locations Iceberg (err = 0.962)

📦 Cluster 19 — 20 samples
   R² = 0.0849 | Mean Abs Error = 1.181 ± 0.439
   🎯 Most Representative Titles:
     - Lost Media Bounties (err = 0.778)
     - Lost Media From Nintendo (err = 0.916)
     - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge (err = 1.236)
     - The Fall of Flight 123 (err = 0.469)
     - The Rules for Rulers (err = 1.470)

In [ ]:
from torch.nn.functional import cosine_similarity
from sklearn.metrics import r2_score
import numpy as np

print("\n=== Cluster Summary by Centroid (Sorted by R²) ===")

emb_tensor = torch.tensor(cls_embeddings).float()
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
targets = inf_df["target"].to_list()
preds = inf_df["predicted_target"].to_list()

num_titles = 5  # number of representative titles to print
cluster_stats = []

# Step 1: Precompute R² and summary stats for all clusters
for cid in sorted(set(clusters)):
    cluster_idx = [i for i, c in enumerate(clusters) if c == cid]
    if len(cluster_idx) < 2:
        continue

    y_true = [targets[i] for i in cluster_idx]
    y_pred = [preds[i] for i in cluster_idx]
    try:
        r2 = r2_score(y_true, y_pred)
    except Exception:
        r2 = float("nan")

    mean_err = np.mean([errors[i] for i in cluster_idx])
    std_err = np.std([errors[i] for i in cluster_idx])

    cluster_stats.append({
        "cid": cid,
        "r2": r2,
        "mean_err": mean_err,
        "std_err": std_err,
        "indices": cluster_idx
    })

# Step 2: Sort clusters by R² descending
cluster_stats = sorted(cluster_stats, key=lambda x: x["r2"], reverse=True)

# Step 3: Print results
for entry in cluster_stats:
    cid = entry["cid"]
    r2 = entry["r2"]
    mean_err = entry["mean_err"]
    std_err = entry["std_err"]
    cluster_idx = entry["indices"]

    # Find representative titles via centroid similarity
    cluster_embs = emb_tensor[cluster_idx]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    top_idxs = np.argsort(sims)[-num_titles:][::-1]

    print(f"\n📦 Cluster {cid} — {len(cluster_idx)} samples")
    print(f"   R² = {r2:.4f} | Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")
    print(f"   🎯 Most Representative Titles:")
    for i in top_idxs:
        real_idx = cluster_idx[i]
        print(f"     - {titles[real_idx]} (err = {errors[real_idx]:.3f})")

=== Cluster Summary by Centroid (Sorted by R²) ===

📦 Cluster 4 — 33 samples
   R² = 0.8048 | Mean Abs Error = 0.146 ± 0.099
   🎯 Most Representative Titles:
     - What is "This Room Does Not Exist"? (err = 0.146)
     - Ten Years Later (err = 0.294)
     - Tea Time Analysis (err = 0.007)
     - Groundhog Day Explained (err = 0.208)
     - The True Cost of the Royal Family Explained (err = 0.011)

📦 Cluster 8 — 10 samples
   R² = 0.4607 | Mean Abs Error = 0.300 ± 0.349
   🎯 Most Representative Titles:
     - Google Translate’s Strange Responses (err = 0.210)
     - Gas Stations and Sonic Sound Effects - Why? (err = 0.059)
     - The Lost Media of Creepypastas (err = 0.204)
     - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge (err = 0.300)
     - Lost Media From Nickelodeon 2022 (err = 0.091)

📦 Cluster 2 — 31 samples
   R² = 0.4503 | Mean Abs Error = 0.238 ± 0.180
   🎯 Most Representative Titles:
     - Hi I'm Mary Mary: Explained (err = 0.239)
     - What If the Electoral College is Tied? (err = 0.195)
     - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)
     - Unnerving YouTube Channels #2 (err = 0.189)
     - What's Going On with "Dad"? (err = 0.040)

📦 Cluster 1 — 28 samples
   R² = 0.3052 | Mean Abs Error = 0.704 ± 0.401
   🎯 Most Representative Titles:
     - Vatican City Explained (err = 0.983)
     - Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027)
     - 12 Lost Pieces of Cartoon Network Media | blameitonjorge (err = 0.866)
     - Gemini and the End of the World (err = 1.381)
     - The European Union Explained* (err = 1.023)

📦 Cluster 15 — 25 samples
   R² = 0.2946 | Mean Abs Error = 0.616 ± 0.338
   🎯 Most Representative Titles:
     - Disturbing Things from Around the Internet [Vol. 1] (err = 0.467)
     - Majora's Mask and the Art of Dark Symbolism (err = 0.548)
     - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag (err = 0.220)
     - Gerrymandering Explained (err = 0.052)
     - Death to Nickels (err = 0.949)

📦 Cluster 3 — 26 samples
   R² = 0.2451 | Mean Abs Error = 0.606 ± 0.581
   🎯 Most Representative Titles:
     - The Debt Limit Explained (err = 0.270)
     - No Flag Northern Ireland (err = 0.023)
     - Into the Abyss of Haunted PS1 (err = 0.274)
     - The Simple Secret of Runway Numbers (err = 1.267)
     - A Redditor's Dive Into Turmoil (err = 0.289)

📦 Cluster 10 — 25 samples
   R² = 0.1766 | Mean Abs Error = 0.852 ± 0.510
   🎯 Most Representative Titles:
     - Magibon's Online Stalker (err = 0.070)
     - How Drug Trafficking Destroyed This Popular Video Game (err = 0.796)
     - How AIs, like ChatGPT, Learn (err = 0.967)
     - An Empty City is Eerie Magic (err = 1.816)
     - 8 Animal Misconceptions Rundown (err = 0.401)

📦 Cluster 6 — 33 samples
   R² = 0.1728 | Mean Abs Error = 0.736 ± 0.389
   🎯 Most Representative Titles:
     - Why Resident Evil 6 Failed (err = 0.456)
     - Exploring the Horrors of SOMA (err = 0.339)
     - Lost Media Found in the Strangest Ways 2 (err = 0.803)
     - 15 Hilariously Awful Wii Games | blameitonjorge (err = 0.757)
     - History of the Union Jack (err = 0.596)

📦 Cluster 12 — 20 samples
   R² = 0.1447 | Mean Abs Error = 0.556 ± 0.159
   🎯 Most Representative Titles:
     - Top 20 Disturbing Moments in Kid Films | blameitonjorge (err = 0.640)
     - How to be a Pirate Captain! 🌈  ☠️ 🌈 (err = 0.522)
     - What Really Happened with u/YAYVIDEOGAMES? (err = 0.851)
     - The Dark Side of Reddit [3] (err = 0.578)
     - The Curse of Evil Otto (err = 0.334)

📦 Cluster 13 — 17 samples
   R² = 0.1373 | Mean Abs Error = 1.229 ± 0.569
   🎯 Most Representative Titles:
     - Top 5 Biggest Lost Media Finds of 2024 (so far) (err = 1.661)
     - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge (err = 1.392)
     - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge (err = 1.836)
     - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge (err = 2.079)
     - Looking for Lisa Holst (Re: 10 Misconceptions Rundown) (err = 1.051)

📦 Cluster 5 — 13 samples
   R² = 0.0998 | Mean Abs Error = 0.563 ± 0.288
   🎯 Most Representative Titles:
     - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown) (err = 0.332)
     - Is Pluto a planet? (err = 0.152)
     - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge (err = 0.338)
     - Disturbing Lost Media From Television (err = 0.640)
     - Disturbing Things from Around the Internet [Vol. 7] (err = 0.383)

📦 Cluster 18 — 31 samples
   R² = 0.0857 | Mean Abs Error = 1.099 ± 0.772
   🎯 Most Representative Titles:
     - American Empire (err = 1.022)
     - Behind the Scenes of TEKOI (err = 2.225)
     - More Mysterious & Spooky Lost Commercials (err = 1.640)
     - Disturbing Lost Recordings of Real Events (err = 0.140)
     - The Mysterious & Lost Locations Iceberg (err = 0.962)

📦 Cluster 19 — 20 samples
   R² = 0.0849 | Mean Abs Error = 1.181 ± 0.439
   🎯 Most Representative Titles:
     - Lost Media Bounties (err = 0.778)
     - Lost Media From Nintendo (err = 0.916)
     - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge (err = 1.236)
     - The Fall of Flight 123 (err = 0.469)
     - The Rules for Rulers (err = 1.470)

📦 Cluster 16 — 16 samples
   R² = 0.0636 | Mean Abs Error = 1.501 ± 0.430
   🎯 Most Representative Titles:
     - Who Is This Man? | Creepy Videos on the Internet (err = 0.906)
     - Your New Sidekick (Notepad!) (err = 1.205)
     - Brief History of the Royal Family (err = 1.431)
     - The Simple Solution to Traffic (err = 2.236)
     - The Most Terrifying Sound Heard Around The World | blameitonjorge (err = 1.161)

📦 Cluster 14 — 9 samples
   R² = -0.0012 | Mean Abs Error = 1.063 ± 0.577
   🎯 Most Representative Titles:
     - 20 Creepypastas Inspired By Real Events (err = 2.159)
     - u/darylprat, the Reddit Stalker (err = 1.211)
     - 3 Reddit Posts with Disturbing & Strange Backstories (err = 0.506)
     - The Search For Clockman: Nickelodeon's Mysterious Lost Short | blameitonjorge (err = 1.374)
     - Can Texas Secede from the Union? (err = 0.728)

📦 Cluster 11 — 12 samples
   R² = -0.0311 | Mean Abs Error = 0.788 ± 0.461
   🎯 Most Representative Titles:
     - The Hidden Pattern in Post Codes (err = 0.762)
     - This Journal Keeps Me Productive (& Maybe You Too) (err = 0.909)
     - What is Local58? (err = 0.539)
     - An Experiment With YouTube Comments… (err = 0.353)
     - Strange Reviews for "Pie" that Doesn't Exist (err = 0.341)

📦 Cluster 17 — 18 samples
   R² = -0.0801 | Mean Abs Error = 0.436 ± 0.551
   🎯 Most Representative Titles:
     - Should all locks have keys? Phones, Castles, Encryption, and You. (err = 0.176)
     - The Harrowing Disappearance of Kris Kremers & Lisanne Froon (err = 0.211)
     - The "Where Did This Image Come From?" Iceberg (err = 0.001)
     - When 43 Students Go Missing... (err = 0.125)
     - I, Phone (err = 0.214)

📦 Cluster 7 — 13 samples
   R² = -0.1259 | Mean Abs Error = 0.637 ± 0.213
   🎯 Most Representative Titles:
     - Abstractions: Explained (err = 0.608)
     - The Race to Win Staten Island (err = 0.985)
     - The Suspicious Death and Cover-Up of Colin Madsen | blameitonjorge (err = 0.843)
     - 🚛 🚗 The Interstate's Forgotten Code 🚗 🚛 (err = 0.532)
     - Daylight Saving Time Explained (err = 0.626)

📦 Cluster 9 — 2 samples
   R² = -0.1294 | Mean Abs Error = 1.558 ± 0.361
   🎯 Most Representative Titles:
     - Inside Colorado's Weed Research Lab (err = 1.197)
     - Top 20 Unintentionally Disturbing Kids' Characters From Around The World (err = 1.919)

📦 Cluster 0 — 3 samples
   R² = -0.9347 | Mean Abs Error = 0.502 ± 0.134
   🎯 Most Representative Titles:
     - Las Vegas isn't Las Vegas (err = 0.410)
     - 10 Most WTF Characters in Courage the Cowardly Dog | blameitonjorge (err = 0.692)
     - The Battle of SHARKS! (err = 0.403)

In [ ]:
from torch.nn.functional import cosine_similarity
from sklearn.metrics import r2_score
import numpy as np

print("\n=== Cluster Summary by Centroid (Sorted by R², All Titles) ===")

emb_tensor = torch.tensor(cls_embeddings).float()
titles = inf_df["video_title"].to_list()
errors = inf_df["error"].to_list()
clusters = inf_df["cluster_id"].to_list()
targets = inf_df["target"].to_list()
preds = inf_df["predicted_target"].to_list()

cluster_stats = []

# Step 1: Compute cluster metrics
for cid in sorted(set(clusters)):
    cluster_idx = [i for i, c in enumerate(clusters) if c == cid]
    if len(cluster_idx) < 2:
        continue

    y_true = [targets[i] for i in cluster_idx]
    y_pred = [preds[i] for i in cluster_idx]
    try:
        r2 = r2_score(y_true, y_pred)
    except Exception:
        r2 = float("nan")

    mean_err = np.mean([errors[i] for i in cluster_idx])
    std_err = np.std([errors[i] for i in cluster_idx])

    cluster_stats.append({
        "cid": cid,
        "r2": r2,
        "mean_err": mean_err,
        "std_err": std_err,
        "indices": cluster_idx
    })

# Step 2: Sort clusters by R²
cluster_stats = sorted(cluster_stats, key=lambda x: x["r2"], reverse=True)

# Step 3: Print all titles in each cluster (sorted by proximity to centroid)
for entry in cluster_stats:
    cid = entry["cid"]
    r2 = entry["r2"]
    mean_err = entry["mean_err"]
    std_err = entry["std_err"]
    cluster_idx = entry["indices"]

    cluster_embs = emb_tensor[cluster_idx]
    centroid = cluster_embs.mean(dim=0, keepdim=True)
    sims = cosine_similarity(centroid, cluster_embs).squeeze().cpu().numpy()
    sorted_by_similarity = np.argsort(sims)[::-1]  # highest similarity first

    print(f"\n📦 Cluster {cid} — {len(cluster_idx)} samples")
    print(f"   R² = {r2:.4f} | Mean Abs Error = {mean_err:.3f} ± {std_err:.3f}")
    print(f"   🎯 Titles (most representative first):")
    for i in sorted_by_similarity:
        real_idx = cluster_idx[i]
        print(f"     - {titles[real_idx]} (err = {errors[real_idx]:.3f})")

=== Cluster Summary by Centroid (Sorted by R², All Titles) ===

📦 Cluster 4 — 33 samples
   R² = 0.8048 | Mean Abs Error = 0.146 ± 0.099
   🎯 Titles (most representative first):
     - What is "This Room Does Not Exist"? (err = 0.146)
     - Ten Years Later (err = 0.294)
     - Tea Time Analysis (err = 0.007)
     - Groundhog Day Explained (err = 0.208)
     - The True Cost of the Royal Family Explained (err = 0.011)
     - Canada Gets Rid of the Penny (Huzzah!) (err = 0.238)
     - Disturbing Things from Around the Internet [Vol. 2] (err = 0.216)
     - 2020 Vision: The YouTube Channel Predicting Death (err = 0.079)
     - Ben Drowns Again (err = 0.135)
     - The Trouble with Transporters (err = 0.251)
     - 'Indian' or 'Native American'?  [Reservations, Part 0] (err = 0.281)
     - Unnerving YouTube Channels #1 (err = 0.047)
     - The Search For A Day With Spongebob Squarepants: The Complete History | blameitonjorge (err = 0.210)
     - Where is Scandinavia? (err = 0.223)
     - Exploring the "StrayedAway" Voicemail Thread (err = 0.060)
     - "My Sister" Analysis (err = 0.009)
     - Exploring KrainaGrzybowTV (err = 0.144)
     - YouTube vs Grey: A Ballad of Accidental Suspension (err = 0.064)
     - Quick and Easy Voting for Normal People (err = 0.055)
     - The Lost Media Gameshow Iceberg | blameitonjorge (err = 0.123)
     - What is a Leap Year? (err = 0.057)
     - PETSCOP: A Virtual Void of Misery (err = 0.157)
     - Oakburn and the Misery of 1997 (err = 0.065)
     - History Lesson for the History Channel (err = 0.298)
     - Can Chess, with Hexagons? (err = 0.188)
     - The Bizarre Search For Cracks: Sesame Street's Lost Nightmarish Short | blameitonjorge (err = 0.052)
     - Instagram’s Darkest Rabbit Hole (ft. Nick Crowley) (err = 0.175)
     - The Redditor that Vanished (err = 0.278)
     - Investigating the "Magic World of Ania” (err = 0.008)
     - Re: The Trouble With The Electoral College – Cities, Metro Areas, Elections and The United States (err = 0.015)
     - The Dark Side of Reddit [1] (err = 0.142)
     - Top 10 Best Songs From Kids Shows | blameitonjorge (err = 0.279)
     - 9 Ridiculous Pixar Ripoffs (feat. RebelTaxi) | blameitonjorge (err = 0.315)

📦 Cluster 8 — 10 samples
   R² = 0.4607 | Mean Abs Error = 0.300 ± 0.349
   🎯 Titles (most representative first):
     - Google Translate’s Strange Responses (err = 0.210)
     - Gas Stations and Sonic Sound Effects - Why? (err = 0.059)
     - The Lost Media of Creepypastas (err = 0.204)
     - Top 40 Creepiest Japanese Urban Legends (2017) | blameitonjorge (err = 0.300)
     - Lost Media From Nickelodeon 2022 (err = 0.091)
     - A Bizarre Lost Kids Show - The Search For Pink Morning Cartoon | blameitonjorge (err = 0.072)
     - How Sesame Street's Banned 847 Episode Was Found | The Lost Wicked Witch Segment (err = 0.039)
     - Not The Confederate Flag? (err = 0.533)
     - Summer of Grey: Parts 1 & 3 (err = 1.260)
     - 10 Worst Character Redesigns In Kids’ Shows | blameitonjorge (err = 0.228)

📦 Cluster 2 — 31 samples
   R² = 0.4503 | Mean Abs Error = 0.238 ± 0.180
   🎯 Titles (most representative first):
     - Hi I'm Mary Mary: Explained (err = 0.239)
     - What If the Electoral College is Tied? (err = 0.195)
     - The Cipher Hunt: Gravity Falls' Insane Worldwide Treasure Hunt | blameitonjorge (err = 0.289)
     - Unnerving YouTube Channels #2 (err = 0.189)
     - What's Going On with "Dad"? (err = 0.040)
     - Security Guard Encounters a Haunting (err = 0.274)
     - John Kricfalusi: An Open Secret | blameitonjorge (err = 0.198)
     - Q&A With Grey: Millenia of Human Attention Edition (err = 0.144)
     - Unnerving YouTube Channels #3 [NE Halloween 2017] (err = 0.153)
     - Your Theme (err = 0.245)
     - The Depravity of u/CarlH (err = 0.124)
     - 11 Insane Knockoffs of Popular Children's' Shows From Around The World (err = 0.249)
     - The Creepy "Hitogata" Japanese Commercial - Lost Media Case Files Vol 3 | blameitonjorge (err = 0.093)
     - Patrice Wilson Live Stream: Explained (err = 0.016)
     - The Alternative Vote Explained (err = 0.070)
     - Q&A With Grey: Favorites Edition (err = 0.074)
     - Who Took This Photograph? (err = 0.196)
     - 15 Lost Disney Cartoons, Episodes, & Shorts That We May Never See Again | blameitonjorge (err = 0.023)
     - 10 Japanese Rituals That Might Scare You To Death (err = 0.560)
     - ‘The Slamming Door’ Haunting: Revisited (err = 0.131)
     - Lost Media Found in 2023 (err = 0.081)
     - What is POSTcontent? (err = 0.296)
     - A New Theory on KrainaGrzybowTV (err = 0.555)
     - What is Interface? (err = 0.122)
     - 9 (more) Bizarre and Unsettling Public Access Shows Not Shown on Regular Television | blameitonjorge (err = 0.097)
     - Fear of the Deep (err = 0.216)
     - ✈️ The Maddening Mess of Airport Codes! ✈️ (err = 0.454)
     - Countries inside Countries (err = 0.435)
     - How Scotland Joined Great Britain (err = 0.359)
     - The Nickelodeon Movie That Used Real Bones - Lost Media Case Files Vol 2 | blameitonjorge (err = 0.446)
     - The Woman Who Went Missing Three Times: Hannah Upp | blameitonjorge (err = 0.813)

📦 Cluster 1 — 28 samples
   R² = 0.3052 | Mean Abs Error = 0.704 ± 0.401
   🎯 Titles (most representative first):
     - Vatican City Explained (err = 0.983)
     - Top 10 Best Episodes of Goosebumps | blameitonjorge (err = 0.027)
     - 12 Lost Pieces of Cartoon Network Media | blameitonjorge (err = 0.866)
     - Gemini and the End of the World (err = 1.381)
     - The European Union Explained* (err = 1.023)
     - Disturbing Things from Around the Internet [Vol. 4] (err = 0.400)
     - 7 Unnecessarily Horrifying Characters in Kid-Friendly Games (N64) | blameitonjorge (err = 1.219)
     - The Lost Films Iceberg (err = 0.503)
     - BREAKING NEWS! The Election's Most Difficult Decision… (err = 0.933)
     - 🎄 Grey Grades Canada's Flags!  (And Merry Xmas!) 🎄 (err = 0.360)
     - A Redditor's Strange Experience with Security Cameras (err = 0.492)
     - Erratas: The Mysterious Word You Shouldn't Search For | blameitonjorge (err = 1.068)
     - 2012 Didn't Happen (err = 0.393)
     - “We’re in the Matrix” Tech CEO's Cryptic Last Words | blameitonjorge (err = 0.500)
     - 40 MORE Lost or Banned Episodes of Kids Shows (err = 0.305)
     - The Scariest Lost PSAs (err = 0.496)
     - One Year & 100,000 Subscribers Later (Thank You!) (err = 1.352)
     - Top 5 Strange and Unnerving YouTube Videos (err = 0.846)
     - How to be a Pirate Quartermaster. 📈 💎 📈 (err = 0.595)
     - Your Social Security Card is Insecure (err = 0.821)
     - The Phelps Case (err = 0.407)
     - The Darkest Lost Media [Vol. 3] (err = 0.099)
     - 9 Episodes of Kids Shows That Dealt With Serious Issues | blameitonjorge (err = 1.825)
     - The Darkest Lost Media [Vol. 2] (err = 0.585)
     - Japan's Strangest Unsolved Mystery (err = 0.602)
     - Do You Recognize This Celebrity? (err = 0.635)
     - The Cult of "Obey The Walrus” (err = 0.579)
     - Disturbing Things from Around the Internet [Vol. 6] (ft. ScareTheater) (err = 0.417)

📦 Cluster 15 — 25 samples
   R² = 0.2946 | Mean Abs Error = 0.616 ± 0.338
   🎯 Titles (most representative first):
     - Disturbing Things from Around the Internet [Vol. 1] (err = 0.467)
     - Majora's Mask and the Art of Dark Symbolism (err = 0.548)
     - 🚨 BREAKING FLAG NEWS: Minnesota Getting a New Flag (err = 0.220)
     - Gerrymandering Explained (err = 0.052)
     - Death to Nickels (err = 0.949)
     - The MayDay Mystery: An Ongoing 30+ Year Old Puzzle | blameitonjorge (err = 1.252)
     - This Video is Worth $13,728.89 (err = 0.495)
     - 11 Lost Audio Clips From Fascinating to Terrifying | blameitonjorge (err = 0.581)
     - A Creator's Dive Into Turmoil (err = 0.321)
     - The Most Mysterious Commercial (err = 0.377)
     - What are Continents? (err = 0.726)
     - Where Did This Image Come From? (err = 0.488)
     - Disturbing Things from Around the Internet [Vol. 12] (err = 0.489)
     - The Dark Side of Reddit [2] (err = 0.181)
     - 2h32 Analysis (err = 1.559)
     - [UPDATED VERSION!] The Trouble With The Electoral College (err = 0.577)
     - 10 Most Insane Crossovers in Kids Shows (feat. PhantomStrider) | blameitonjorge (err = 0.407)
     - Felicity Rossi’s Zombie Doll: Explained in Three Minutes or Less (err = 1.128)
     - Disturbing Things from Around the Internet [Vol. 13] (err = 0.661)
     - What Happened to u/throwaway181718? (err = 0.920)
     - The Disturbing, Calculated Murder of Oakey Al Kite | blameitonjorge (err = 0.852)
     - Down the AshVlogs Rabbit Hole (err = 0.423)
     - The Sneaky Plan to Subvert the Electoral College for the Next Election (err = 0.443)
     - The Future of the Channel, and You (err = 0.754)
     - 10 Bizarre & Creepy Public Access Shows | blameitonjorge (err = 0.533)

📦 Cluster 3 — 26 samples
   R² = 0.2451 | Mean Abs Error = 0.606 ± 0.581
   🎯 Titles (most representative first):
     - The Debt Limit Explained (err = 0.270)
     - No Flag Northern Ireland (err = 0.023)
     - Into the Abyss of Haunted PS1 (err = 0.274)
     - The Simple Secret of Runway Numbers (err = 1.267)
     - A Redditor's Dive Into Turmoil (err = 0.289)
     - Top 20 Saddest Moments In Kid Shows | blameitonjorge (err = 2.226)
     - Primary Elections Explained (err = 0.270)
     - Supreme Court Shenanigans !!! (err = 1.089)
     - 10 Lost/Missing Pilot Episodes From Popular Kids Shows | blameitonjorge (err = 0.190)
     - My Experience with a Stalker (err = 0.157)
     - 20 Creepy YouTube Horror Channels (err = 1.391)
     - Canada & The United States's Bizarre Border (err = 1.771)
     - Is The Penny *Finally* Dead? (err = 0.688)
     - 💖 The History of The Tiffany 💖 (err = 0.032)
     - Top 20 Lost Kids Films | blameitonjorge (err = 0.091)
     - Lost Media Found in 2021 | blameitonjorge (err = 0.247)
     - Down the Rabb.it Hole (err = 0.921)
     - Time Management for Teachers (err = 1.215)
     - How to Pronounce Uranus (err = 0.431)
     - Road Trip After Eight Years Without Driving (err = 0.043)
     - London's Secret Mayor who runs The Secret City (err = 0.146)
     - Q&A With Grey: One Million Subscribers Edition (err = 0.614)
     - Siberia's Strangest Unsolved Mystery [Podcast Reveal] (err = 0.127)
     - Investigating the Disturbing Mystery of the Snapchat Intruder (err = 0.403)
     - A Dying Person's Search For A Lost Song - Lost Media Case Files Vol. 4 (err = 0.414)
     - Top 13 Lost Horror Films | blameitonjorge (err = 1.159)

📦 Cluster 10 — 25 samples
   R² = 0.1766 | Mean Abs Error = 0.852 ± 0.510
   🎯 Titles (most representative first):
     - Magibon's Online Stalker (err = 0.070)
     - How Drug Trafficking Destroyed This Popular Video Game (err = 0.796)
     - How AIs, like ChatGPT, Learn (err = 0.967)
     - An Empty City is Eerie Magic (err = 1.816)
     - 8 Animal Misconceptions Rundown (err = 0.401)
     - You Are Two (err = 1.250)
     - 🐝 Behind the Scenes of Rock, Paper, Scissors! 🪨📄✂️ (err = 1.464)
     - The Slamming Door Analysis (err = 1.198)
     - Investigating Nugumu: An Eerie Virtual YouTuber (err = 0.886)
     - Spaceship You (err = 0.091)
     - Digital Aristotle: Thoughts on the Future of Education (err = 0.684)
     - Why the UK Election Results are the Worst in History. (err = 0.527)
     - This Video Will Make You Angry (err = 1.058)
     - 🇬🇧🔥 Brexit, Briefly: REVISITED! 🔥🇪🇺 (err = 0.709)
     - Top 40 Lost or Cancelled Video Games (err = 0.547)
     - Disturbing Things from Around the Internet [Vol. 5] (err = 0.130)
     - 10 Absolute WORST Animated Shows Based off of Video Games (err = 0.279)
     - Fable of the Dragon-Tyrant (err = 0.691)
     - Lost Media Found in 2022 (err = 0.843)
     - The Lost Media Iceberg | blameitonjorge (err = 1.420)
     - Cult in a Dead MMO (err = 1.186)
     - Why Some Animals Can't be Domesticated (err = 1.378)
     - A Crime Against Childhood (err = 0.335)
     - TOP SNEAKY STAMP!!! (err = 0.588)
     - The Theme System Journal (err = 1.989)

📦 Cluster 6 — 33 samples
   R² = 0.1728 | Mean Abs Error = 0.736 ± 0.389
   🎯 Titles (most representative first):
     - Why Resident Evil 6 Failed (err = 0.456)
     - Exploring the Horrors of SOMA (err = 0.339)
     - Lost Media Found in the Strangest Ways 2 (err = 0.803)
     - 15 Hilariously Awful Wii Games | blameitonjorge (err = 0.757)
     - History of the Union Jack (err = 0.596)
     - Testing Tesla on the Deadliest Road in America 🐉 (err = 1.126)
     - Humans Need Not Apply (err = 1.320)
     - The Russian Doll Man (err = 0.396)
     - Disturbing Things from Around the Internet [Vol. 8] (err = 0.687)
     - Politics in the Animal Kingdom: Single Transferable Vote (err = 0.532)
     - The One Ring Explained (err = 0.646)
     - The Trouble with the Electoral College (err = 0.560)
     - The Dark Side of Reddit (err = 0.794)
     - 🇺🇸 DOES YOUR FLAG FAIL?  Grey Grades State Flags! (err = 1.314)
     - Q&A With Grey: 500,000 Subscribers Edition (err = 0.509)
     - Top 10 Misconceptions (err = 0.624)
     - Being President: Most Deadly Job in America (err = 0.856)
     - A Brief History of Santa (err = 0.492)
     - 2.5 Hours of Lost Media Stories (err = 1.150)
     - The Video Game Tied to a Cult (ft. MamaMax) (err = 0.488)
     - YouTube's Blood Cult: An Internet Rabbit Hole | blameitonjorge (err = 0.578)
     - Getting Vaccinated at the Coolest Place 😎 (err = 1.993)
     - How the Electoral College Works (err = 0.176)
     - Lord of the Rings Mythology Explained (err = 0.667)
     - Finland's Most Sinister Unsolved Mystery (err = 0.426)
     - Q&A With Grey: Meme Edition (err = 0.578)
     - Behind the Scenes Videos! (err = 0.417)
     - The Difference between the UK, Great Britain & England Explained (err = 1.499)
     - 8 Unexpectedly Dark Episodes in Cartoons | blameitonjorge (err = 1.008)
     - The Darkest Lost Media [Vol. 1] (err = 1.116)
     - How to Become the British Monarch (err = 0.774)
     - The Cryptic Disappearance of an Internet Celebrity | blameitonjorge (err = 0.378)
     - Who Owns Antarctica? (err = 0.228)

📦 Cluster 12 — 20 samples
   R² = 0.1447 | Mean Abs Error = 0.556 ± 0.159
   🎯 Titles (most representative first):
     - Top 20 Disturbing Moments in Kid Films | blameitonjorge (err = 0.640)
     - How to be a Pirate Captain! 🌈  ☠️ 🌈 (err = 0.522)
     - What Really Happened with u/YAYVIDEOGAMES? (err = 0.851)
     - The Dark Side of Reddit [3] (err = 0.578)
     - The Curse of Evil Otto (err = 0.334)
     - 8 Worst Ripoffs of Dreamworks Films (feat. PhantomStrider) | blameitonjorge (err = 0.701)
     - Ruby's Friend "Grateful" (err = 0.612)
     - This Video Will Hurt (err = 0.814)
     - Disturbing Things from Around the Internet [Vol. 3] (err = 0.375)
     - The Best Documented UFO Case: Lonnie Zamora | blameitonjorge (err = 0.351)
     - 5 More Strange and Unnerving YouTube Videos (err = 0.452)
     - Minority Rule: First Past the Post Voting (err = 0.639)
     - How Many Countries Are There? (err = 0.714)
     - Observer: Psychological Cyberpunk Horror (err = 0.444)
     - Coffee: The Greatest Addiction Ever (err = 0.526)
     - Lost Media Case Files Vol 1. | blameitonjorge (err = 0.608)
     - Supreme Court BANS Faithless Electors…………? (err = 0.354)
     - 7 Forgotten & Underrated Halloween Specials | blameitonjorge (err = 0.780)
     - Frank's Missing Cash, The Lucky 7 Broadcast, and A Mysterious Missing Woman | blameitonjorge (err = 0.447)
     - What Happened to the Sodder Children? (err = 0.374)

📦 Cluster 13 — 17 samples
   R² = 0.1373 | Mean Abs Error = 1.229 ± 0.569
   🎯 Titles (most representative first):
     - Top 5 Biggest Lost Media Finds of 2024 (so far) (err = 1.661)
     - 7 Insanely Shitty Superhero Ripoffs | blameitonjorge (err = 1.392)
     - 7 Surprisingly Dark Series Finales in Kid-Friendly Shows | blameitonjorge (err = 1.836)
     - Top 40 Lost or Banned Episodes of Kid Shows | blameitonjorge (err = 2.079)
     - Looking for Lisa Holst (Re: 10 Misconceptions Rundown) (err = 1.051)
     - The Creepy Instagram Alien (err = 1.086)
     - 11 Forgotten Cartoon Characters Removed From Television | blameitonjorge (err = 1.099)
     - Warminster UFO Analysis (err = 1.123)
     - Ryoma Analysis (err = 1.500)
     - Dan Schneider: A Scandal at Nickelodeon | blameitonjorge (err = 1.963)
     - Searching for The Five (err = 1.363)
     - Paranoia.com: An Internet Mystery (err = 0.537)
     - Silent Hill: Through the Years (err = 0.747)
     - Who is Justin Y? in Three Minutes or Less (err = 0.346)
     - The Dyatlov Pass Incident | PSX Documentaries (err = 2.151)
     - Your Family Tree Explained (err = 0.593)
     - The Coolest ''''Country''''' Flag You Need To Know (err = 0.369)

📦 Cluster 5 — 13 samples
   R² = 0.0998 | Mean Abs Error = 0.563 ± 0.288
   🎯 Titles (most representative first):
     - Are Daddy Longlegs Spiders?  (Re: 8 Animal Misconceptions Rundown) (err = 0.332)
     - Is Pluto a planet? (err = 0.152)
     - The Man Who Vanished Into Thin Air: Brian Shaffer | blameitonjorge (err = 0.338)
     - Disturbing Lost Media From Television (err = 0.640)
     - Disturbing Things from Around the Internet [Vol. 7] (err = 0.383)
     - Who Owns The Statue of Liberty? (err = 0.934)
     - Why Die? (err = 0.408)
     - TimmyThick's Strange Disappearance: Solved in Three Minutes or Less (err = 0.656)
     - Strange Flyers Around Portland, Oregon (err = 0.651)
     - 🌍 Which Planet is the Closest? (err = 0.521)
     - The Search Term that Made a YouTuber Vanish (ft. Atrocity Guide) (err = 1.269)
     - Lost Media Found in the Strangest Ways | blameitonjorge (err = 0.310)
     - Can You Win a 1 in 1 Million Game of Rock, Paper, Scissors? (Civilization may depend on it…) (err = 0.726)

📦 Cluster 18 — 31 samples
   R² = 0.0857 | Mean Abs Error = 1.099 ± 0.772
   🎯 Titles (most representative first):
     - American Empire (err = 1.022)
     - Behind the Scenes of TEKOI (err = 2.225)
     - More Mysterious & Spooky Lost Commercials (err = 1.640)
     - Disturbing Lost Recordings of Real Events (err = 0.140)
     - The Mysterious & Lost Locations Iceberg (err = 0.962)
     - The Law You Won't Be Told (err = 1.253)
     - The Top 20 Childhood Conspiracy Theories | blameitonjorge (err = 0.294)
     - The Disturbing Art of A.I. (err = 0.102)
     - 10 Hoaxes/Rumors in Kids Shows (feat: RebelTaxi & NightMind) | blameitonjorge (err = 0.210)
     - 15,000: Thank you. (err = 3.362)
     - The Mysterious Death of Elisa Lam (err = 2.450)
     - How AI, Like ChatGPT, *Really* Learns (err = 0.887)
     - The Trouble With Tumbleweed (err = 0.945)
     - Mixed-Member Proportional Representation Explained (err = 0.385)
     - The Vanishing of David Lewis (err = 0.109)
     - 3 Creepy and Unexplained Audio Recordings (err = 1.097)
     - 4Channer Goes Missing in 2013 (err = 1.090)
     - Holland vs the Netherlands (err = 1.059)
     - What are The Walten Files? (err = 1.348)
     - CGP Grey was WRONG (err = 0.310)
     - 6 Unexpectedly Dark Episodes in Kids Shows II | blameitonjorge (err = 1.173)
     - The "Real Blair Witch" Incident (err = 0.299)
     - Americapox: The Missing Plague (err = 0.892)
     - Nexpo: Extended Play | Video Extras (err = 1.068)
     - 5 Historical Misconceptions Rundown (err = 1.056)
     - I Feel Fantastic Analysis (err = 1.621)
     - How to Become Pope (err = 1.789)
     - The Most Terrifying Conspiracy | The Delta Project (err = 1.435)
     - NEW: More Designs for Your Sidekick Notepad! (err = 2.477)
     - Who or What is Stephanie Lawson Stevens? (err = 0.167)
     - Abandoned Nuclear Weapon Facility Exploration (err = 1.189)

📦 Cluster 19 — 20 samples
   R² = 0.0849 | Mean Abs Error = 1.181 ± 0.439
   🎯 Titles (most representative first):
     - Lost Media Bounties (err = 0.778)
     - Lost Media From Nintendo (err = 0.916)
     - 10 Episodes of Kids Shows That Dealt With Serious Issues II | blameitonjorge (err = 1.236)