In [ ]:
# params to modify

queries = ['Driver: San Francisco', 'Driver: San Francisco review', 'Driver: San Francisco retrospective', 'Driver: San Francisco critique', 'Driver: San Francisco analysis']
cadence = {'years': 10}
join_q = False
refresh = False


# setup things

from googleapiclient.errors import HttpError
from googleapiclient.discovery import build
from concurrent.futures import ThreadPoolExecutor, as_completed

from tqdm.notebook import tqdm
from datetime import datetime
from itertools import product

import pandas as pd
import polars as pl

import logging

logging.basicConfig(level=logging.DEBUG)


if join_q and len(queries) > 1:
    join_queries = True
else:
    join_queries = False


start_date = (datetime.now() - pd.DateOffset(**cadence)).strftime("%Y-%m-%d")
end_date = datetime.now().strftime("%Y-%m-%d")


# cadence term
key, val = list(cadence.items())[0]
cadence_str =  str(key)[0] + str(val)


# create db anem
queries = sorted(queries)
joined_queries = '|'.join(queries)
split_joined_queries = joined_queries.split('|')
initials = ''.join([x[0] for x in split_joined_queries])
join_str = 'joined' if join_queries else 'split'
db_name = f'{initials.lower()}_{cadence_str}_{join_str}.db'
print(f'Database name: {db_name}')


# Get API keys
api_key_loc = '../../data/keys'
with open(api_key_loc, 'r') as f:
    API_KEYS = f.read().splitlines()

import duckdb

connection_name = f'../../data/{db_name}'
con = duckdb.connect(connection_name)

if refresh:
    print('Dropping tables...')
    con.execute(f'DROP TABLE IF EXISTS search_results')
    con.execute(f'DROP TABLE IF EXISTS channel_statistics')
    con.execute(f'DROP TABLE IF EXISTS channnel_playlists')
    con.execute(f'DROP TABLE IF EXISTS video_statistics')
    con.commit()
else:
    print('Tables not dropped...')
    # print all tables
    con.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(con.fetchall())
    
# con.close()

In [ ]:
# Parallel Search


tqdm.pandas()


keys = API_KEYS.copy()

def get_videos_for_period(query_string, start_date, pbar, cadence=None):

    logging.debug(f'Query: {query_string}, Start Date: {start_date}')

    next_page_token = None
    
    period = {key: 1 for key in cadence.keys()}    
    
    start_date = pd.Timestamp(start_date).strftime('%Y-%m-%dT00:00:00Z')
    end_date = (
        pd.Timestamp(start_date) + pd.DateOffset(**period)
        if cadence else datetime.now()
    ).strftime('%Y-%m-%dT00:00:00Z')       
    
    search_results_data = []
    while True:
        
        logging.debug(f'Querying with API key: {keys[0]}')
        
        youtube = build('youtube', 'v3', developerKey=keys[0])
        # First API request (search)
        request = youtube.search().list(
            part='snippet',
            maxResults=50,
            pageToken=next_page_token,
            publishedAfter=start_date,
            publishedBefore=end_date,
            q=query_string,
            relevanceLanguage='en',
            type='video',
            # videoCategoryId='20'
        )
        
        try:
            response = request.execute()
        except HttpError as e:
            
            if e.resp.status == 403:
                
                logging.error(f"API key {keys[0]} has exceeded its quota.")
                
                pbar.set_postfix_str(f"Keys remaining: {len(keys)}")
                
                keys.pop(0)
                
                continue
        
        next_page_token = response.get('nextPageToken')
        search_items = response.get('items')
        search_results_data.extend(search_items)
        
        if not next_page_token:
            break
        
    return search_results_data


# Function to parallelize the queries and date range processing
def parallel_search_query_execution(queries, period_start_dates, cadence):
    
    # Combine the queries and dates into a product list
    queries_and_dates = list(product(queries, period_start_dates))

    # Initialize progress bar and list for storing results
    pbar = tqdm(total=len(queries_and_dates), desc="Processing Queries and Dates")
    search_data = []

    # Use ThreadPoolExecutor to handle parallel processing
    with ThreadPoolExecutor(max_workers=4) as executor:  # Adjust max_workers as needed
        futures = []
        
        # Submit all query-date tasks for parallel execution
        for query, start_date in queries_and_dates:
            futures.append(executor.submit(get_videos_for_period, query, start_date, pbar, cadence))

        # Collect results as they are completed
        for future in as_completed(futures):
            video_data = future.result()
            search_data.append(video_data)
            pbar.update(1)

    search_results = [elem for sub in search_data for elem in sub]
    
    search_results_df = pl.json_normalize(search_results)

    return search_results_df


import logging


logging_level = logging.DEBUG

logging.basicConfig(level=logging_level)

logging.info(f'Logging level {logging_level}')


# Calculate number of periods
num_periods = list(cadence.values())[0] + 1
period_start_dates = pd.date_range(start=start_date, end=end_date, periods=num_periods)[:-1]

logging.info(f'Number of periods: {num_periods}')
logging.info(f'Initial start date: {start_date}')
logging.info(f'End date: {end_date}')

query_list = [joined_queries] if join_queries else queries

# Call the parallelized search execution function
search_results_df = parallel_search_query_execution(query_list, period_start_dates, cadence)

search_results_df.write_database(table_name='search_results',
                                 connection=f'duckdb:///{connection_name}',
                                 if_table_exists='replace')

search_results_df = pl.read_database(query=f'SELECT * FROM search_results', 
                         connection=con)

search_results_df.shape

In [ ]:
# Parallel get channel statistics


api_keys = API_KEYS.copy()


# Function to get channel statistics
def get_channel_statistics(channel_id):
    
    while True:
        
        youtube = build('youtube', 'v3', developerKey=api_keys[0])
        request = youtube.channels().list(
            part='contentDetails,id,snippet,statistics,topicDetails',
            id=channel_id
        )
        
        try:
            response = request.execute()
            items_data = response.get('items')
            return items_data
            
        except HttpError as e:
            if e.resp.status == 403:  # Quota exceeded
                logging.error(f"API key {api_keys[0]} has exceeded its quota.")
                api_keys.pop(0)
            elif e.resp.status in [400, 404, 503]:
                logging.error(f"Error fetching statistics for {channel_id}: {e}")
                return
            else:
                raise e

from concurrent.futures import ThreadPoolExecutor, as_completed

# Parallelized fetch
def parallel_channel_statistics_fetch(channel_id_strings):
    
    channels_data = []
    
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = [
            executor.submit(get_channel_statistics, channel_id_string)
            for channel_id_string in tqdm(channel_id_strings, desc="Fetching Channel Statistics")
        ]

        for future in tqdm(as_completed(futures), total=len(futures), desc="Processing Results"):
            try:
                data = future.result()  # Get both data and the updated key index
                if data is not None:
                    channels_data.append(data)
            except Exception as e:
                print(f"Error processing a channel: {e}")
    
    flat_channel_data = [item for sublist in channels_data for item in sublist]
    
    channel_statistics_df = pl.json_normalize(flat_channel_data)
    
    return channel_statistics_df


import duckdb

connection_name = f'../../data/{db_name}'

con = duckdb.connect(connection_name)

logging.info(f"Found 'search_results' table. Getting channel statistics.")

channel_ids = con.sql('SELECT DISTINCT "snippet.channelId" FROM search_results').pl()

logging.info(f"Total unique channel IDs: {len(channel_ids)}")

batch_size = 50

channel_id_batches = (
    channel_ids
    .with_row_index()  # Add a row number to help with batch splitting
    .with_columns((pl.col("index") // batch_size).alias("batch"))  # Create batch numbers based on batch size
    .group_by("batch")  # Group by batch numbers
    .agg(
        pl.col("snippet.channelId").str.concat(delimiter=",").alias("joined_channelIds")  # Concatenate each batch into a single string
    )
)['joined_channelIds'].to_numpy()

channel_statistics_df = parallel_channel_statistics_fetch(channel_id_batches)


channel_statistics_df.write_database(table_name='channel_statistics',
                                 connection=f'duckdb:///{connection_name}',
                                 if_table_exists='replace')

channel_statistics_df = pl.read_database(query=f'SELECT * FROM channel_statistics', 
                         connection=con)

In [ ]:
# parallel get playlists


api_keys = API_KEYS.copy()


def get_channel_playlist_data(playlist_id, pbar):
    
    next_page_token = None
    channel_playlist_data = []
    
    while True:
        try:
            youtube = build('youtube', 'v3', developerKey=api_keys[0])

            request = youtube.playlistItems().list(
                part='contentDetails,snippet',
                playlistId=playlist_id,
                maxResults=50,
                pageToken=next_page_token
            )
            
            response = request.execute()
            response_data = response.get('items')
            channel_playlist_data.extend(response_data)

            pbar.update(len(response_data))

            next_page_token = response.get('nextPageToken')
            
            if not next_page_token:
                return channel_playlist_data
            
        except HttpError as e:
            if e.resp.status == 403:  # Quota exceeded
                logging.error(f"API key {api_keys[0]} has exceeded its quota.")
                api_keys.pop(0)

            elif e.resp.status == 404:
                print("Playlist not found.")
                break
            else:
                raise  # Re-raise the exception if it's not a quota error


connection_name = f'../../data/{db_name}'

con = duckdb.connect(connection_name)

table_names = con.execute("SELECT name FROM sqlite_master WHERE type='table';").pl()

# Main logic
if 'channel_statistics' in table_names['name']:

    logging.info(f"Found 'channel_statistics' table. Getting playlist info .")

    iteration = 0

    while True:

        table_names = con.execute("SELECT name FROM sqlite_master WHERE type='table';").pl()
        
        logging.info(f"Iteration {iteration}")

        channel_statistics_df = con.sql('SELECT * FROM channel_statistics').pl()

        # cast statistics.videoCount to int
        channel_statistics_df = channel_statistics_df.with_columns(
            pl.col('statistics.videoCount').cast(pl.Int32)
        )        

        logging.info(f"Total unique channel IDs: {channel_statistics_df.height}")
        
        if 'channel_playlists' in table_names['name']:
            
            logging.info(f"Found 'channel_playlists' table. Filtering channel IDs.")
            
            channel_playlists_ids = con.sql('SELECT DISTINCT "snippet.channelId" FROM channel_playlists').pl()
            
            channel_statistics_df = channel_statistics_df.filter(
                ~pl.col('id').is_in(channel_playlists_ids['snippet.channelId'])
                )
            
            logging.info(f"Channels to fetch: {channel_statistics_df.height}")
        
        number_of_videos = channel_statistics_df['statistics.videoCount'].sum()
        
        logging.info(f"Total number of videos: {number_of_videos}")
        
        if number_of_videos == 0:
            logging.info("All videos fetched.")
            break
    
        pbar = tqdm(total=number_of_videos, desc="Fetching Playlist Items")        

        channel_playlists_data = []
        
        def process_channel(channel_id):
            playlist_id = 'UU' + channel_id[2:]
            logging.info(f"Fetching videos for channel {channel_id} with playlist ID {playlist_id}")
            channel_playlist_data = get_channel_playlist_data(playlist_id, pbar)
            return channel_playlist_data
        
        with ThreadPoolExecutor(max_workers=4) as executor:
            futures = {executor.submit(process_channel, channel_id): channel_id for channel_id in channel_statistics_df['id']}

            for future in as_completed(futures):
                channel_id = futures[future]
                try:
                    channel_playlist_data = future.result()
                    if channel_playlist_data is not None:
                        channel_playlists_df = pl.json_normalize(channel_playlist_data)
                        channel_playlists_df.write_database(table_name='channel_playlists',
                                                            connection=f'duckdb:///{connection_name}',
                                                            if_table_exists='append')
                except Exception as e:
                    logging.error(f"Error processing channel {channel_id}: {e}")

        iteration += 1

In [ ]:
# Parallel video statistics fetch [suboptimal]


api_keys = API_KEYS.copy()


# Parameters
concurrent_requests = 64
batch_size = 1
wait_when_rate_limited = 60
timeout_seconds = 120
use_cookies = False
 
import aiohttp
import asyncio
from sqlalchemy.exc import ProgrammingError


semaphore = asyncio.Semaphore(concurrent_requests)


def fetch_video_statistics_for_id_string(id_string, pbar):
    
    logging.debug(f'Fetching video statistics for ID string: {id_string}')
        
    try:
        youtube = build('youtube', 'v3', developerKey=api_keys[0])

        request = youtube.videos().list(
            part='contentDetails,id,liveStreamingDetails,snippet,statistics,topicDetails',
            id=id_string
        )
        
        response = request.execute()
        
        items = response.get('items')
        
        logging.debug(f'Number of items: {len(items)}')
        
        pbar.update(len(items))
        
        return items
        
    except HttpError as e:
        
        if e.resp.status == 403:  # Quota exceeded
            logging.error(f"API key {api_keys[0]} has exceeded its quota.")
            api_keys.pop(0)
        else:
            raise  # Re-raise the exception if it's not a quota error


async def fetch_video_statistics_for_channel(channel, pbar):
    
    next_page_token = None 
    
    playlist_id = 'UU' + channel[2:]

    playlist_data = []

    async with semaphore:
        
        while True:
            
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys[0])

                playlist_request = youtube.playlistItems().list(
                    part='contentDetails,snippet',
                    playlistId=playlist_id,
                    maxResults=50,
                    pageToken=next_page_token
                )
                
                playlist_response = playlist_request.execute()
                playlist_items = playlist_response.get('items')
                playlist_data.extend(playlist_items)
                
                next_page_token = playlist_response.get('nextPageToken')
                    
                if not next_page_token:
                    break
                    
            except HttpError as e:
                
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys[0]} has exceeded its quota.")
                    api_keys.pop(0)
                else:
                    raise  # Re-raise the exception if it's not a quota error
                
        video_ids = [item['snippet']['resourceId']['videoId'] for item in playlist_data]
        
        batch_size = 50
        video_id_batches = [video_ids[i:i + batch_size] for i in range(0, len(video_ids), batch_size)]
        video_id_strings = [','.join(video_id_batch) for video_id_batch in video_id_batches]
        
        video_statistics_data = [fetch_video_statistics_for_id_string(video_id_string, pbar) for video_id_string in video_id_strings]
        flattened_video_statistics_data = [item for sublist in video_statistics_data for item in sublist]
        
        result_df = pl.json_normalize(flattened_video_statistics_data)
        
        try:
            
            logging.debug(f"Writing video statistics to database for channel {channel}")
            
            result_df.write_database(table_name='video_statistics',
                                        connection=f'duckdb:///{connection_name}',
                                        if_table_exists='append')
        except ProgrammingError as e:
            if 'column' in str(e):
                existing_columns = con.execute("SELECT * FROM video_statistics LIMIT 1").fetch_df().columns
                for column in result_df.columns:
                    if column not in existing_columns:
                        try:
                            alter_stmt = f'ALTER TABLE video_statistics ADD COLUMN "{column}" TEXT'
                            con.execute(alter_stmt)
                            logging.info(f"Added missing column: {column}")
                        except Exception as e:
                            logging.error(f'Failed to add column: {column}')
                result_df.write_database(table_name='video_statistics',
                                        connection=f'duckdb:///{connection_name}',
                                        if_table_exists='append')        
        
        return 


async def fetch_data(channel_statistics_ids):
    
    pbar = tqdm(total=video_sums, desc="Fetching Video Statistics")
    
    tasks = [fetch_video_statistics_for_channel(channel_id, pbar) for channel_id in channel_statistics_ids]
    
    for task in tqdm(asyncio.as_completed(tasks), total=len(tasks)):
        await task

    pbar.close()
    

import duckdb

connection_name = f'../../data/{db_name}'
con = duckdb.connect(connection_name)

table_names = con.execute("SELECT name FROM sqlite_master WHERE type='table';").pl()

# Main logic
if 'channel_statistics' in table_names['name']:
    
    channel_statistics_df = con.sql('SELECT * FROM channel_statistics').pl()
    
    channel_statistics_df = channel_statistics_df.with_columns(
        pl.col('statistics.videoCount').cast(pl.Int32)
    )

    logging.info(f"Total unique channel IDs: {channel_statistics_df.shape[0]}")
    
    if 'video_statistics' in table_names['name']:
        
        video_statistics_ids = con.sql('SELECT DISTINCT "snippet.channelId" FROM video_statistics').pl()
        
        logging.info(f"Total unique video statistics channel IDs: {video_statistics_ids.shape[0]}")
        
        channel_statistics_df = channel_statistics_df.filter(
               ~pl.col('id').is_in(video_statistics_ids['snippet.channelId'])
            )

        
    logging.info(f"Channels to fetch: {channel_statistics_df.shape[0]}")
        
    video_sums = channel_statistics_df['statistics.videoCount'].sum()
    
    channel_statistics_ids = channel_statistics_df['id'].to_numpy().flatten()
        
    await fetch_data(channel_statistics_ids)

In [ ]:
import duckdb

connection_name = f'../../data/{db_name}'

con = duckdb.connect(connection_name)

video_statistics_df = con.execute(f'SELECT * FROM video_statistics').pl()

video_statistics_df

In [ ]:
def fetch_video_statistics_for_id_string(id_string):
    
    logging.debug(f'Fetching video statistics for ID string: {id_string}')
        
    try:
        youtube = build('youtube', 'v3', developerKey=api_keys[0])

        request = youtube.videos().list(
            part='contentDetails,id,liveStreamingDetails,snippet,statistics,topicDetails',
            id=id_string
        )
        
        response = request.execute()
        
        items = response.get('items')
        
        logging.debug(f'Number of items: {len(items)}')
        
        return items
        
    except HttpError as e:
        
        if e.resp.status == 403:  # Quota exceeded
            logging.error(f"API key {api_keys[0]} has exceeded its quota.")
            api_keys.pop(0)
        else:
            raise  # Re-raise the exception if it's not a quota error
        
        
api_keys = API_KEYS.copy()

# break into groups of 50
video_ids = search_results_df['id.videoId'].to_numpy().flatten()
batch_size = 50
video_id_batches = [video_ids[i:i + batch_size] for i in range(0, len(video_ids), batch_size)]

video_id_strings = [','.join(video_id_batch) for video_id_batch in video_id_batches]
video_statistics_data = [fetch_video_statistics_for_id_string(video_id_string) for video_id_string in tqdm(video_id_strings)]

no_none = [item for item in video_statistics_data if item]
flattened_video_statistics_data = [item for sublist in no_none for item in sublist]
result_df = pl.json_normalize(flattened_video_statistics_data)
result_df

In [ ]:
result_df.write_parquet(f'../../data/driver_san_francisco_video_statistics.parquet')

In [ ]:
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import polars as pl
from tqdm.auto import tqdm
import logging

def get_channel_videos(channel_identifier, api_keys):
    """
    Get all videos from a YouTube channel.
    
    Parameters:
    -----------
    channel_identifier : str
        The channel ID or handle (with or without @ symbol)
    api_keys : list
        List of YouTube API keys to use
        
    Returns:
    --------
    polars.DataFrame
        DataFrame containing video title, ID, and description
    """
    api_keys_copy = api_keys.copy()
    
    # Step 1: Convert handle to channel ID if needed
    channel_id = None
    if channel_identifier.startswith('@') or not channel_identifier.startswith('UC'):
        # If this is a handle, we need to get the channel ID
        handle = channel_identifier
        if not handle.startswith('@'):
            handle = f'@{handle}'
            
        while True:
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                request = youtube.search().list(
                    part='snippet',
                    q=handle,
                    type='channel',
                    maxResults=1
                )
                response = request.execute()
                
                if response.get('items'):
                    channel_id = response['items'][0]['snippet']['channelId']
                    logging.info(f"Converted handle {handle} to channel ID: {channel_id}")
                    break
                else:
                    raise ValueError(f"Could not find channel with handle: {handle}")
                    
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                else:
                    raise e
    else:
        channel_id = channel_identifier
    
    # Step 2: Create uploads playlist ID
    playlist_id = 'UU' + channel_id[2:]
    logging.info(f"Using uploads playlist ID: {playlist_id}")
    
    # Step 3: Get all videos from the uploads playlist
    next_page_token = None
    all_videos = []
    
    with tqdm(desc="Fetching videos") as pbar:
        while True:
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                
                request = youtube.playlistItems().list(
                    part='contentDetails,snippet',
                    playlistId=playlist_id,
                    maxResults=50,
                    pageToken=next_page_token
                )
                
                response = request.execute()
                videos = response.get('items', [])
                all_videos.extend(videos)
                
                pbar.update(len(videos))
                pbar.set_postfix({"total": len(all_videos)})
                
                next_page_token = response.get('nextPageToken')
                if not next_page_token:
                    break
                    
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                elif e.resp.status == 404:
                    logging.error("Playlist not found.")
                    break
                else:
                    raise e
    
    # Step 4: Extract relevant data
    video_data = []
    for video in all_videos:
        video_data.append({
            'title': video['snippet']['title'],
            'video_id': video['snippet']['resourceId']['videoId'],
            'description': video['snippet']['description'],
            'published_at': video['snippet']['publishedAt'],
            'channel_id': video['snippet']['channelId'],
            'channel_title': video['snippet']['channelTitle']
        })
    
    # Create polars DataFrame
    if video_data:
        df = pl.DataFrame(video_data)
        logging.info(f"Found {len(df)} videos for channel {channel_id}")
        return df
    else:
        logging.warning(f"No videos found for channel {channel_id}")
        return pl.DataFrame({
            'title': [],
            'video_id': [],
            'description': [],
            'published_at': [],
            'channel_id': [],
            'channel_title': []
        })

INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Converted handle @SecretBaseSBN to channel ID: UCGz-bVKK0HR2zZzJHEeYvWA
INFO:root:Using uploads playlist ID: UUGz-bVKK0HR2zZzJHEeYvWA
Fetching videos: 0it [00:00, ?it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1it [00:00,  6.18it/s, total=1]
INFO:root:Found 1 videos for channel UCGz-bVKK0HR2zZzJHEeYvWA

Found 1 videos
shape: (1, 6)
┌──────────────────┬─────────────┬─────────────┬─────────────────┬─────────────────┬───────────────┐
│ title            ┆ video_id    ┆ description ┆ published_at    ┆ channel_id      ┆ channel_title │
│ ---              ┆ ---         ┆ ---         ┆ ---             ┆ ---             ┆ ---           │
│ str              ┆ str         ┆ str         ┆ str             ┆ str             ┆ str           │
╞══════════════════╪═════════════╪═════════════╪═════════════════╪═════════════════╪═══════════════╡
│ secret base～君  ┆ E9PXmSQu_5E ┆             ┆ 2024-07-02T12:5 ┆ UCGz-bVKK0HR2zZ ┆ ななさん      │
│ がくれたもの～歌 ┆             ┆             ┆ 8:39Z           ┆ zJHEeYvWA       ┆               │
│ の最高のギター指 ┆             ┆             ┆                 ┆                 ┆               │
│ 弾…              ┆             ┆             ┆                 ┆                 ┆               │
└──────────────────┴─────────────┴─────────────┴─────────────────┴─────────────────┴───────────────┘

In [9]:
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import polars as pl
from tqdm.auto import tqdm
import logging
import re

def get_channel_videos(channel_identifier, api_keys):
    """
    Get all videos from a YouTube channel.
    
    Parameters:
    -----------
    channel_identifier : str
        The channel ID, username, or handle (with or without @ symbol)
    api_keys : list
        List of YouTube API keys to use
        
    Returns:
    --------
    polars.DataFrame
        DataFrame containing video title, ID, and description
    """
    api_keys_copy = api_keys.copy()
    
    # Step 1: Determine the channel ID
    channel_id = None
    
    # Check if it's already a channel ID (starts with UC)
    if channel_identifier.startswith('UC'):
        channel_id = channel_identifier
        logging.info(f"Using provided channel ID: {channel_id}")
    else:
        # Handle custom channel identifier (username or @handle)
        username = channel_identifier
        if username.startswith('@'):
            username = username[1:]  # Remove @ symbol
        
        while True and api_keys_copy:
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                
                # Try with forUsername parameter (works for legacy usernames)
                try:
                    request = youtube.channels().list(
                        part='id',
                        forUsername=username
                    )
                    response = request.execute()
                    
                    if response.get('items'):
                        channel_id = response['items'][0]['id']
                        logging.info(f"Converted username {username} to channel ID: {channel_id}")
                        break
                except HttpError:
                    pass  # If this fails, it might be a newer @handle format
                
                # If we didn't get a channel ID, we need a different approach
                # For newer handles, we might need to use a different approach or custom URL
                if not channel_id:
                    logging.warning(f"Could not directly resolve username/handle: {username}")
                    logging.warning("Please provide a channel ID instead, or use a web browser to find the channel ID")
                    
                    # Ask the user for the channel ID or URL
                    user_input = input(f"Could not automatically resolve {channel_identifier}. Please enter the channel ID or URL manually: ")
                    
                    # Extract channel ID from URL if provided
                    if 'youtube.com' in user_input:
                        if 'channel/' in user_input:
                            channel_id = re.search(r'channel/([^/?]+)', user_input).group(1)
                        elif 'c/' in user_input:
                            # We need to do another lookup for custom URLs
                            custom_name = re.search(r'c/([^/?]+)', user_input).group(1)
                            logging.warning(f"Custom URLs (c/{custom_name}) require manual channel ID lookup")
                            channel_id = input("Please enter the channel ID directly (starts with UC): ")
                    else:
                        # Assume they entered the channel ID directly
                        channel_id = user_input
                    
                    if not channel_id.startswith('UC'):
                        raise ValueError("Invalid channel ID. Channel IDs should start with 'UC'")
                    break
                    
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                else:
                    raise e
    
    if not channel_id:
        raise ValueError(f"Could not determine channel ID for: {channel_identifier}")
    
    # Step 2: Create uploads playlist ID
    playlist_id = 'UU' + channel_id[2:]
    logging.info(f"Using uploads playlist ID: {playlist_id}")
    
    # Step 3: Get all videos from the uploads playlist
    next_page_token = None
    all_videos = []
    
    with tqdm(desc="Fetching videos") as pbar:
        while True and api_keys_copy:
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                
                request = youtube.playlistItems().list(
                    part='contentDetails,snippet',
                    playlistId=playlist_id,
                    maxResults=50,
                    pageToken=next_page_token
                )
                
                response = request.execute()
                videos = response.get('items', [])
                all_videos.extend(videos)
                
                pbar.update(len(videos))
                pbar.set_postfix({"total": len(all_videos)})
                
                next_page_token = response.get('nextPageToken')
                if not next_page_token:
                    break
                    
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                elif e.resp.status == 404:
                    logging.error("Playlist not found.")
                    break
                else:
                    raise e
    
    # Step 4: Extract relevant data
    video_data = []
    for video in all_videos:
        video_data.append({
            'title': video['snippet']['title'],
            'video_id': video['snippet']['resourceId']['videoId'],
            'description': video['snippet']['description'],
            'published_at': video['snippet']['publishedAt'],
            'channel_id': video['snippet']['channelId'],
            'channel_title': video['snippet']['channelTitle']
        })
    
    # Create polars DataFrame
    if video_data:
        df = pl.DataFrame(video_data)
        logging.info(f"Found {len(df)} videos for channel {channel_id}")
        return df
    else:
        logging.warning(f"No videos found for channel {channel_id}")
        return pl.DataFrame({
            'title': [],
            'video_id': [],
            'description': [],
            'published_at': [],
            'channel_id': [],
            'channel_title': []
        })

In [10]:
# UCDRmGMSgrtZkOsh_NQl4_xw

# Example usage
if __name__ == "__main__":
    # Get API keys
    api_key_loc = '../../data/keys'
    with open(api_key_loc, 'r') as f:
        API_KEYS = f.read().splitlines()
    
    # Set up logging
    logging.basicConfig(level=logging.INFO)
    
    # Get videos for a channel
    channel_videos = get_channel_videos('@SecretBaseSBN', API_KEYS)
    
    # Display results
    print(f"Found {len(channel_videos)} videos")
    print(channel_videos.head())
    # Optionally save to file
    channel_videos.write_csv("channel_videos.csv")

INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
WARNING:root:Could not directly resolve username/handle: SecretBaseSBN
WARNING:root:Please provide a channel ID instead, or use a web browser to find the channel ID
INFO:root:Using uploads playlist ID: UUDRmGMSgrtZkOsh_NQl4_xw
Fetching videos: 0it [00:00, ?it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 50it [00:00, 179.64it/s, total=50]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 100it [00:00, 213.81it/s, total=100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 150it [00:00, 209.61it/s, total=150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 200it [00:00, 205.14it/s, total=200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 250it [00:01, 199.54it/s, total=250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 300it [00:01, 209.81it/s, total=300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 350it [00:01, 217.98it/s, total=350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 400it [00:01, 216.20it/s, total=400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 450it [00:02, 217.28it/s, total=450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 500it [00:02, 218.04it/s, total=500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 550it [00:02, 222.50it/s, total=550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 600it [00:02, 215.96it/s, total=600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 650it [00:03, 217.68it/s, total=650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 700it [00:03, 224.93it/s, total=700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 750it [00:03, 231.54it/s, total=750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 800it [00:03, 233.96it/s, total=800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 850it [00:03, 241.02it/s, total=850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 900it [00:04, 252.60it/s, total=900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 950it [00:04, 257.40it/s, total=950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1000it [00:04, 265.79it/s, total=1000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1050it [00:04, 239.52it/s, total=1050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1100it [00:04, 232.07it/s, total=1100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1150it [00:05, 230.83it/s, total=1150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1200it [00:05, 231.67it/s, total=1200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1250it [00:05, 226.76it/s, total=1250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1300it [00:05, 236.59it/s, total=1300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1350it [00:05, 219.67it/s, total=1350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1400it [00:06, 232.25it/s, total=1400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1450it [00:06, 247.54it/s, total=1450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1500it [00:06, 237.81it/s, total=1500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1550it [00:06, 221.57it/s, total=1550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1600it [00:07, 236.98it/s, total=1600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1650it [00:07, 250.38it/s, total=1650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1700it [00:07, 232.16it/s, total=1700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1750it [00:07, 210.25it/s, total=1750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1800it [00:07, 226.59it/s, total=1800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1850it [00:08, 238.96it/s, total=1850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1900it [00:08, 246.63it/s, total=1900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 1950it [00:08, 252.31it/s, total=1950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2000it [00:08, 261.94it/s, total=2000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2050it [00:08, 230.44it/s, total=2050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2100it [00:09, 213.36it/s, total=2100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2150it [00:09, 227.64it/s, total=2150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2200it [00:09, 243.86it/s, total=2200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2250it [00:09, 252.13it/s, total=2250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2300it [00:09, 265.91it/s, total=2300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2350it [00:10, 268.01it/s, total=2350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2400it [00:10, 261.04it/s, total=2400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2450it [00:10, 236.16it/s, total=2450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2500it [00:10, 233.52it/s, total=2500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2550it [00:10, 245.36it/s, total=2550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2600it [00:11, 226.09it/s, total=2600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2650it [00:11, 234.44it/s, total=2650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2700it [00:11, 218.97it/s, total=2700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2750it [00:11, 219.49it/s, total=2750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2800it [00:12, 235.31it/s, total=2800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2850it [00:12, 237.80it/s, total=2850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2900it [00:12, 250.84it/s, total=2900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 2950it [00:12, 253.11it/s, total=2950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3000it [00:12, 207.67it/s, total=3000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3050it [00:13, 212.53it/s, total=3050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3100it [00:13, 223.94it/s, total=3100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3150it [00:13, 210.92it/s, total=3150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3200it [00:13, 221.67it/s, total=3200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3250it [00:14, 216.73it/s, total=3250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3300it [00:14, 216.25it/s, total=3300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3350it [00:14, 220.38it/s, total=3350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3400it [00:14, 201.24it/s, total=3400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3450it [00:15, 206.96it/s, total=3450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3500it [00:15, 216.42it/s, total=3500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3550it [00:15, 225.56it/s, total=3550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3600it [00:15, 226.59it/s, total=3600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3650it [00:15, 210.18it/s, total=3650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3700it [00:16, 220.68it/s, total=3700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3750it [00:16, 222.41it/s, total=3750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3800it [00:16, 211.45it/s, total=3800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3850it [00:16, 207.63it/s, total=3850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3900it [00:17, 206.52it/s, total=3900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3950it [00:17, 220.09it/s, total=3950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching videos: 3951it [00:17, 225.41it/s, total=3951]
INFO:root:Found 3951 videos for channel UCDRmGMSgrtZkOsh_NQl4_xw

Found 3951 videos
shape: (5, 6)
┌─────────────────┬─────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ title           ┆ video_id    ┆ description    ┆ published_at   ┆ channel_id     ┆ channel_title │
│ ---             ┆ ---         ┆ ---            ┆ ---            ┆ ---            ┆ ---           │
│ str             ┆ str         ┆ str            ┆ str            ┆ str            ┆ str           │
╞═════════════════╪═════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ The greatest    ┆ IGt2Gx-07O8 ┆ This might be  ┆ 2025-05-09T16: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ offensive       ┆             ┆ too many hits  ┆ 59:24Z         ┆ sh_NQl4_xw     ┆               │
│ perform…        ┆             ┆ an…            ┆                ┆                ┆               │
│ Shohei Ohtani   ┆ lmHkqblgdec ┆ In 2024, Los   ┆ 2025-05-09T16: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ crafted a       ┆             ┆ Angeles        ┆ 01:17Z         ┆ sh_NQl4_xw     ┆               │
│ season…         ┆             ┆ Dodgers s…     ┆                ┆                ┆               │
│ Welcome to Year ┆ CrGp5O6FVv0 ┆ Year one flew  ┆ 2025-05-05T17: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ 2 of Top Secre… ┆             ┆ by over at     ┆ 00:14Z         ┆ sh_NQl4_xw     ┆               │
│                 ┆             ┆ https…         ┆                ┆                ┆               │
│ Kyrie Irving’s  ┆ EMDCaFsqwrU ┆ Starting in    ┆ 2025-05-02T19: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ beef with       ┆             ┆ the 2017-18    ┆ 00:10Z         ┆ sh_NQl4_xw     ┆               │
│ Bosto…          ┆             ┆ season…        ┆                ┆                ┆               │
│ Deion Sanders   ┆ DGX9vRMYfms ┆ Hopefully,     ┆ 2025-04-25T19: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ vs. Andre Rison ┆             ┆ Shedeur can    ┆ 25:04Z         ┆ sh_NQl4_xw     ┆               │
│ …               ┆             ┆ learn f…       ┆                ┆                ┆               │
└─────────────────┴─────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [11]:
channel_videos

shape: (3_951, 6)
┌─────────────────┬─────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ title           ┆ video_id    ┆ description    ┆ published_at   ┆ channel_id     ┆ channel_title │
│ ---             ┆ ---         ┆ ---            ┆ ---            ┆ ---            ┆ ---           │
│ str             ┆ str         ┆ str            ┆ str            ┆ str            ┆ str           │
╞═════════════════╪═════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ The greatest    ┆ IGt2Gx-07O8 ┆ This might be  ┆ 2025-05-09T16: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ offensive       ┆             ┆ too many hits  ┆ 59:24Z         ┆ sh_NQl4_xw     ┆               │
│ perform…        ┆             ┆ an…            ┆                ┆                ┆               │
│ Shohei Ohtani   ┆ lmHkqblgdec ┆ In 2024, Los   ┆ 2025-05-09T16: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ crafted a       ┆             ┆ Angeles        ┆ 01:17Z         ┆ sh_NQl4_xw     ┆               │
│ season…         ┆             ┆ Dodgers s…     ┆                ┆                ┆               │
│ Welcome to Year ┆ CrGp5O6FVv0 ┆ Year one flew  ┆ 2025-05-05T17: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ 2 of Top Secre… ┆             ┆ by over at     ┆ 00:14Z         ┆ sh_NQl4_xw     ┆               │
│                 ┆             ┆ https…         ┆                ┆                ┆               │
│ Kyrie Irving’s  ┆ EMDCaFsqwrU ┆ Starting in    ┆ 2025-05-02T19: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ beef with       ┆             ┆ the 2017-18    ┆ 00:10Z         ┆ sh_NQl4_xw     ┆               │
│ Bosto…          ┆             ┆ season…        ┆                ┆                ┆               │
│ Deion Sanders   ┆ DGX9vRMYfms ┆ Hopefully,     ┆ 2025-04-25T19: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ vs. Andre Rison ┆             ┆ Shedeur can    ┆ 25:04Z         ┆ sh_NQl4_xw     ┆               │
│ …               ┆             ┆ learn f…       ┆                ┆                ┆               │
│ …               ┆ …           ┆ …              ┆ …              ┆ …              ┆ …             │
│ Westminster     ┆ 65rlXiWlbxU ┆ Full story:    ┆ 2012-02-14T23: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ Kennel Club Dog ┆             ┆ http://www.sbn ┆ 43:03Z         ┆ sh_NQl4_xw     ┆               │
│ Sh…             ┆             ┆ atio…          ┆                ┆                ┆               │
│ A Super Bowl    ┆ _p_rzRkz6YA ┆ Gary Grimes    ┆ 2012-02-03T08: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ Gesture: Giants ┆             ┆ nearly died in ┆ 00:46Z         ┆ sh_NQl4_xw     ┆               │
│ C…              ┆             ┆ a c…           ┆                ┆                ┆               │
│ Super Bowl      ┆ FGGggOPCok0 ┆ Top Chef's Eli ┆ 2012-02-02T18: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ Party Tips: Eli ┆             ┆ Kirshtein      ┆ 23:26Z         ┆ sh_NQl4_xw     ┆               │
│ Kir…            ┆             ┆ helps…         ┆                ┆                ┆               │
│ Pro Quality,    ┆ MHza9mqt0Zk ┆ Subscribe to   ┆ 2011-12-22T18: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ Fan Perspective ┆             ┆ our channel    ┆ 37:24Z         ┆ sh_NQl4_xw     ┆               │
│ -…              ┆             ┆ for m…         ┆                ┆                ┆               │
│ Pro Quality,    ┆ 2qccmZk92Aw ┆ Subscribe to   ┆ 2011-12-22T18: ┆ UCDRmGMSgrtZkO ┆ Secret Base   │
│ Fan Perspective ┆             ┆ our channel    ┆ 36:56Z         ┆ sh_NQl4_xw     ┆               │
│ -…              ┆             ┆ for m…         ┆                ┆                ┆               │
└─────────────────┴─────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [14]:
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import polars as pl
from tqdm.auto import tqdm
import logging
import re
import isodate  # For parsing ISO 8601 duration format

def get_channel_videos(channel_identifier, api_keys):
    """
    Get all videos from a YouTube channel.
    
    Parameters:
    -----------
    channel_identifier : str
        The channel ID (starts with UC)
    api_keys : list
        List of YouTube API keys to use
        
    Returns:
    --------
    polars.DataFrame
        DataFrame containing video title, ID, description, and duration
    """
    api_keys_copy = api_keys.copy()
    
    # Step 1: Determine the channel ID
    channel_id = None
    
    # Check if it's already a channel ID (starts with UC)
    if isinstance(channel_identifier, str) and channel_identifier.startswith('UC'):
        channel_id = channel_identifier
        logging.info(f"Using provided channel ID: {channel_id}")
    else:
        raise ValueError("Please provide a valid channel ID starting with 'UC'")
    
    # Step 2: Create uploads playlist ID
    playlist_id = 'UU' + channel_id[2:]
    logging.info(f"Using uploads playlist ID: {playlist_id}")
    
    # Step 3: Get all videos from the uploads playlist
    next_page_token = None
    all_video_ids = []
    
    with tqdm(desc="Fetching video IDs") as pbar:
        while True and api_keys_copy:
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                
                request = youtube.playlistItems().list(
                    part='contentDetails',  # Only need contentDetails for videoId
                    playlistId=playlist_id,
                    maxResults=50,
                    pageToken=next_page_token
                )
                
                response = request.execute()
                videos = response.get('items', [])
                
                # Extract video IDs
                for video in videos:
                    all_video_ids.append(video['contentDetails']['videoId'])
                
                pbar.update(len(videos))
                pbar.set_postfix({"total": len(all_video_ids)})
                
                next_page_token = response.get('nextPageToken')
                if not next_page_token:
                    break
                    
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                elif e.resp.status == 404:
                    logging.error("Playlist not found.")
                    break
                else:
                    raise e
    
    # Step 4: Fetch detailed information for all videos in batches
    video_data = []
    batch_size = 50  # YouTube API allows up to 50 video IDs per request
    
    with tqdm(total=len(all_video_ids), desc="Fetching video details") as pbar:
        # Create batches of video IDs
        for i in range(0, len(all_video_ids), batch_size):
            batch_ids = all_video_ids[i:i+batch_size]
            id_string = ','.join(batch_ids)
            
            try:
                youtube = build('youtube', 'v3', developerKey=api_keys_copy[0])
                
                request = youtube.videos().list(
                    part='contentDetails,snippet,statistics',
                    id=id_string
                )
                
                response = request.execute()
                batch_videos = response.get('items', [])
                
                for video in batch_videos:
                    # Parse the ISO 8601 duration format
                    duration_iso = video['contentDetails']['duration']
                    duration_seconds = int(isodate.parse_duration(duration_iso).total_seconds())
                    
                    # Format duration as HH:MM:SS
                    hours, remainder = divmod(duration_seconds, 3600)
                    minutes, seconds = divmod(remainder, 60)
                    duration_formatted = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
                    
                    video_data.append({
                        'title': video['snippet']['title'],
                        'video_id': video['id'],
                        'description': video['snippet']['description'],
                        'published_at': video['snippet']['publishedAt'],
                        'channel_id': video['snippet']['channelId'],
                        'channel_title': video['snippet']['channelTitle'],
                        'duration_iso': duration_iso,
                        'duration_seconds': duration_seconds,
                        'duration': duration_formatted,
                        'view_count': int(video['statistics'].get('viewCount', 0)),
                        'like_count': int(video['statistics'].get('likeCount', 0)),
                        'comment_count': int(video['statistics'].get('commentCount', 0))
                    })
                
                pbar.update(len(batch_ids))
                
            except HttpError as e:
                if e.resp.status == 403:  # Quota exceeded
                    logging.error(f"API key {api_keys_copy[0]} has exceeded its quota.")
                    api_keys_copy.pop(0)
                    if not api_keys_copy:
                        raise ValueError("All API keys have exceeded their quota.")
                else:
                    raise e
    
    # Create polars DataFrame
    if video_data:
        df = pl.DataFrame(video_data)
        logging.info(f"Found {len(df)} videos for channel {channel_id}")
        return df
    else:
        logging.warning(f"No videos found for channel {channel_id}")
        return pl.DataFrame({
            'title': [],
            'video_id': [],
            'description': [],
            'published_at': [],
            'channel_id': [],
            'channel_title': [],
            'duration_iso': [],
            'duration_seconds': [],
            'duration': [],
            'view_count': [],
            'like_count': [],
            'comment_count': []
        })

# Example usage
if __name__ == "__main__":
    # Get API keys
    api_key_loc = '../../data/keys'
    with open(api_key_loc, 'r') as f:
        API_KEYS = f.read().splitlines()
    
    # Set up logging
    logging.basicConfig(level=logging.INFO)

    # Get videos for a channel using the channel ID (must start with UC)
    channel_id = "UCDRmGMSgrtZkOsh_NQl4_xw"  # Replace with actual channel ID
    channel_videos = get_channel_videos(channel_id, API_KEYS)
    
    # Display results
    print(f"Found {len(channel_videos)} videos")
    print(channel_videos.select(['title', 'video_id', 'duration', 'view_count']).head())
    
    # Optionally save to file
    channel_videos.write_csv("channel_videos.csv")

INFO:root:Using provided channel ID: UCDRmGMSgrtZkOsh_NQl4_xw
INFO:root:Using uploads playlist ID: UUDRmGMSgrtZkOsh_NQl4_xw
Fetching video IDs: 0it [00:00, ?it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 50it [00:00, 223.08it/s, total=50]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 100it [00:00, 249.60it/s, total=100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 150it [00:00, 246.91it/s, total=150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 200it [00:00, 237.99it/s, total=200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 250it [00:01, 254.70it/s, total=250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 300it [00:01, 261.35it/s, total=300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 350it [00:01, 271.91it/s, total=350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 400it [00:01, 271.35it/s, total=400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 450it [00:01, 246.39it/s, total=450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 500it [00:01, 250.36it/s, total=500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 550it [00:02, 261.52it/s, total=550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 600it [00:02, 264.45it/s, total=600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 650it [00:02, 270.21it/s, total=650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 700it [00:02, 277.51it/s, total=700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 750it [00:02, 271.96it/s, total=750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 800it [00:03, 274.27it/s, total=800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 850it [00:03, 276.36it/s, total=850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 900it [00:03, 251.75it/s, total=900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 950it [00:03, 265.00it/s, total=950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1000it [00:03, 275.58it/s, total=1000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1050it [00:03, 284.44it/s, total=1050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1100it [00:04, 274.44it/s, total=1100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1150it [00:04, 278.08it/s, total=1150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1200it [00:04, 277.72it/s, total=1200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1250it [00:04, 266.26it/s, total=1250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1300it [00:04, 277.65it/s, total=1300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1350it [00:05, 280.08it/s, total=1350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1400it [00:05, 256.44it/s, total=1400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1450it [00:05, 269.23it/s, total=1450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1500it [00:05, 274.99it/s, total=1500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1550it [00:05, 271.56it/s, total=1550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1600it [00:06, 237.05it/s, total=1600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1650it [00:06, 247.74it/s, total=1650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1700it [00:06, 263.27it/s, total=1700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1750it [00:06, 263.49it/s, total=1750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1800it [00:06, 273.10it/s, total=1800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1850it [00:07, 225.02it/s, total=1850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1900it [00:07, 245.95it/s, total=1900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 1950it [00:07, 252.57it/s, total=1950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2000it [00:07, 255.18it/s, total=2000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2050it [00:07, 266.08it/s, total=2050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2100it [00:07, 273.52it/s, total=2100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2150it [00:08, 269.27it/s, total=2150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2200it [00:08, 240.83it/s, total=2200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2250it [00:08, 256.07it/s, total=2250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2300it [00:08, 266.41it/s, total=2300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2350it [00:08, 280.36it/s, total=2350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2400it [00:09, 284.07it/s, total=2400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2450it [00:09, 283.24it/s, total=2450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2500it [00:09, 280.33it/s, total=2500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2550it [00:09, 285.30it/s, total=2550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2600it [00:09, 291.51it/s, total=2600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2650it [00:09, 300.33it/s, total=2650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2700it [00:10, 300.56it/s, total=2700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2750it [00:10, 277.05it/s, total=2750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2800it [00:10, 278.53it/s, total=2800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2850it [00:10, 293.22it/s, total=2850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2900it [00:10, 302.30it/s, total=2900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 2950it [00:10, 306.30it/s, total=2950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3000it [00:11, 300.99it/s, total=3000]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3050it [00:11, 294.81it/s, total=3050]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3100it [00:11, 295.16it/s, total=3100]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3150it [00:11, 283.37it/s, total=3150]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3200it [00:11, 276.82it/s, total=3200]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3250it [00:12, 286.09it/s, total=3250]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3300it [00:12, 289.59it/s, total=3300]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3350it [00:12, 292.91it/s, total=3350]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3400it [00:12, 297.51it/s, total=3400]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3450it [00:12, 297.70it/s, total=3450]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3500it [00:12, 296.88it/s, total=3500]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3550it [00:13, 298.15it/s, total=3550]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3600it [00:13, 300.11it/s, total=3600]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3650it [00:13, 291.21it/s, total=3650]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3700it [00:13, 279.67it/s, total=3700]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3750it [00:13, 275.20it/s, total=3750]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3800it [00:14, 243.08it/s, total=3800]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3850it [00:14, 254.87it/s, total=3850]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3900it [00:14, 239.12it/s, total=3900]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3950it [00:14, 255.24it/s, total=3950]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video IDs: 3951it [00:14, 268.18it/s, total=3951]
Fetching video details:   0%|          | 0/3951 [00:00<?, ?it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   1%|▏         | 50/3951 [00:00<00:24, 156.57it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   3%|▎         | 100/3951 [00:00<00:23, 165.81it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   4%|▍         | 150/3951 [00:00<00:23, 164.77it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   5%|▌         | 200/3951 [00:01<00:22, 165.66it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   6%|▋         | 250/3951 [00:01<00:23, 159.83it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   8%|▊         | 300/3951 [00:01<00:22, 161.39it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:   9%|▉         | 350/3951 [00:02<00:22, 158.98it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  10%|█         | 400/3951 [00:02<00:21, 164.68it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  11%|█▏        | 450/3951 [00:02<00:21, 159.83it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  13%|█▎        | 500/3951 [00:03<00:22, 156.85it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  14%|█▍        | 550/3951 [00:03<00:21, 156.38it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  15%|█▌        | 600/3951 [00:03<00:21, 159.01it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  16%|█▋        | 650/3951 [00:04<00:20, 162.97it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  18%|█▊        | 700/3951 [00:04<00:19, 164.20it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  19%|█▉        | 750/3951 [00:04<00:19, 167.41it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  20%|██        | 800/3951 [00:04<00:18, 169.89it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  22%|██▏       | 850/3951 [00:05<00:18, 169.62it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  23%|██▎       | 900/3951 [00:05<00:17, 170.63it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  24%|██▍       | 950/3951 [00:05<00:17, 169.55it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  25%|██▌       | 1000/3951 [00:06<00:17, 170.36it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  27%|██▋       | 1050/3951 [00:06<00:16, 173.86it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  28%|██▊       | 1100/3951 [00:06<00:16, 174.65it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  29%|██▉       | 1150/3951 [00:06<00:16, 172.89it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  30%|███       | 1200/3951 [00:07<00:15, 174.84it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  32%|███▏      | 1250/3951 [00:07<00:15, 175.28it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  33%|███▎      | 1300/3951 [00:07<00:16, 163.35it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  34%|███▍      | 1350/3951 [00:08<00:15, 166.40it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  35%|███▌      | 1400/3951 [00:08<00:15, 160.39it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  37%|███▋      | 1450/3951 [00:08<00:15, 159.37it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  38%|███▊      | 1500/3951 [00:09<00:15, 155.20it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  39%|███▉      | 1550/3951 [00:09<00:14, 162.41it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  40%|████      | 1600/3951 [00:09<00:14, 165.03it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  42%|████▏     | 1650/3951 [00:10<00:14, 162.05it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  43%|████▎     | 1700/3951 [00:10<00:14, 154.20it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  44%|████▍     | 1750/3951 [00:10<00:14, 154.07it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  46%|████▌     | 1800/3951 [00:11<00:13, 156.66it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  47%|████▋     | 1850/3951 [00:11<00:13, 151.63it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  48%|████▊     | 1900/3951 [00:11<00:13, 157.75it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  49%|████▉     | 1950/3951 [00:11<00:12, 156.37it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  51%|█████     | 2000/3951 [00:12<00:12, 153.84it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  52%|█████▏    | 2050/3951 [00:12<00:11, 159.27it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  53%|█████▎    | 2100/3951 [00:12<00:11, 165.20it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  54%|█████▍    | 2150/3951 [00:13<00:10, 168.12it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  56%|█████▌    | 2200/3951 [00:13<00:10, 170.31it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  57%|█████▋    | 2250/3951 [00:13<00:09, 173.18it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  58%|█████▊    | 2300/3951 [00:14<00:09, 174.46it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Fetching video details:  59%|█████▉    | 2350/3951 [00:14<00:09, 171.41it/s]INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0

Found 3951 videos
shape: (5, 4)
┌─────────────────────────────────┬─────────────┬──────────┬────────────┐
│ title                           ┆ video_id    ┆ duration ┆ view_count │
│ ---                             ┆ ---         ┆ ---      ┆ ---        │
│ str                             ┆ str         ┆ str      ┆ i64        │
╞═════════════════════════════════╪═════════════╪══════════╪════════════╡
│ The greatest offensive perform… ┆ IGt2Gx-07O8 ┆ 00:02:47 ┆ 7475       │
│ Shohei Ohtani crafted a season… ┆ lmHkqblgdec ┆ 00:14:30 ┆ 93839      │
│ Welcome to Year 2 of Top Secre… ┆ CrGp5O6FVv0 ┆ 00:04:09 ┆ 19429      │
│ Kyrie Irving’s beef with Bosto… ┆ EMDCaFsqwrU ┆ 00:14:22 ┆ 217525     │
│ Deion Sanders vs. Andre Rison … ┆ DGX9vRMYfms ┆ 00:02:08 ┆ 10951      │
└─────────────────────────────────┴─────────────┴──────────┴────────────┘

In [13]:
!pip install isodate

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting isodate
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Installing collected packages: isodate
Successfully installed isodate-0.7.2

In [15]:
channel_videos

shape: (3_951, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ title     ┆ video_id  ┆ descripti ┆ published ┆ … ┆ duration ┆ view_coun ┆ like_coun ┆ comment_c │
│ ---       ┆ ---       ┆ on        ┆ _at       ┆   ┆ ---      ┆ t         ┆ t         ┆ ount      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ i64       ┆ i64       ┆ i64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ The       ┆ IGt2Gx-07 ┆ This      ┆ 2025-05-0 ┆ … ┆ 00:02:47 ┆ 7475      ┆ 274       ┆ 5         │
│ greatest  ┆ O8        ┆ might be  ┆ 9T16:59:2 ┆   ┆          ┆           ┆           ┆           │
│ offensive ┆           ┆ too many  ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ perform…  ┆           ┆ hits an…  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Shohei    ┆ lmHkqblgd ┆ In 2024,  ┆ 2025-05-0 ┆ … ┆ 00:14:30 ┆ 93839     ┆ 3178      ┆ 280       │
│ Ohtani    ┆ ec        ┆ Los       ┆ 9T16:01:1 ┆   ┆          ┆           ┆           ┆           │
│ crafted a ┆           ┆ Angeles   ┆ 7Z        ┆   ┆          ┆           ┆           ┆           │
│ season…   ┆           ┆ Dodgers   ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ s…        ┆           ┆   ┆          ┆           ┆           ┆           │
│ Welcome   ┆ CrGp5O6FV ┆ Year one  ┆ 2025-05-0 ┆ … ┆ 00:04:09 ┆ 19429     ┆ 701       ┆ 120       │
│ to Year 2 ┆ v0        ┆ flew by   ┆ 5T17:00:1 ┆   ┆          ┆           ┆           ┆           │
│ of Top    ┆           ┆ over at   ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ Secre…    ┆           ┆ https…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ Kyrie     ┆ EMDCaFsqw ┆ Starting  ┆ 2025-05-0 ┆ … ┆ 00:14:22 ┆ 217525    ┆ 6616      ┆ 594       │
│ Irving’s  ┆ rU        ┆ in the    ┆ 2T19:00:1 ┆   ┆          ┆           ┆           ┆           │
│ beef with ┆           ┆ 2017-18   ┆ 0Z        ┆   ┆          ┆           ┆           ┆           │
│ Bosto…    ┆           ┆ season…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Deion     ┆ DGX9vRMYf ┆ Hopefully ┆ 2025-04-2 ┆ … ┆ 00:02:08 ┆ 10951     ┆ 368       ┆ 4         │
│ Sanders   ┆ ms        ┆ , Shedeur ┆ 5T19:25:0 ┆   ┆          ┆           ┆           ┆           │
│ vs. Andre ┆           ┆ can learn ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ Rison …   ┆           ┆ f…        ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ Westminst ┆ 65rlXiWlb ┆ Full      ┆ 2012-02-1 ┆ … ┆ 00:02:16 ┆ 10468     ┆ 36        ┆ 3         │
│ er Kennel ┆ xU        ┆ story:    ┆ 4T23:43:0 ┆   ┆          ┆           ┆           ┆           │
│ Club Dog  ┆           ┆ http://ww ┆ 3Z        ┆   ┆          ┆           ┆           ┆           │
│ Sh…       ┆           ┆ w.sbnatio ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ …         ┆           ┆   ┆          ┆           ┆           ┆           │
│ A Super   ┆ _p_rzRkz6 ┆ Gary      ┆ 2012-02-0 ┆ … ┆ 00:04:03 ┆ 5737      ┆ 31        ┆ 3         │
│ Bowl      ┆ YA        ┆ Grimes    ┆ 3T08:00:4 ┆   ┆          ┆           ┆           ┆           │
│ Gesture:  ┆           ┆ nearly    ┆ 6Z        ┆   ┆          ┆           ┆           ┆           │
│ Giants C… ┆           ┆ died in a ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ c…        ┆           ┆   ┆          ┆           ┆           ┆           │
│ Super     ┆ FGGggOPCo ┆ Top       ┆ 2012-02-0 ┆ … ┆ 00:04:39 ┆ 4729      ┆ 21        ┆ 6         │
│ Bowl      ┆ k0        ┆ Chef's    ┆ 2T18:23:2 ┆   ┆          ┆           ┆           ┆           │
│ Party     ┆           ┆ Eli       ┆ 6Z        ┆   ┆          ┆           ┆           ┆           │
│ Tips: Eli ┆           ┆ Kirshtein ┆           ┆   ┆          ┆           ┆           ┆           │
│ Kir…      ┆           ┆ helps…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ Pro       ┆ MHza9mqt0 ┆ Subscribe ┆ 2011-12-2 ┆ … ┆ 00:00:49 ┆ 4053      ┆ 44        ┆ 18        │
│ Quality,  ┆ Zk        ┆ to our    ┆ 2T18:37:2 ┆   ┆          ┆           ┆           ┆           │
│ Fan Persp ┆           ┆ channel   ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ ective -… ┆           ┆ for m…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ Pro       ┆ 2qccmZk92 ┆ Subscribe ┆ 2011-12-2 ┆ … ┆ 00:00:14 ┆ 9710      ┆ 55        ┆ 14        │
│ Quality,  ┆ Aw        ┆ to our    ┆ 2T18:36:5 ┆   ┆          ┆           ┆           ┆           │
│ Fan Persp ┆           ┆ channel   ┆ 6Z        ┆   ┆          ┆           ┆           ┆           │
│ ective -… ┆           ┆ for m…    ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [29]:
channel_videos.filter(
    # pl.col('description').str.contains('Jon Bois'),
    pl.col('description').str.contains('Alex Rubenstein'),
    pl.col('description').str.contains('written') | pl.col('description').str.contains('Written'),
    pl.col('duration_seconds') >= 60 * 8,
    # pl.col('duration_seconds') <= 60 * 24,
).sort('duration')

shape: (32, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ title     ┆ video_id  ┆ descripti ┆ published ┆ … ┆ duration ┆ view_coun ┆ like_coun ┆ comment_c │
│ ---       ┆ ---       ┆ on        ┆ _at       ┆   ┆ ---      ┆ t         ┆ t         ┆ ount      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆          ┆ i64       ┆ i64       ┆ i64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ The worst ┆ -8dGx-Ra8 ┆ When the  ┆ 2019-02-2 ┆ … ┆ 00:08:05 ┆ 1611919   ┆ 25534     ┆ 1093      │
│ NBA       ┆ xA        ┆ Denver    ┆ 1T16:00:4 ┆   ┆          ┆           ┆           ┆           │
│ playoff   ┆           ┆ Nuggets   ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ game was… ┆           ┆ visite…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ How many  ┆ mCW9n4TYk ┆ A quarter ┆ 2019-07-0 ┆ … ┆ 00:10:11 ┆ 329896    ┆ 5453      ┆ 327       │
│ passes    ┆ Ys        ┆ back      ┆ 2T15:18:3 ┆   ┆          ┆           ┆           ┆           │
│ can you   ┆           ┆ dropping  ┆ 4Z        ┆   ┆          ┆           ┆           ┆           │
│ throw …   ┆           ┆ back ti…  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Antonio   ┆ iVn37ndpk ┆ For more  ┆ 2019-04-1 ┆ … ┆ 00:10:28 ┆ 2899759   ┆ 32365     ┆ 4229      │
│ Brown's   ┆ Ic        ┆ Pennsylva ┆ 1T14:30:1 ┆   ┆          ┆           ┆           ┆           │
│ beef with ┆           ┆ nia-based ┆ 1Z        ┆   ┆          ┆           ┆           ┆           │
│ Ben …     ┆           ┆ qu…       ┆           ┆   ┆          ┆           ┆           ┆           │
│ How the   ┆ NkOtndaSt ┆ The       ┆ 2019-03-2 ┆ … ┆ 00:12:09 ┆ 1423645   ┆ 21956     ┆ 2081      │
│ Marlins   ┆ zo        ┆ Florida   ┆ 7T17:00:1 ┆   ┆          ┆           ┆           ┆           │
│ accidenta ┆           ┆ Marlins   ┆ 2Z        ┆   ┆          ┆           ┆           ┆           │
│ lly w…    ┆           ┆ became    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ the…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ Correctin ┆ 5E7Z84Wtt ┆ Want more ┆ 2024-09-1 ┆ … ┆ 00:14:00 ┆ 173598    ┆ 9425      ┆ 680       │
│ g the     ┆ Ic        ┆ for       ┆ 7T17:00:0 ┆   ┆          ┆           ┆           ┆           │
│ NFL’s     ┆           ┆ Secret    ┆ 3Z        ┆   ┆          ┆           ┆           ┆           │
│ passer    ┆           ┆ Base?     ┆           ┆   ┆          ┆           ┆           ┆           │
│ ra…       ┆           ┆ Goo…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ “You      ┆ ymLqLKkRt ┆ It’s the  ┆ 2023-08-2 ┆ … ┆ 01:22:55 ┆ 548691    ┆ 9192      ┆ 1006      │
│ don’t     ┆ Qk        ┆ 1980s.    ┆ 3T01:00:0 ┆   ┆          ┆           ┆           ┆           │
│ belong    ┆           ┆ The       ┆ 9Z        ┆   ┆          ┆           ┆           ┆           │
│ here” |   ┆           ┆ Vikings’  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Dork…     ┆           ┆ s…        ┆           ┆   ┆          ┆           ┆           ┆           │
│ The two   ┆ jGoZiKz6a ┆ The 1990s ┆ 2023-08-3 ┆ … ┆ 01:26:52 ┆ 545034    ┆ 8565      ┆ 1195      │
│ heroes |  ┆ qQ        ┆ Minnesota ┆ 0T01:00:0 ┆   ┆          ┆           ┆           ┆           │
│ Dorktown  ┆           ┆ Vikings   ┆ 7Z        ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ we…       ┆           ┆   ┆          ┆           ┆           ┆           │
│ It’s a    ┆ aV-8cG63o ┆ Orange    ┆ 2021-09-0 ┆ … ┆ 01:37:47 ┆ 878759    ┆ 19461     ┆ 6049      │
│ funny     ┆ 2w        ┆ man bad!  ┆ 7T17:00:1 ┆   ┆          ┆           ┆           ┆           │
│ story |   ┆           ┆ Football  ┆ 6Z        ┆   ┆          ┆           ┆           ┆           │
│ The       ┆           ┆ team …    ┆           ┆   ┆          ┆           ┆           ┆           │
│ Histo…    ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Aw, dang  ┆ AQqZwO-vF ┆ This is a ┆ 2023-09-0 ┆ … ┆ 01:39:43 ┆ 656787    ┆ 8921      ┆ 1466      │
│ it |      ┆ Po        ┆ super-siz ┆ 6T01:00:0 ┆   ┆          ┆           ┆           ┆           │
│ Dorktown  ┆           ┆ ed        ┆ 9Z        ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ episode … ┆           ┆   ┆          ┆           ┆           ┆           │
│ You gotta ┆ GULCd-oOs ┆ In this   ┆ 2023-09-0 ┆ … ┆ 01:43:04 ┆ 510220    ┆ 11399     ┆ 2183      │
│ live with ┆ 1A        ┆ series    ┆ 9T01:00:1 ┆   ┆          ┆           ┆           ┆           │
│ the       ┆           ┆ finale of ┆ 0Z        ┆   ┆          ┆           ┆           ┆           │
│ bounce…   ┆           ┆ The H…    ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘